"""Verify the installed ``guardkit`` shell wrapper exposes ``feature``.

Pins TASK-FPSG-004 (L3d) installer half: ``installer/scripts/install.sh``
emits a shell wrapper at ``~/.agentecflow/bin/guardkit`` that must
register a ``feature)`` case arm so

    ~/.agentecflow/bin/guardkit feature validate FEAT-XXXX

reaches ``cli/feature.py`` instead of falling through to the
``Unknown command: feature`` error.

We can't run the full installer in CI, so this test asserts on the
content of the heredoc inside ``install.sh``. The heredoc is the
single source of truth for the wrapper: the installer just writes it
verbatim to ``$INSTALL_DIR/bin/guardkit``. If the heredoc has the arm,
fresh installs have it; if it doesn't, fresh installs won't.

A true end-to-end post-install smoke test (running the installer in a
sandboxed home, then exec'ing the wrapper) is out of scope — it
requires write access to ``$HOME``, network for ``pip install``, and
~30 s wall-clock per run. The content test below is the
no-side-effects equivalent.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Fixture: load the install.sh source
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def install_sh_text() -> str:
    """Return the full text of ``installer/scripts/install.sh``."""
    repo_root = Path(__file__).resolve().parents[3]
    install_sh = repo_root / "installer" / "scripts" / "install.sh"
    assert install_sh.is_file(), (
        f"installer/scripts/install.sh not found at {install_sh} — "
        f"this test pins the wrapper heredoc, so the source script "
        f"must exist."
    )
    return install_sh.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def guardkit_wrapper_heredoc(install_sh_text: str) -> str:
    """Extract the ``cat > "$INSTALL_DIR/bin/guardkit" << 'EOF' ... EOF`` body.

    The wrapper is generated by exactly one heredoc in install.sh; this
    fixture pulls that heredoc out so assertions only run against the
    wrapper text, not (for example) the ``guardkit-init`` heredoc that
    lives a few hundred lines earlier in the same file.
    """
    # The opening line is:
    #   cat > "$INSTALL_DIR/bin/guardkit" << 'EOF'
    # The closing line is a single ``EOF`` (followed by chmod +x).
    # We use a non-greedy match between those anchors.
    pattern = re.compile(
        r'cat > "\$INSTALL_DIR/bin/guardkit" << \'EOF\'\n(.*?)\nEOF',
        re.DOTALL,
    )
    match = pattern.search(install_sh_text)
    assert match is not None, (
        "Could not locate the ``$INSTALL_DIR/bin/guardkit`` heredoc in "
        "install.sh. The wrapper-generation source moved or the test "
        "assumption is stale — update this test to find it."
    )
    return match.group(1)


# ---------------------------------------------------------------------------
# AC: feature subcommand is registered in the wrapper case statement
# ---------------------------------------------------------------------------


def test_wrapper_contains_feature_case_arm(
    guardkit_wrapper_heredoc: str,
) -> None:
    """The wrapper's case statement must have a ``feature)`` arm."""
    # Match the arm header with its closing paren on the same line, the
    # same way ``autobuild)`` and ``graphiti)`` are written in the file.
    # Anchored at line start to avoid false positives on usage strings
    # like "guardkit feature validate".
    assert re.search(
        r"^\s*feature\)\s*$", guardkit_wrapper_heredoc, re.MULTILINE
    ), (
        "Expected a ``feature)`` case arm in the guardkit wrapper "
        "heredoc. Without it, ``guardkit feature validate FEAT-XXXX`` "
        "falls through to the `Unknown command: feature` error and "
        "/feature-plan Step 8.5 silently no-ops."
    )


def test_wrapper_feature_arm_execs_guardkit_py(
    guardkit_wrapper_heredoc: str,
) -> None:
    """The ``feature)`` arm must delegate to ``guardkit-py feature``.

    Mirrors the ``autobuild)`` and ``graphiti)`` arms — they all forward
    their arguments to the same Python entry point so behaviour stays
    consistent.
    """
    # Look for the canonical exec line. We don't pin the exact spacing
    # so reformatting doesn't break the test, but we do require the
    # ``"$GUARDKIT_PY" feature "$@"`` form so the args-passthrough
    # contract is preserved.
    assert re.search(
        r'exec\s+"\$GUARDKIT_PY"\s+feature\s+"\$@"',
        guardkit_wrapper_heredoc,
    ), (
        "Expected ``exec \"$GUARDKIT_PY\" feature \"$@\"`` inside the "
        "feature) arm. The arm must delegate to the Python CLI so "
        "``guardkit feature validate`` reaches cli/feature.py."
    )


def test_wrapper_help_text_lists_feature_command(
    guardkit_wrapper_heredoc: str,
) -> None:
    """``guardkit help`` must advertise the new feature subcommand.

    Without this line, agents discover the gap only at the
    ``Unknown command`` error — the help text is the canonical surface
    that ``/feature-plan`` agents read to decide which subcommands are
    available.
    """
    # Pin the canonical help line. This is the descriptor printed by
    # ``print_help`` inside the wrapper; agents grep for it to verify
    # /feature-plan Step 8.5 is supported.
    assert re.search(
        r"feature\s+<cmd>\s+Feature YAML management",
        guardkit_wrapper_heredoc,
    ), (
        "Expected ``feature <cmd>     Feature YAML management ...`` in "
        "the wrapper's print_help block — this is what agents and "
        "users see when running ``guardkit help``."
    )


def test_wrapper_help_text_lists_feature_validate_example(
    guardkit_wrapper_heredoc: str,
) -> None:
    """``guardkit help`` must show the ``feature validate FEAT-XXXX`` example.

    The example is what the agent copies into Step 8.5 — without it,
    a fresh install can register ``feature`` but the agent doesn't know
    what subcommands exist underneath.
    """
    assert re.search(
        r"feature validate FEAT-XXXX", guardkit_wrapper_heredoc
    ), (
        "Expected ``feature validate FEAT-XXXX`` example in the "
        "wrapper's print_help block."
    )
