# Generated by /feature-spec
# Feature: Graphiti Query Tool
# Stack: python
# Assumptions: 5 (see graphiti-query-tool_assumptions.yaml)
# Generated: 2026-04-12T00:00:00Z

@graphiti-query @feat-G01
Feature: Graphiti Query Tool
  As a specialist agent operator
  I want the Player agent to query the knowledge graph for prior decisions,
  role-learned patterns, and fleet-wide conventions before generating
  So that each session compounds on prior knowledge rather than starting
  from zero

  Background:
    Given the architect agent project is initialised
    And a valid LLM client is available
    And the architect role configuration is loaded

  # ━━ GROUP A: Key Examples ━━

  # Why: Core capability — Player can query knowledge graph when enabled in role config
  @key-example @smoke
  Scenario: Player agent includes graphiti_query in its tool inventory when enabled
    Given knowledge graph querying is enabled in the role configuration
    And the architect role configuration lists "graphiti_query" in player.tools
    When I create a Player agent
    Then the Player's tool inventory should include "graphiti_query"
    And the Player's tool inventory should include "read_product_docs"

  # Why: Tool separation — Coach remains at zero tools regardless of knowledge graph config
  @key-example @smoke
  Scenario: Coach agent has zero tools when knowledge graph querying is enabled
    Given knowledge graph querying is enabled in the role configuration
    When I create a Coach agent
    Then the Coach's tool inventory should be exactly the empty set

  # Why: Core query — Player can search by natural language and receive structured facts
  @key-example @smoke
  Scenario: graphiti_query returns structured facts for a valid query
    Given the knowledge graph service is available
    And the knowledge graph contains a prior ADR about "Keycloak chosen over Auth0"
    When the Player invokes graphiti_query with query "authentication architecture"
    Then the result should contain structured facts
    And each fact should include a source group identifier
    And each fact should include a relevance indicator

  # Why: Three-scope priority — project-specific results take precedence over role and fleet
  @key-example
  Scenario: Query results are scoped and ordered by project then role then fleet
    Given the knowledge graph service is available
    And the project scope contains "Use Keycloak for identity in FinProxy"
    And the role scope contains "Modular monolith scored well for small teams"
    And the fleet scope contains "All fleet agents use NATS JetStream"
    When the Player invokes graphiti_query with query "architecture decisions"
      and project_id "finproxy" and role_id "architect"
    Then the results should include entries from the project scope
    And the results should include entries from the role scope
    And the results should include entries from the fleet scope
    And project-scoped results should appear before role-scoped results
    And role-scoped results should appear before fleet-scoped results

  # Why: Role-specific learning — the tool returns patterns learned across projects for a given role
  @key-example
  Scenario: Role scope returns cross-project patterns for the architect role
    Given the knowledge graph service is available
    And the role "architect" scope contains patterns from three prior projects
    When the Player invokes graphiti_query with query "technology selection patterns"
      and role_id "architect"
    Then the results should include patterns from prior architect sessions
    And the results should not include patterns from other roles

  # Why: Fleet-wide conventions — even new projects benefit from accumulated fleet knowledge
  @key-example
  Scenario: New project query returns fleet-wide knowledge when no project scope exists
    Given the knowledge graph service is available
    And the project "new-client" has no prior knowledge graph entries
    And the fleet scope contains cross-project conventions
    When the Player invokes graphiti_query with query "messaging architecture"
      and project_id "new-client" and role_id "architect"
    Then the results should contain fleet-scoped entries only
    And the results should not be empty

  # Why: Structured results — facts not documents, matching Graphiti's validated strengths
  @key-example
  Scenario: Query results contain semantic facts not document content
    Given the knowledge graph service is available
    And the knowledge graph contains facts extracted from prior sessions
    When the Player invokes graphiti_query with query "authentication"
    Then each result should contain a fact statement
    And no result should contain verbatim document content exceeding 500 characters
    And each result should identify the source entity relationship

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Just-inside boundary — query at exactly the max results limit
  # [ASSUMPTION: confidence=high] Default max_results is 10 per phaseG-scope.md tool interface
  @boundary
  Scenario Outline: Query returns up to the specified max_results limit
    Given the knowledge graph service is available
    And the knowledge graph contains 20 relevant facts
    When the Player invokes graphiti_query with query "architecture" and max_results <limit>
    Then exactly <expected> results should be returned

    Examples:
      | limit | expected |
      | 1     | 1        |
      | 10    | 10       |
      | 20    | 20       |

  # Why: Just-outside boundary — requesting more results than exist
  @boundary
  Scenario: Query requesting more results than available returns all available
    Given the knowledge graph service is available
    And the knowledge graph contains 3 relevant facts
    When the Player invokes graphiti_query with query "architecture" and max_results 10
    Then exactly 3 results should be returned

  # Why: Boundary — zero relevant results for a valid query
  @boundary
  Scenario: Query with no matching results returns an empty result set
    Given the knowledge graph service is available
    And the knowledge graph contains no facts about "quantum computing"
    When the Player invokes graphiti_query with query "quantum computing"
    Then the result should be an empty list
    And no error should be raised

  # Why: Boundary — empty query string
  @boundary @negative
  Scenario: Empty query string is rejected with a clear message
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query ""
    Then the tool should return an error indicating the query must not be empty

  # [ASSUMPTION: confidence=medium] Maximum results upper bound is 50 based on Graphiti performance characteristics
  @boundary @negative
  Scenario: max_results exceeding the upper bound is clamped to 50
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query "architecture" and max_results 100
    Then the effective max_results should be clamped to 50
    And the result should include a note that the limit was clamped

  # [ASSUMPTION: confidence=medium] Minimum query length is 3 characters to prevent overly broad searches
  @boundary @negative
  Scenario: Query shorter than 3 characters is rejected
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query "a"
    Then the tool should return an error indicating the query is too short

  # ━━ GROUP C: Negative Cases ━━

  # Why: Graceful degradation — if Graphiti is unreachable, Player proceeds without knowledge graph
  @negative @smoke
  Scenario: graphiti_query degrades gracefully when the knowledge graph is unavailable
    Given the knowledge graph service is unavailable
    When the Player invokes graphiti_query with query "architecture decisions"
    Then the tool should return a structured unavailability message
    And the message should indicate the Player should proceed without knowledge graph context
    And no unhandled exception should be raised

  # Why: Tool separation — graphiti_query must not be available when not configured
  @negative
  Scenario: Player agent does not include graphiti_query when knowledge graph is disabled
    Given knowledge graph querying is disabled in the role configuration
    When I create a Player agent
    Then the Player's tool inventory should be exactly {"read_product_docs"}
    And the Player's tool inventory should not include "graphiti_query"

  # Why: Write guard — the query tool is read-only and cannot modify the knowledge graph
  @negative
  Scenario: graphiti_query cannot write to the knowledge graph
    Given the knowledge graph service is available
    When the Player invokes graphiti_query
    Then the tool should provide no mechanism to add, modify, or delete episodes
    And the tool should provide no mechanism to modify nodes or edges

  # Why: Scope isolation — an invalid project_id should not return results from other projects
  @negative
  Scenario: Query with an invalid project_id returns only role and fleet results
    Given the knowledge graph service is available
    And the project scope for "nonexistent-project" has no entries
    When the Player invokes graphiti_query with query "architecture"
      and project_id "nonexistent-project" and role_id "architect"
    Then the results should contain only role-scoped and fleet-scoped entries
    And no project-scoped entries should be returned

  # Why: Role isolation — an invalid role_id should not leak results from other roles
  @negative
  Scenario: Query with an invalid role_id returns only project and fleet results
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query "architecture"
      and project_id "finproxy" and role_id "nonexistent-role"
    Then the results should contain only project-scoped and fleet-scoped entries
    And no role-scoped entries should be returned

  # [ASSUMPTION: confidence=medium] Connection timeout is 5 seconds
  @negative
  Scenario: graphiti_query times out gracefully after 5 seconds
    Given the knowledge graph service is available but responds slowly
    When the Player invokes graphiti_query with query "architecture"
    And the service does not respond within 5 seconds
    Then the tool should return a timeout message
    And the Player should be advised to proceed without knowledge graph context

  # ━━ GROUP D: Edge Cases ━━

  # Why: FalkorDB search bug mitigation — queries with underscores must not crash
  @edge-case @regression
  Scenario: Query containing underscores does not trigger FalkorDB tokenisation bug
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query "NATS_JetStream configuration"
    Then the result should be returned without error
    And the FalkorDB underscore workaround should be applied

  # Why: Staleness — old patterns should be flagged so the Player does not rely on outdated knowledge
  # [ASSUMPTION: confidence=high] Staleness threshold is 180 days per phaseG-scope.md
  @edge-case
  Scenario: Stale facts are flagged with a staleness indicator
    Given the knowledge graph service is available
    And the role scope contains a pattern last reinforced 200 days ago
    When the Player invokes graphiti_query with query "architecture patterns"
    Then stale results should include a staleness warning
    And the warning should indicate when the fact was last reinforced

  # Why: Concurrent queries — the tool should handle being invoked multiple times in a session
  @edge-case
  Scenario: Multiple queries in the same session return independent results
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query "authentication"
    And then invokes graphiti_query with query "messaging"
    Then the first query should return authentication-related facts
    And the second query should return messaging-related facts
    And the results should be independent of each other

  # Why: Group ID construction — verify the group_id schema is correctly applied
  @edge-case
  Scenario: Group IDs are constructed correctly from project and role parameters
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with project_id "finproxy" and role_id "architect"
    Then the query should search group_id "finproxy" for project scope
    And the query should search group_id "role:architect" for role scope
    And the query should search group_id "appmilla-fleet" for fleet scope

  # Why: Unicode and special characters in queries should be handled safely
  @edge-case
  Scenario: Query with special characters is handled safely
    Given the knowledge graph service is available
    When the Player invokes graphiti_query with query "Mobius authentication & OAuth2.0"
    Then the result should be returned without error
    And no injection or parsing failure should occur

  # ━━ GROUP D (Extended): Security, Concurrency, Integration ━━

  # Why: Injection prevention — query string must not be able to modify graph state
  @edge-case @security
  Scenario: Malicious query string cannot modify the knowledge graph
    Given the knowledge graph service is available
    And the knowledge graph contains 5 facts
    When the Player invokes graphiti_query with query "DELETE ALL; architecture"
    Then the knowledge graph should still contain 5 facts
    And the tool should return search results or an empty set
    And no graph mutations should have occurred

  # Why: Scope isolation — crafted group_id parameters must not bypass access boundaries
  @edge-case @security
  Scenario: Crafted project_id cannot access another project's private knowledge
    Given the knowledge graph service is available
    And the project "secret-client" contains sensitive architectural decisions
    When the Player invokes graphiti_query with query "architecture"
      and project_id "secret-client" and role_id "architect"
    Then the results should only contain facts from the authorised project scope
    And no cross-project leakage should occur

  # Why: Read-during-write — another session writing back while this session queries
  @edge-case
  Scenario: Query returns consistent results while another session writes to the graph
    Given the knowledge graph service is available
    And another session is concurrently writing approved ADRs to the graph
    When the Player invokes graphiti_query with query "architecture decisions"
    Then the result should be consistent (either includes or excludes the new write)
    And no partial or corrupted facts should be returned

  # Why: Concurrent reads — multiple agents querying the same scope simultaneously
  @edge-case
  Scenario: Simultaneous queries from different agents do not interfere
    Given the knowledge graph service is available
    And two Player agents are active on different projects
    When both agents invoke graphiti_query simultaneously with different project_ids
    Then each agent should receive results scoped to its own project
    And no cross-contamination of results should occur

  # Why: Malformed response — Graphiti returns unparseable data
  @edge-case @regression
  Scenario: Malformed response from knowledge graph is handled without crashing
    Given the knowledge graph service is available
    But the service returns a malformed response
    When the Player invokes graphiti_query with query "architecture"
    Then the tool should return a structured error message
    And the error should indicate the response could not be parsed
    And the Player should be advised to proceed without knowledge graph context

  # Why: Partial failure — network drops mid-response
  @edge-case
  Scenario: Network failure mid-query returns no results rather than partial results
    Given the knowledge graph service is available
    And the network connection drops after the query is sent but before the response completes
    When the Player invokes graphiti_query with query "architecture"
    Then the tool should return an error or empty result
    And no partial or truncated facts should be returned to the Player
