# Generated by /feature-spec
# Feature: architect_feature_plan specialist tool (FEAT-SPL-008)
# Stack: python
# Assumptions: 12 (see architect-feature-plan-specialist-tool_assumptions.yaml)
# Generated: 2026-07-07T13:25:13+01:00

@architect-feature-plan @feat-spl-008
Feature: architect_feature_plan specialist tool — headless /feature-plan as an architect plan mode
  As the forge Mode P planner
  I want the local Architect specialist to turn a validated feature specification into the feature/task/wave YAML contract and its task documents, headlessly, with every planning preference resolved to a recorded default instead of a question
  So that autobuild receives a plan that passes the guardkit feature validate oracle without an attended Claude Code session, completing the local spec-to-plan chain

  Background:
    Given the architect role registers a plan mode named architect_feature_plan
    And the pinned /feature-plan methodology template is loadable from the installed guardkit package
    And a validated feature specification with its spec summary is supplied as the planning input

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A: Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: The core contract — validated spec in, oracle-conformant feature
  # YAML plus task documents out, as one returned artifact set.
  @task:TASK-SPL8-006
  @key-example @smoke
  Scenario: Generating the feature plan from a validated specification
    Given the specification describes a feature with several distinct pieces of work
    When the architect_feature_plan session runs to completion
    Then a feature definition, its task documents, and a plan document are returned as one artifact set
    And the feature definition conforms to the pinned feature/task/wave contract
    And the feature definition passes the deterministic validate oracle when written into a repository alongside its task documents

  # Why: Wave detection is the plan's load-bearing structure — dependencies
  # decide sequencing, independence decides parallelism.
  @task:TASK-SPL8-003
  @key-example @smoke
  Scenario: Waves are derived from task dependencies
    Given the plan contains tasks where some depend on the outputs of others
    When the feature definition is generated
    Then every task that depends on another appears in a later wave than that dependency
    And tasks with no dependency relationship may share a wave
    And every task appears in exactly one wave

  # Why: Task frontmatter is the CoachValidator's routing input — a task
  # without a valid type gets the wrong quality gates downstream.
  @task:TASK-SPL8-003
  @key-example @smoke
  Scenario: Every task document carries the required frontmatter
    When the feature definition is generated
    Then every task document declares a task type from the pinned valid set
    And every task document carries the feature identifier that groups it with its siblings
    And every task entry in the feature definition names a task document path under the tasks directory

  # Why: Seam v1.1 — same pinned-data posture as the spec tool; the plan
  # methodology is data, not behaviour baked into the harness.
  @key-example
  Scenario: The methodology template is consumed as pinned data
    Given the installed guardkit package provides the feature-plan methodology at a recorded version
    When the session starts
    Then the session records the template version it loaded
    And the session proceeds only when the loaded version matches the pinned version

  # Why: The gold traces show three interaction points (review scope, the
  # implement decision, implementation preferences) — headless mode must
  # resolve all three to defaults and leave an audit trail, never a question.
  @task:TASK-SPL8-005
  @key-example @smoke
  Scenario: Planning preferences resolve to recorded defaults instead of questions
    Given the methodology defines clarification points for review scope and implementation preferences
    When the architect_feature_plan session runs headlessly
    # [ASSUMPTION: confidence=low] Headless runs use the template's no-questions defaults path, and each auto-resolved decision is recorded as a deferred assumption in the returned plan document
    Then no question is addressed to a human at any point in the session
    And each auto-resolved planning decision is recorded in the returned plan document with its chosen default
    And each recorded decision is marked as deferred for human review

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B: Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — the smallest valid plan is one task in one
  # wave, and it must still satisfy the full contract.
  @task:TASK-SPL8-006
  @boundary
  Scenario: A single-task feature produces a single-wave plan
    Given the specification describes one indivisible piece of work
    When the feature definition is generated
    Then the plan contains exactly one task in exactly one wave
    And the feature definition still passes the deterministic validate oracle

  # Why: The complexity threshold decides the implementation mode — both
  # sides of the boundary must be exact.
  @task:TASK-SPL8-003
  @boundary
  Scenario Outline: Implementation mode follows the complexity boundary
    Given a task assessed at complexity <complexity>
    When the feature definition is generated
    Then that task's implementation mode is <mode>

    Examples:
      | complexity | mode      |
      | 3          | direct    |
      | 4          | task-work |

  # Why: Boundary on the revision loop — validate-failure feedback is
  # bounded, and exhausting it is where PLANNED-HANDOFF degradation begins.
  @task:TASK-SPL8-006
  @boundary
  Scenario: Validate-failure revisions stop at the configured cap
    Given the validate oracle rejects the generated feature definition on every revision
    When the revision cap is reached
    Then the session ends with an explicit not-accepted outcome
    And the last feature definition and the outstanding oracle errors are returned with the outcome

  # Why: The smoke-gate activation nudge fires at exactly two waves — the
  # boundary where between-wave composition checks first become possible.
  @task:TASK-SPL8-005
  @boundary
  Scenario: A multi-wave plan without smoke gates carries an activation notice
    Given the generated plan organises its tasks into two or more waves
    And no smoke gate could be derived from the supplied context
    When the artifact set is returned
    Then the plan document records that the feature's waves are ungated
    And the notice names the smoke-gate block as the one edit needed to activate between-wave checks

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C: Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: The input contract is a VALIDATED spec — planning from an unreviewed
  # or incomplete specification would launder unapproved scope into the build.
  @task:TASK-SPL8-006
  @negative
  Scenario: An incomplete specification input fails the session cleanly
    Given the planning request supplies a specification without its spec summary
    When an architect_feature_plan session is requested
    Then the session fails before any plan is generated
    And the failure names the missing input
    And no partial artifact set is returned

  # Why: Same version-pin discipline as the spec tool — a drifted plan
  # methodology must refuse, not silently serve.
  @negative @smoke
  Scenario: An unpinned or mismatched template version refuses to serve
    Given the installed guardkit package provides a template version that differs from the pin
    When an architect_feature_plan session is requested
    Then the session refuses to start
    And the refusal names the pinned version and the version found

  # Why: The tool must not return a plan it can already prove the oracle
  # will reject — unknown dependencies are mechanically checkable.
  @task:TASK-SPL8-003
  @negative
  Scenario: A plan referencing an unknown dependency is not returned as accepted
    Given the player proposes a task depending on a task identifier that appears nowhere in the plan
    When the session finalises its artifacts
    Then the artifact set is not returned as accepted
    And the unknown dependency is reported for revision

  # Why: Intra-wave dependencies are the wave model's canonical contradiction
  # — parallel tasks cannot wait for each other.
  @task:TASK-SPL8-003
  @negative
  Scenario: A plan with an intra-wave dependency is not returned as accepted
    Given the player proposes two tasks in the same wave where one depends on the other
    When the session finalises its artifacts
    Then the artifact set is not returned as accepted
    And the conflicting wave placement is reported for revision

  # Why: A task entry without a document path is the documented FeatureLoader
  # hard-failure — the known sharpest edge of the YAML contract.
  @task:TASK-SPL8-003
  @negative
  Scenario: A task entry without a document path is not returned as accepted
    Given the player proposes a task entry that names no task document path
    When the session finalises its artifacts
    Then the artifact set is not returned as accepted
    And the incomplete task entry is reported for revision

  # Why: An invalid task type routes a task to the wrong quality gates —
  # the valid set is pinned and checkable at generation time.
  @task:TASK-SPL8-003
  @negative
  Scenario: A task document with an unrecognised task type is not returned as accepted
    Given the player proposes a task document whose declared type is outside the pinned valid set
    When the session finalises its artifacts
    Then the artifact set is not returned as accepted
    And the unrecognised type and the valid set are reported for revision

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D: Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Cross-repo deliverables silently break the autobuild evidence
  # boundary unless declared — detection at plan time is the cheap fix.
  @task:TASK-SPL8-005
  @edge-case
  Scenario: A task targeting a sibling repository declares the evidence boundary
    Given the specification describes work whose deliverable lives in a sibling repository
    When the feature definition is generated
    Then the feature definition declares the sibling repository as an evidence repository
    And that task's expected files are recorded in repository-qualified form

  # Why: Live-infrastructure acceptance criteria cannot be satisfied by the
  # autonomous build loop — headless mode must tag without the interactive
  # prompt the template prescribes, biased toward tagging.
  @task:TASK-SPL8-005
  @edge-case
  Scenario: Live-infrastructure work is tagged for operator handoff without prompting
    Given the specification contains an acceptance criterion requiring observation of a live service
    When the feature definition is generated
    # [ASSUMPTION: confidence=low] Headless detection auto-applies the operator-handoff type on strong signals because the template's interactive confirmation prompt has no human to ask
    Then the affected task is typed as operator handoff
    And the plan document reports the count of operator follow-up tasks

  # Why: Smoke-gate paths must verify against a real tests tree, and the
  # headless tool has no repository checkout — unverifiable paths must be
  # omitted rather than invented (the documented invented-paths defect class).
  @task:TASK-SPL8-005
  @edge-case
  Scenario: Smoke gates are only emitted with verifiable test roots
    Given the supplied context does not establish the target repository's test directory layout
    When the feature definition is generated
    Then the feature definition contains no smoke-gate block
    And the plan document records why the smoke gate was omitted

  # Why: Gold-trace reproducibility is a stated Session D validation
  # criterion for the plan side as much as the spec side.
  @task:TASK-SPL8-006
  @edge-case
  Scenario: Re-running the same specification produces a structurally equivalent plan
    Given an architect_feature_plan session has previously completed for a specification
    When a new session runs with the same specification and context
    Then the new plan has the same task decomposition and wave structure
    And any differences are in wording rather than in work covered
