# Generated by /feature-spec
# Feature: Output Quality — Preferred Directions, Source Documents, Research Topics
# Stack: python
# Assumptions: 3 (see output-quality-preferred-directions-source-docs-research-topics_assumptions.yaml)
# Generated: 2026-04-11T00:00:00Z

@output @feat-006
Feature: Output Quality — Preferred Directions with Tradeoffs, Source Documents, Research Topics
  As an architect agent developer preparing a conversation starter for /system-arch
  I want the formatter to render tradeoff-aware decisions, a source documents table, and a research topics list
  So that the reviewer can see what the agent gave up for each decision, which docs influenced the output, and where deeper investigation is still needed

  Background:
    Given a valid session with project name "FinProxy"
    And a conversation starter containing a context-level and a container-level C4 diagram
    And an evaluation produced by the Coach

  # ━━ GROUP A: Key Examples ━━

  # Why: The formatter contract has grown from 9 to 11 sections — this is the anchor scenario
  @key-example @smoke
  Scenario: Formatting a complete conversation starter produces all 11 sections in order
    Given a conversation starter with decisions, source documents, and research topics populated
    When I format the conversation starter
    Then the output should contain the 11 required sections in this order:
      | section                                                    |
      | # FinProxy -- Conversation Starter                         |
      | ## Purpose of this document                                |
      | ## What is FinProxy?                                       |
      | ## Key architectural principle                             |
      | ## C4 Level 1: System Context                              |
      | ## C4 Level 2: Container Diagram                           |
      | ## Preferred Decisions (challenge only with new evidence)  |
      | ## Open Questions for /system-arch to Resolve              |
      | ## Constraints                                             |
      | ## Source Documents                                        |
      | ## Suggested Research Topics                               |

  # Why: Preferred Directions table columns are the core format change — reviewer reads this row-by-row
  @key-example @smoke
  Scenario: Preferred Decisions table uses the four-column tradeoff-aware format
    Given a preferred decision with a title, a chosen direction, two alternatives, and a tradeoff summary
    When I format the conversation starter
    Then the Preferred Decisions table should have columns "Decision", "Preferred Direction", "Alternatives Considered", and "Tradeoff" in that order
    And the Decision cell should carry the decision identifier as a prefix to its title
    And the Tradeoff cell should contain the tradeoff summary verbatim

  # Why: Source Documents traceability — reviewer must see which docs influenced the output
  @key-example @smoke
  Scenario: Source Documents section renders a Document and Contribution table
    Given three product documents were read during generation
    And each document has a one-sentence contribution summary
    When I format the conversation starter
    Then the Source Documents section should contain a table with columns "Document" and "Contribution"
    And the table should list one row per source document in the order the documents were recorded
    And each row should show the filename alongside its contribution summary

  # Why: Research topics let the agent flag what it cannot resolve from the supplied docs
  @key-example @smoke
  Scenario: Suggested Research Topics section renders as a bullet list
    Given the agent identified four topics needing deeper investigation beyond the supplied docs
    When I format the conversation starter
    Then the Suggested Research Topics section should list each topic as a bullet
    And the topics should appear in the order they were recorded

  # Why: Tradeoff is optional — older generations without a tradeoff must still render cleanly
  @key-example
  Scenario: A decision without a tradeoff renders with an empty Tradeoff cell
    Given a preferred decision where the tradeoff summary was not provided
    When I format the conversation starter
    Then the decision row should still appear in the Preferred Decisions table
    And the Tradeoff cell for that decision should be empty
    And no validation error should be raised

  # Why: New sections are additive — existing structure must not regress
  @key-example
  Scenario: Adding source documents and research topics does not disturb earlier sections
    Given a conversation starter populated with every field
    When I format the conversation starter
    Then the Constraints section should still appear before Source Documents
    And Source Documents should appear before Suggested Research Topics
    And the Preferred Decisions section should appear before Open Questions

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Zero source documents is valid — empty state must use placeholder rather than blank
  @boundary
  Scenario: Formatting with no source documents shows placeholder text
    Given a conversation starter with no source documents recorded
    When I format the conversation starter
    # [ASSUMPTION: confidence=high] Empty Source Documents section uses placeholder prose rather than omitting the section
    Then the Source Documents section should indicate that no source documents have been recorded
    And the output should still contain all 11 required sections

  # Why: Zero research topics is valid — placeholder path for the new section
  @boundary
  Scenario: Formatting with no research topics shows placeholder text
    Given a conversation starter with no suggested research topics
    When I format the conversation starter
    # [ASSUMPTION: confidence=high] Empty Suggested Research Topics section uses placeholder prose rather than omitting the section
    Then the Suggested Research Topics section should indicate that no topics have been identified yet
    And the output should still contain all 11 required sections

  # Why: Exactly one source document — smallest non-empty table, proves table scaffolding is not fixed to N>1
  @boundary
  Scenario: Formatting with exactly one source document renders a single-row table
    Given a conversation starter with exactly one source document
    When I format the conversation starter
    Then the Source Documents table should contain exactly one data row
    And the row should show that document's filename and contribution

  # Why: Exactly one research topic — smallest non-empty bullet list
  @boundary
  Scenario: Formatting with exactly one suggested research topic renders a single bullet
    Given a conversation starter with exactly one suggested research topic
    When I format the conversation starter
    Then the Suggested Research Topics section should contain exactly one bullet
    And no placeholder text should be rendered

  # Why: Zero preferred decisions combined with new sections — the pre-existing empty path must still hold
  @boundary
  Scenario: Formatting with zero preferred decisions still renders all 11 sections
    Given a conversation starter with zero preferred decisions
    And source documents and research topics both populated
    When I format the conversation starter
    Then the Preferred Decisions section should indicate no decisions have been recorded yet
    And the Source Documents section should still render its table
    And the output should contain all 11 required sections

  # Why: Tradeoff cell at its natural minimum — empty string — must not collapse the Markdown table
  @boundary
  Scenario: All decisions have empty tradeoffs — the table still renders four columns
    Given three preferred decisions where every tradeoff summary is empty
    When I format the conversation starter
    Then the Preferred Decisions table should still have four columns
    And every Tradeoff cell should be empty
    And the table should remain valid Markdown

  # ━━ GROUP C: Negative Cases ━━

  # Why: Construction-time validation — ADRs with fewer than 2 alternatives should never reach the formatter
  @negative
  Scenario: Constructing an ADR with fewer than two alternatives is rejected
    When I attempt to construct a preferred decision with only one alternative
    Then the construction should fail with a validation error
    And the error should indicate at least two alternatives are required

  # Why: A SourceDocument must identify the file it describes
  @negative
  Scenario: Constructing a source document without a filename is rejected
    When I attempt to construct a source document with no filename
    Then the construction should fail with a validation error

  # Why: A SourceDocument without a contribution is meaningless traceability
  @negative
  Scenario: Constructing a source document without a contribution is rejected
    When I attempt to construct a source document with no contribution summary
    Then the construction should fail with a validation error

  # Why: C4 minimum contract is unchanged — still enforced alongside the new sections
  @negative
  Scenario: Formatting without a container C4 diagram still fails validation even when new sections are populated
    Given a conversation starter with a context C4 diagram but no container diagram
    And source documents and research topics both populated
    When I attempt to format the conversation starter
    Then the formatter should raise a validation error
    And the error should indicate a container C4 diagram is required

  # ━━ GROUP D: Edge Cases ━━

  # Why: Cells may contain user-authored text that includes pipe characters; must not break Markdown tables
  @edge-case
  Scenario: A tradeoff summary containing a pipe character does not break the table
    Given a preferred decision whose tradeoff summary contains a pipe character
    When I format the conversation starter
    # [ASSUMPTION: confidence=low] Pipe characters inside cells are preserved as-is and the row remains parseable
    Then the Preferred Decisions table should remain valid Markdown
    And the decision row should still be rendered on a single line

  # Why: Long contributions and topics must not be truncated — reviewer needs full context
  @edge-case
  Scenario: Long source document contributions are rendered in full
    Given a source document whose contribution summary exceeds 500 characters
    When I format the conversation starter
    Then the Source Documents table should include the contribution in full without truncation

  # Why: Many items should all render
  @edge-case
  Scenario: Many source documents all appear in the Source Documents table
    Given a conversation starter referencing fourteen source documents
    When I format the conversation starter
    Then the Source Documents table should contain fourteen data rows
    And each row should correspond to a recorded source document

  # Why: A decision with populated tradeoff and another with empty tradeoff should coexist cleanly
  @edge-case
  Scenario: Mixed tradeoff population across decisions
    Given two preferred decisions — one with a tradeoff summary and one without
    When I format the conversation starter
    Then both decision rows should appear in the Preferred Decisions table
    And the first row's Tradeoff cell should contain its summary
    And the second row's Tradeoff cell should be empty

  # Why: The formatter's output IS the input to /system-arch — section headings must stay parseable
  @edge-case
  Scenario: The formatted output is structurally consumable by downstream /system-arch tooling
    Given a fully populated conversation starter
    When the formatted output is parsed as Markdown
    Then the Source Documents heading should be extractable
    And the Suggested Research Topics heading should be extractable
    And no raw template placeholders should appear in the document

  # ━━ GROUP E: Edge Case Expansion ━━

  # Why: Filenames come from on-disk scans — path traversal sequences must not leak structural meaning into the table
  @edge-case @security
  Scenario: A source document filename containing path traversal characters is rendered safely
    Given a source document whose filename is "../../etc/passwd.md"
    When I format the conversation starter
    # [ASSUMPTION: confidence=low] Traversal sequences are rendered literally in the cell with no filesystem side effects
    Then the Source Documents table should contain exactly one row for that document
    And the filename should appear literally in the Document cell
    And no file outside the recorded source documents should be accessed during formatting

  # Why: Research topics are free-text — embedded Markdown headings must not break section structure
  @edge-case @security
  Scenario: A research topic containing embedded Markdown does not alter surrounding section structure
    Given a suggested research topic whose text begins with "## Injected Heading"
    When I format the conversation starter
    Then the Suggested Research Topics section should contain exactly one bullet for that topic
    And no additional top-level or second-level heading should be introduced by the topic text
    And the document should still contain all 11 required sections

  # Why: Two docs can legitimately share a filename (different directories) — both must appear
  @edge-case
  Scenario: Source documents with duplicate filenames each appear as distinct rows
    Given two source documents that share the filename "overview.md"
    And each has a different contribution summary
    When I format the conversation starter
    Then the Source Documents table should contain two data rows for "overview.md"
    And each row should carry its own contribution summary

  # Why: Product docs and decision titles may use CJK or emoji — must render intact, not escaped
  @edge-case
  Scenario: Unicode characters in decisions, contributions, and topics render intact
    Given a preferred decision whose title contains CJK characters
    And a source document whose contribution contains an emoji
    And a research topic containing a non-Latin script
    When I format the conversation starter
    Then the decision title should appear intact in the Preferred Decisions table
    And the emoji should appear intact in the Source Documents table
    And the research topic should appear intact in the Suggested Research Topics section

  # Why: Backward compatibility with Phase 0 output — existing ConversationStarters must still format under the new contract
  @edge-case @regression
  Scenario: A Phase 0-style conversation starter with no tradeoffs, source documents, or research topics still formats cleanly
    Given a conversation starter where every decision has an empty tradeoff
    And no source documents are recorded
    And no research topics are recorded
    When I format the conversation starter
    Then formatting should succeed without error
    And the Preferred Decisions table should render with empty Tradeoff cells
    And the Source Documents section should show its placeholder text
    And the Suggested Research Topics section should show its placeholder text
    And the output should contain all 11 required sections
