# Generated by /feature-spec
# Feature: Jarvis Notification Bridge (Pipeline -> Slack)
# Stack: python
# Assumptions: 11 (see jarvis-notification-bridge_assumptions.yaml)
# Generated: 2026-07-03T10:52:30Z
# Revised: 2026-07-03 (Slack pivot; v1 full-lifecycle scope; +2 scenarios)

@jarvis-notification-bridge
Feature: Jarvis Notification Bridge
  As the operator of the overnight build service
  I want the build lifecycle -- queued, running, terminal outcomes and
  approval pauses -- pushed to my phone,
  and I want to approve or reject a paused build by replying,
  So that I can queue features before bed and steer only the builds that
  need a human, without watching a terminal all night.

  # [ASSUMPTION: confidence=high] Notifications are delivered to a single configured operator Slack channel via a Slack bot; v1.1 replies are Socket Mode button clicks authorized against the operator's member id (ASSUM-007).
  Background:
    Given the notification bridge is running and connected to the build service
    And my phone is configured to receive build notifications

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: The first signal of the checkpoint sequence -- queueing from the
  # assistant must be acknowledged on the phone.
  # [ASSUMPTION: confidence=high] The queued notification fires at jarvis intake publish time; CLI-queued builds produce no queued notification (ASSUM-011).
  @key-example @smoke
  Scenario: Queueing a build from the assistant notifies my phone that it is queued
    Given I ask the assistant to queue a build for feature "FEAT-4A2C"
    When my build request is published to the build queue
    Then I should receive a notification on my phone
    And the notification should identify the feature and tell me it is queued

  # Why: The queued -> running transition -- the phone confirms the night
  # shift actually picked the build up.
  @key-example @smoke
  Scenario: A build that starts running notifies my phone
    Given a queued build for feature "FEAT-4A2C" is waiting to start
    When the build service starts running the build
    Then I should receive a notification on my phone
    And the notification should identify the feature and the build
    And the notification should tell me the build is running

  # Why: Core terminal-success path -- the "PR is ready" morning signal.
  # [ASSUMPTION: confidence=high] v1 notifies the full lifecycle: build-queued (jarvis-intake), build-started, build-complete, build-failed, build-cancelled, build-paused (ASSUM-001).
  @key-example @smoke
  Scenario: A build that completes successfully notifies my phone
    Given a queued build for feature "FEAT-4A2C" is running
    When the build completes successfully
    Then I should receive a notification on my phone
    And the notification should identify the feature and the build
    And the notification should tell me the build completed and link to its result

  # Why: Core terminal-failure path -- a failure must always reach the phone.
  @key-example @smoke
  Scenario: A build that fails notifies my phone with the reason
    Given a queued build for feature "FEAT-4A2C" is running
    When the build fails
    Then I should receive a notification on my phone
    And the notification should tell me the build failed
    And the notification should include the reason the build failed

  # Why: Core pause path -- the escalation that asks for a human decision.
  # [ASSUMPTION: confidence=high] A recorded coach score renders when present; on today's live path the score is always absent (ASSUM-003), so the no-score sibling in Group B is the live-checkpoint smoke variant.
  @key-example
  Scenario: A build that pauses for approval notifies my phone with the coach rationale
    Given a queued build for feature "FEAT-4A2C" is running
    When the build pauses for approval at a stage with a coach score recorded
    Then I should receive a notification on my phone
    And the notification should name the stage the build paused at
    And the notification should include the coach score and the rationale for the pause
    And the notification should tell me I can approve or reject the build

  # Why: A cancelled build is a terminal state the operator must be told about.
  # [ASSUMPTION: confidence=medium] Forge today has no verified end-to-end producer of build-cancelled; this scenario specifies bridge behaviour when the envelope arrives (ASSUM-010).
  @key-example
  Scenario: A build that is cancelled notifies my phone
    Given a queued build for feature "FEAT-4A2C" is running
    When the build is cancelled
    Then I should receive a notification on my phone
    And the notification should tell me the build was cancelled and by whom

  # Why: v1.1 core -- an approve reply resumes the paused build.
  @key-example
  Scenario: Approving a paused build from my phone resumes it
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    When I reply to approve the build
    Then the build should resume
    And I should not be asked to approve the same pause again

  # Why: v1.1 core -- a reject reply must not resume the build; forge records
  # the rejection as a cancellation (ASSUM-004).
  @key-example
  Scenario: Rejecting a paused build from my phone does not resume it
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    When I reply to reject the build
    Then the build should not resume
    And the outcome of my decision should be recorded against the build

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Just-inside -- the coach score at each end of its range still renders.
  # [ASSUMPTION: confidence=high] Coach score is 0.0-1.0 per forge's enforced contract; the wire schema is unconstrained and the value is always None on today's live path, so rendering is defensive (ASSUM-003).
  @boundary
  Scenario Outline: A pause notification renders the coach score at the range boundaries
    Given a build that pauses for approval with a coach score of <score>
    When the pause notification is sent to my phone
    Then the notification should show the coach score as <score>

    Examples:
      | score |
      | 0.0   |
      | 1.0   |

  # Why: The live coach-score gap -- a pause with NO score must still notify.
  # This is today's live default (ASSUM-003), hence the checkpoint @smoke tag.
  @boundary @smoke
  Scenario: A pause with no coach score still notifies with the rationale
    Given a build that pauses for approval with no coach score recorded
    When the pause notification is sent to my phone
    Then I should still receive the pause notification
    And the notification should include the rationale
    And the notification should indicate the coach score is unavailable

  # Why: Just-inside the approval window -- a reply within the window resumes.
  # [ASSUMPTION: confidence=high] The approval window waits 300s per attempt up to a 3600s total ceiling; breaching the ceiling cancels the build (ASSUM-005).
  @boundary
  Scenario: An approval reply that arrives within the wait window resumes the build
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    And the approval wait window has not yet elapsed
    When I reply to approve the build
    Then the build should resume

  # Why: Just-outside the approval window -- a reply after the window is too late.
  @boundary @negative
  Scenario: An approval reply that arrives after the wait window is not applied
    Given the build for feature "FEAT-4A2C" has waited past its approval window
    When I reply to approve the build
    Then the build should not be resumed by the late reply

  # Why: The rationale is verbatim operator-facing text -- a long rationale must survive.
  @boundary
  Scenario: A pause with a long rationale delivers the rationale intact
    Given a build that pauses with a multi-paragraph coach rationale
    When the pause notification is sent to my phone
    Then the notification should preserve the full rationale text

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: DDR-007 -- a delivery failure must never regress the build.
  # [ASSUMPTION: confidence=high] On notification failure the bridge logs a WARNING and continues; the build never regresses (ASSUM-008).
  @negative @smoke
  Scenario: A notification delivery failure is logged and the build is unaffected
    Given a build for feature "FEAT-4A2C" completes successfully
    When the notification cannot be delivered to my phone
    Then the delivery failure should be logged as a warning
    And the build should remain recorded as complete
    And the build should not be retried or rolled back because of the failure

  # Why: Intra-build chatter is noise on a phone in v1.
  # [ASSUMPTION: confidence=high] v1 suppresses build-progress, stage-complete and build-resumed from the phone; build-started is notified per ASSUM-001 (ASSUM-002).
  @negative
  Scenario Outline: Routine progress events are not sent to my phone
    Given a build for feature "FEAT-4A2C" is running
    When the build emits a <event> update
    Then I should not receive a notification on my phone

    Examples:
      | event          |
      | build progress |
      | stage complete |
      | build resumed  |

  # Why: Events from an unrecognised source must not reach the operator.
  @negative
  Scenario: A notification from an unrecognised source is dropped
    Given a lifecycle update arrives that did not originate from the build service
    When the bridge processes the update
    Then no notification should be sent to my phone
    And the dropped update should be logged

  # Why: A malformed update must not crash the bridge or reach the phone.
  @negative
  Scenario: A malformed lifecycle update is dropped without notifying
    Given a malformed lifecycle update arrives at the bridge
    When the bridge processes the update
    Then no notification should be sent to my phone
    And the bridge should continue handling subsequent updates

  # Why: Only the schema's allowed decisions may act on a pause.
  # [ASSUMPTION: confidence=high] Allowed approval decisions are approve, reject, defer and override (ASSUM-004).
  @negative
  Scenario: An approval reply with an unrecognised decision is refused
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    When I reply with a decision the build service does not recognise
    Then the build should remain paused
    And the refusal should be logged

  # Why: Security -- a reply from an unauthorised person must not resume a build.
  @negative
  Scenario: An approval reply from an unauthorised person is refused
    Given the build for feature "FEAT-4A2C" is paused awaiting approval from the configured operator
    When someone other than the configured operator replies to approve the build
    Then the build should remain paused

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: At-least-once delivery must not double-notify the operator.
  # [ASSUMPTION: confidence=high] A first-response-wins dedup window of 300s suppresses duplicate deliveries (ASSUM-006).
  @edge-case
  Scenario: A duplicated terminal event notifies my phone only once
    Given a build for feature "FEAT-4A2C" completes successfully
    When the completion event is delivered to the bridge twice
    Then I should receive exactly one completion notification

  # Why: First-reply-wins -- a duplicated approval must resume only once.
  @edge-case
  Scenario: A duplicated approval reply resumes the build only once
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    When my approval reply is delivered to the bridge twice
    Then the build should resume exactly once

  # Why: A reply for an already-finished build must be ignored.
  @edge-case
  Scenario: An approval reply for a build that already ended is ignored
    Given the build for feature "FEAT-4A2C" has already reached a terminal state
    When I reply to approve that build
    Then the reply should be ignored
    And the build should not change state

  # Why: Concurrency -- approving one paused build must not resume another.
  @edge-case
  Scenario: Approving one paused build does not resume a different paused build
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    And the build for feature "FEAT-9E71" is also paused awaiting my approval
    When I reply to approve the build for feature "FEAT-4A2C"
    Then only the build for feature "FEAT-4A2C" should resume
    And the build for feature "FEAT-9E71" should remain paused

  # Why: The build ledger is authoritative; a lost notification is not a lost build.
  @edge-case
  Scenario: A build outcome is preserved even when its notification is never delivered
    Given the phone notification channel is unavailable
    When a build for feature "FEAT-4A2C" reaches a terminal state
    Then the build outcome should still be recorded by the build service
    And the missed notification should be logged as a warning

  # Why: No-replay-on-restart -- events missed while the bridge is down are not resurfaced.
  # [ASSUMPTION: confidence=high] Events emitted while the bridge is down are not replayed on restart -- structurally guaranteed by workqueue retention + the ephemeral consumer (ASSUM-009).
  @edge-case
  Scenario: Events emitted while the bridge was down are not replayed on restart
    Given a build reached a terminal state while the bridge was not running
    When the bridge starts up again
    Then I should not receive a delayed notification for that past event

  # ==========================================================================
  # GROUP E: Edge Case Expansion (security, concurrency, integration)
  # ==========================================================================

  # Why: Cross-build spoof guard -- knowing a build id must not be enough to steer it.
  @edge-case @security
  Scenario: An approval reply carrying the wrong correlation is refused
    Given the build for feature "FEAT-4A2C" is paused awaiting my approval
    When an approval reply arrives that names this build but carries a correlation from a different build
    Then the build should remain paused
    And the mismatched reply should be logged as an anomaly

  # Why: The rationale and failure reason are attacker-influenced text rendered on a phone.
  @edge-case @security
  Scenario: Formatting characters in a rationale are delivered as inert text
    Given a build that pauses with a rationale containing message-formatting characters
    When the pause notification is sent to my phone
    Then the rationale should be shown as plain text
    And the formatting characters should not change how the notification is displayed

  # Why: A race between a valid reply and window expiry must resolve to one outcome.
  @edge-case
  Scenario: An approval that races the window expiry resolves to a single outcome
    Given the build for feature "FEAT-4A2C" is paused and its approval window is about to expire
    When my approval reply and the window expiry occur at effectively the same moment
    Then the build should end in exactly one state, either resumed or timed out
    And the build should not undergo two conflicting transitions

  # Why: Concurrent terminal events must not leak fields between builds.
  @edge-case
  Scenario: Two concurrent terminal events each notify their own build correctly
    Given a build for feature "FEAT-4A2C" and a build for feature "FEAT-9E71" finish at the same time
    When both terminal events are delivered to the bridge together
    Then I should receive one notification for each build
    And each notification should carry only its own build's feature, build id, and outcome

  # Why: A burst of notifications must not wedge the bridge or affect builds.
  @edge-case
  Scenario: The bridge tolerates the phone channel throttling a burst of notifications
    Given several builds reach terminal states in quick succession
    When the phone channel throttles the bridge
    Then the bridge should back off and keep attempting delivery
    And no build's recorded outcome should be affected by the throttling

  # Why: The bridge must start safely when the build service is not yet reachable.
  @edge-case
  Scenario: The bridge starts in a degraded state when the build service is unreachable
    Given the build service connection is unavailable when the bridge starts
    When the bridge starts up
    Then the bridge should start without crashing
    And it should send no notifications until the connection is established
