# Generated by /feature-spec
# Feature: Local LLM provider configuration for the architect fine-tune (FEAT-RAG-01)
# Stack: python
# Assumptions: 4 (see feat-rag-01-local-provider-config_assumptions.yaml)
# Generated: 2026-05-03T12:00:00Z

@feat-rag-01 @local-provider-config
Feature: Local LLM provider configuration for the architect fine-tune

  As an operator running the architect role against a local fine-tune
  I want the local provider to default to the llama-swap endpoint and
  let me select the served model by name
  So that I can route the architect role at the GB10-hosted Gemma 4 MoE
  fine-tune without code changes and without losing the cloud-provider
  abstraction.

  Background:
    Given the architect uses the local LLM provider
    And no LLM_BASE_URL or LOCAL_MODEL environment variables are set unless a scenario states otherwise

  # ──────────────────────────────────────────────────────────────────────
  # GROUP A: Key Examples
  # ──────────────────────────────────────────────────────────────────────

  # Why: Core path — out-of-the-box defaults match the canonical llama-swap
  #       topology documented in the architect-dataset RUNBOOK (port 9000).
  @task:TASK-RAG01-001
  @key-example @smoke
  Scenario: Local provider defaults to the llama-swap endpoint and the "default" model
    When I create a local provider client with no configuration
    Then the client should target the llama-swap default endpoint
    And the client should request the model named "default"

  # Why: This is the load-bearing operator action FEAT-RAG-01 unlocks —
  #       selecting the architect fine-tune by stable id without touching
  #       code.
  # [ASSUMPTION: confidence=medium] The architect fine-tune is registered
  #       with llama-swap under the stable id "architect-agent" (confirmed
  #       live on GB10:9000/v1/models, 2026-05-03).
  @task:TASK-RAG01-001
  @key-example @smoke
  Scenario: Operator selects the architect fine-tune via LOCAL_MODEL
    Given LOCAL_MODEL is set to "architect-agent"
    When I create a local provider client
    And the client generates a response to a prompt
    Then the local server should be asked for the "architect-agent" model

  # Why: Endpoint override remains essential — different operators reach
  #       llama-swap by hostname, Tailscale name, or localhost.
  @task:TASK-RAG01-001
  @key-example
  Scenario: Operator overrides the endpoint via LLM_BASE_URL
    Given LLM_BASE_URL is set to "http://promaxgb10-41b1:9000"
    When I create a local provider client
    Then the client should target "http://promaxgb10-41b1:9000"

  # ──────────────────────────────────────────────────────────────────────
  # GROUP B: Boundary Conditions
  # ──────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — when LOCAL_MODEL is omitted, the historical
  #       "default" tag must still be sent for backward compatibility.
  @task:TASK-RAG01-001
  @boundary
  Scenario: LOCAL_MODEL not set falls back to the default model tag
    Given LOCAL_MODEL is unset
    When I create a local provider client
    Then the client should request the model named "default"

  # Why: Empty-string env vars are a common operator footgun. Define
  #       deterministic behaviour rather than letting "" reach the server.
  # [ASSUMPTION: confidence=medium] An empty LOCAL_MODEL value is treated
  #       as unset; the client falls back to "default".
  @task:TASK-RAG01-001
  @boundary
  Scenario: LOCAL_MODEL set to an empty string is treated as unset
    Given LOCAL_MODEL is set to ""
    When I create a local provider client
    Then the client should request the model named "default"

  # Why: Constructor-argument precedence over env vars matches the existing
  #       pattern for base_url and is required for existing tests that
  #       construct LocalLLMClient(model=...) directly.
  # [ASSUMPTION: confidence=medium] An explicit model= constructor argument
  #       overrides LOCAL_MODEL.
  @task:TASK-RAG01-001
  @boundary
  Scenario: An explicit model passed to the constructor overrides LOCAL_MODEL
    Given LOCAL_MODEL is set to "architect-agent"
    When I create a local provider client with the model "test-model"
    Then the client should request the model named "test-model"

  # Why: Existing precedence for LLM_BASE_URL must be preserved (regression
  #       guard against accidentally swapping the order in the new code path).
  @task:TASK-RAG01-001
  @boundary @regression
  Scenario: An explicit base URL passed to the constructor overrides LLM_BASE_URL
    Given LLM_BASE_URL is set to "http://override:9000"
    When I create a local provider client with the base URL "http://gpu-server:9000"
    Then the client should target "http://gpu-server:9000"

  # ──────────────────────────────────────────────────────────────────────
  # GROUP C: Negative Cases
  # ──────────────────────────────────────────────────────────────────────

  # Why: When llama-swap is not running, the operator must get a clear,
  #       actionable error — not a stack trace or a generic timeout.
  @task:TASK-RAG01-001
  @negative
  Scenario: Local server unreachable produces a clear configuration error
    Given the local server endpoint is not running
    When the local provider tries to generate a response
    Then the operator should see an error indicating the local server cannot be reached
    And the error should mention the configured endpoint

  # Why: Operator selects a model the server has not loaded — the upstream
  #       error must surface, not be swallowed.
  @task:TASK-RAG01-001
  @negative
  Scenario: Operator selects a model the local server has not loaded
    Given LOCAL_MODEL is set to "an-unloaded-model"
    And the local server is reachable
    And the local server rejects requests for "an-unloaded-model"
    When the local provider tries to generate a response
    Then the operator should see an error explaining the local server rejected the request

  # ──────────────────────────────────────────────────────────────────────
  # GROUP D: Edge Cases
  # ──────────────────────────────────────────────────────────────────────

  # Why: Provider-abstraction invariant — the FEAT-RAG-01 changes must not
  #       regress the claude/gemini/openai paths.
  @task:TASK-RAG01-001
  @edge-case @regression
  Scenario Outline: Other LLM providers continue to work unchanged
    When I create a "<provider>" provider client
    Then the client should report itself as the "<provider>" provider
    And the client should expose its configured model identity

    Examples:
      | provider |
      | claude   |
      | gemini   |
      | openai   |

  # Why: Existing tests construct LocalLLMClient(model=, base_url=, timeout=)
  #       directly. The new env-var paths must not break that signature.
  @task:TASK-RAG01-001
  @edge-case @regression
  Scenario: Programmatic construction with explicit model and base URL still works
    When I create a local provider client with model "llama-3.1-8b" and base URL "http://gpu-server:9000"
    Then the client should report its model as "llama-3.1-8b"
    And the client should report its base URL as "http://gpu-server:9000"

  # Why: Reasoning-model switch is configured by AGENT_MODELS__REASONING_MODEL
  #       per build plan RAG-01-02; the local provider needs to be selectable
  #       as the active reasoning provider through that key.
  @task:TASK-RAG01-001
  @edge-case
  Scenario: Selecting the local provider as the reasoning model
    Given AGENT_MODELS__REASONING_MODEL is set to "local"
    And LOCAL_MODEL is set to "architect-agent"
    When the architect role resolves its reasoning provider
    Then the local provider should be the active reasoning provider
    And it should be configured to request the "architect-agent" model

  # ──────────────────────────────────────────────────────────────────────
  # GROUP E: Configuration / Secret Handling
  # ──────────────────────────────────────────────────────────────────────

  # Why: vLLM/llama-swap convention — no API key required. Verify that
  #       ambient OPENAI_API_KEY is not used by the local provider, so
  #       cloud OpenAI credentials cannot leak to a local endpoint that
  #       may be on Tailscale or a shared LAN.
  @task:TASK-RAG01-001
  @edge-case @security
  Scenario: Local provider does not forward the OpenAI API key from the environment
    Given OPENAI_API_KEY is set to "sk-do-not-leak"
    When I create a local provider client
    And the client generates a response to a prompt
    Then the local server should not receive "sk-do-not-leak" as an API key

  # Why: If the operator points LLM_BASE_URL at an HTTPS endpoint with a
  #       broken cert, the failure must be visible — not silently downgraded
  #       to plaintext or hidden behind a generic timeout.
  # [ASSUMPTION: confidence=low] HTTPS with an invalid certificate is
  #       expected to surface a clear connection error to the operator;
  #       the client must not silently retry over plaintext.
  @task:TASK-RAG01-001
  @edge-case @security @negative
  Scenario: HTTPS endpoint with an invalid certificate fails with a clear error
    Given LLM_BASE_URL is set to an HTTPS endpoint with an invalid certificate
    When the local provider tries to generate a response
    Then the operator should see an error indicating the connection could not be established
    And the error should not silently retry over plaintext

  # ──────────────────────────────────────────────────────────────────────
  # GROUP F: Concurrency / State
  # ──────────────────────────────────────────────────────────────────────

  # Why: Two local clients constructed with different model selections must
  #       not share state — required by the two-model split scenario
  #       (Player=local, Coach=claude) and by general provider-abstraction
  #       hygiene.
  @task:TASK-RAG01-001
  @edge-case
  Scenario: Two local-provider clients with different model selections stay isolated
    When I create a local provider client with the model "model-a"
    And I create a second local provider client with the model "model-b"
    Then the first client should request the model named "model-a"
    And the second client should request the model named "model-b"
    And token usage on one client should not affect the other

  # ──────────────────────────────────────────────────────────────────────
  # GROUP G: Integration Boundary
  # ──────────────────────────────────────────────────────────────────────

  # Why: PLAN-PHASE-RAG.md §Risk Mitigation explicitly endorses a two-model
  #       split (Player=local, Coach=claude) as a fallback if the fine-tune
  #       is competitive on reasoning but weaker on structured JSON output.
  #       FEAT-RAG-01 must not block this configuration.
  @task:TASK-RAG01-001
  @edge-case @regression
  Scenario: Two-model split — Player on local, Coach on Claude — configures independently
    Given LOCAL_MODEL is set to "architect-agent"
    And ANTHROPIC_API_KEY is set
    When the Player is created with the "local" provider
    And the Coach is created with the "claude" provider
    Then the Player client should request the "architect-agent" model
    And the Coach client should report itself as the "claude" provider
    And neither client should share configuration with the other
