# Generated by /feature-spec
# Feature: Architect RAG Deployment & Serving Runbook
# Stack: python
# Assumptions: 11 (see architect-rag-deployment-runbook_assumptions.yaml)
# Generated: 2026-05-04T00:00:00Z

@architect-rag-deployment-runbook
Feature: Architect RAG Deployment & Serving Runbook
  As an operator wiring up the architect role for Phase RAG
  I want a single end-to-end runbook plus a topology ADR
  So that I can stand up llama-swap + ChromaDB + Ollama embeddings on the GB10
  and run a working architect_align session against the fine-tune + RAG
  without piecing the answer together from scope and build-plan documents

  Background:
    # [ASSUMPTION: confidence=low] ChromaDB runs in persistent-client mode (no separate server, no port) — opened in-process by the ingestion script and the architecture_knowledge_query tool against the same persistence directory on the GB10 host
    Given the Phase RAG topology where the GB10 host serves
      | service                          | endpoint                                      |
      | llama-swap (OpenAI-compatible)   | http://promaxgb10-41b1:9000                   |
      | ChromaDB (persistent-client)     | host-local persistence directory on GB10      |
      | Ollama embeddings (nomic-embed)  | http://promaxgb10-41b1:11434/api/embeddings   |
    And the agent host (Mac) reaches the GB10 over Tailscale
    And FEAT-RAG-01 (local provider config) and FEAT-RAG-02 (ChromaDB ingestion) have already landed

  # ------------------------------------------------------------------
  # GROUP A: Key Examples
  # ------------------------------------------------------------------

  # Why: This is the load-bearing acceptance criterion from FEAT-RAG-06
  @task:TASK-RAG06-007
  @key-example @smoke
  Scenario: A new operator follows the runbook end-to-end and reaches a working architect_align session
    Given an operator with no prior knowledge of the Phase RAG topology
    And the operator has shell access to both the agent host and the GB10 host
    When the operator works through the runbook section by section in order
    Then the operator should reach a passing smoke-test architect_align session
    And the operator should not have needed to consult the phase-rag scope or build-plan documents
    And the operator should not have needed to read source code outside the commands the runbook quotes

  # Why: Topology is the orienting section — every later step refers back to it
  @task:TASK-RAG06-001
  @key-example
  Scenario: The runbook opens with a topology section that names every service, host, and port
    When the operator reads the topology section of the runbook
    Then the section should identify llama-swap on the GB10 host with its port
    And the section should identify ChromaDB on the GB10 host with its persistence path
    And the section should identify Ollama embeddings on the GB10 host with its port and the embedding model name
    And the section should explain that the architect process runs on the agent host and reaches the GB10 over Tailscale

  # Why: Without a stable model id, the local provider cannot select the fine-tune
  # [ASSUMPTION: confidence=medium] The fine-tune is registered under the stable model id "architect-agent" — runbook examples use this value, and operators with a different llama-swap registration substitute their own
  @task:TASK-RAG06-003
  @key-example @smoke
  Scenario: The runbook's llama-swap section verifies the fine-tune is registered under a stable model id
    When the operator follows the llama-swap configuration steps
    Then the operator should be able to confirm the fine-tune is registered by listing the available models from the GB10 endpoint
    And the listing should include the architect fine-tune under its stable model id
    And the runbook should state that this stable id is the value the operator sets for LOCAL_MODEL on the agent host

  # Why: ChromaDB section must hand off cleanly to FEAT-RAG-02 without duplicating it
  # [ASSUMPTION: confidence=medium] Backup is a tar.gz of the configured Chroma persistence directory; restore is the inverse
  @task:TASK-RAG06-004
  @key-example
  Scenario: The runbook's ChromaDB section covers persistence path, ingestion, and backup-restore
    When the operator reads the ChromaDB section of the runbook
    Then the section should identify the persistent collection path on the GB10 host
    And the section should quote the ingestion command from FEAT-RAG-02 verbatim rather than re-deriving it
    And the section should describe how to back up the collection
    And the section should describe how to restore the collection from a backup

  # Why: The smoke test is the only acceptance test the operator can run themselves
  # [ASSUMPTION: confidence=low] Smoke-test prompt re-uses one of the FEAT-RAG-07-02 align targets so that a captured GPT-5.5 baseline is available for comparison
  # [ASSUMPTION: confidence=low] A passing smoke test produces a <think> block, at least one [book: topic] citation drawn from the architecture knowledge index, a Coach acceptance verdict, and a session-log entry showing architecture_knowledge_query was invoked
  @task:TASK-RAG06-005
  @key-example @smoke
  Scenario: The runbook's smoke test gives a runnable architect_align call with expected and observed behaviour
    When the operator reaches the smoke-test section of the runbook
    Then the section should provide a single architect_align command the operator can run as-is
    And the section should describe the expected behaviour of a healthy run including a citation drawn from the architecture knowledge index
    And the section should describe what the operator should observe to declare the smoke test passing
    And the section should describe at least one observable signal that distinguishes a passing run from a silently degraded run

  # ------------------------------------------------------------------
  # GROUP B: Boundary Conditions
  # ------------------------------------------------------------------

  # Why: Just-inside boundary — every env var the runbook references must exist in .env.example
  @task:TASK-RAG06-001
  @boundary
  Scenario: Every environment variable the runbook references is documented in .env.example
    When the operator copies .env.example to .env and fills in the values the runbook calls out
    Then there should be no environment variable the runbook mentions that does not appear in .env.example
    And there should be no environment variable in .env.example whose role the runbook fails to explain

  # Why: Just-inside boundary — every port and host appears in the topology table
  @task:TASK-RAG06-007
  @boundary
  Scenario: Every host and port mentioned in any runbook section also appears in the topology table
    When the operator scans every concrete host and port reference in the runbook
    Then each one should also appear in the topology section's services list
    And the topology table should not contain any entry that is unused in the rest of the runbook

  # Why: Just-outside boundary — runbook must not assume work the operator hasn't done
  @task:TASK-RAG06-001
  @boundary @negative
  Scenario: A reader who has not yet completed FEAT-RAG-01 or FEAT-RAG-02 is sent back to those features rather than walked through them again
    Given an operator whose agent host is still on default-vLLM provider settings
    When the operator opens the runbook
    Then the runbook should state its prerequisites including FEAT-RAG-01 (local provider config) and FEAT-RAG-02 (ingestion)
    And the runbook should link to the prerequisite features rather than reproducing their commands

  # Why: Companion ADR must record the three explicit decisions named in the description
  # [ASSUMPTION: confidence=high] The companion ADR is filed as ADR-ARCH-014 (next free number after ADR-ARCH-013)
  # [ASSUMPTION: confidence=medium] The companion ADR is a new ADR rather than an extension to ADR-ARCH-013; it cross-references ADR-ARCH-013 for embedding-model and refresh-cadence specifics rather than restating them
  @task:TASK-RAG06-002
  @boundary
  Scenario: The companion ADR records the three required decisions
    When the reviewer opens the companion ADR
    Then the ADR should record the inference-topology decision comparing GB10 against local-host and cloud alternatives
    And the ADR should record the embedding model choice with its rationale
    And the ADR should record the refresh cadence for the architecture knowledge collection

  # ------------------------------------------------------------------
  # GROUP C: Negative Cases
  # ------------------------------------------------------------------

  # Why: Most likely failure mode at first run — the model id doesn't appear in /v1/models
  @task:TASK-RAG06-003
  @negative
  Scenario: The runbook tells the operator what to do when the fine-tune is not listed by llama-swap
    Given the operator has run the verification step against the GB10 endpoint
    When the listing returns a set of models that does not include the architect fine-tune
    Then the runbook should give the operator a clear next action
    And the next action should distinguish "fine-tune not yet copied to the host" from "llama-swap config not yet pointing at the fine-tune"

  # Why: Tailscale brings its own failure mode — host reachability before service reachability
  @task:TASK-RAG06-006
  @negative
  Scenario: The runbook tells the operator how to recognise and recover from a Tailscale outage
    Given the operator has run a verification step from the agent host against the GB10 endpoint
    When the request fails to reach the GB10 host at all
    Then the runbook should tell the operator how to confirm Tailscale is up between the two hosts before suspecting the services
    And the runbook should not ask the operator to debug llama-swap or Chroma until host reachability is established

  # Why: Smoke test passing visually but degraded silently is the worst failure mode
  # [ASSUMPTION: confidence=low] A response without a [book: topic] citation indicates the architecture_knowledge_query tool fell into its graceful-degradation path rather than the model failing
  @task:TASK-RAG06-005
  @negative
  Scenario: The runbook tells the operator how to recognise a degraded smoke-test pass
    Given the operator has run the smoke-test architect_align command and received a response
    When the response contains an architect-shaped output but no citation drawn from the architecture knowledge index
    Then the runbook should explain that this is a known degraded mode rather than a pass
    And the runbook should point the operator at the architecture_knowledge_query graceful-degradation path as the most likely cause

  # Why: Operator must not bypass the orchestrator-gated write contract by editing files in place
  @task:TASK-RAG06-007
  @negative
  Scenario: The runbook does not document any procedure that bypasses orchestrator-gated writes
    When the reviewer scans the runbook for any step that writes to the conversation-starter output
    Then no step should instruct the operator to write to the output directly
    And every documented write path should go through the architect_align orchestrator

  # Why: Public exposure of llama-swap or ChromaDB is a real security failure mode
  @task:TASK-RAG06-006
  @negative @security
  Scenario: The runbook does not encourage exposing GB10 services to the public internet
    When the reviewer scans the runbook for network-binding instructions
    Then no step should instruct the operator to bind llama-swap, ChromaDB, or Ollama to a public-internet-reachable address
    And the runbook should state that the agent host reaches the GB10 over Tailscale by default

  # ------------------------------------------------------------------
  # GROUP D: Edge Cases
  # ------------------------------------------------------------------

  # Why: Backup/restore must be exercise-able as documented or it is decorative
  # [ASSUMPTION: confidence=medium] Restore requires stopping any process holding the persistence directory open before extracting the archive — Chroma persistent client locks the directory
  @task:TASK-RAG06-004
  @edge-case
  Scenario: Backup and restore round-trips the ChromaDB collection without data loss
    Given a populated architect-knowledge collection on the GB10 host
    When the operator runs the backup procedure exactly as the runbook documents it
    And the operator simulates loss by removing the persistence directory
    And the operator runs the restore procedure exactly as the runbook documents it
    Then the restored collection should expose the same record count it had before
    And the restored collection should answer the runbook's smoke-test query with the same retrieval result

  # Why: Distinguishing this runbook's role from existing ADRs is reader-orienting
  @task:TASK-RAG06-007
  @edge-case
  Scenario: The runbook is the operational counterpart of ADR-ARCH-013, not a duplicate of it
    When the reviewer reads the runbook with ADR-ARCH-013 open alongside it
    Then the runbook should reference ADR-ARCH-013 for the embedding model and collection-naming decisions
    And the runbook should not re-derive those decisions in its own prose
    And the companion ADR for this feature should cross-reference ADR-ARCH-013 explicitly

  # Why: A reader following the runbook for the first time needs the order to be fixed
  @task:TASK-RAG06-007
  @edge-case
  Scenario: The runbook's section order is end-to-end executable rather than reference-only
    When a first-time operator works through the runbook from top to bottom in order
    Then no section should depend on a step from a later section
    And no section should expect knowledge the operator has not yet been told

  # Why: Refresh cadence is the bridge between dataset regeneration and runbook re-execution
  @task:TASK-RAG06-004
  @edge-case
  Scenario: The runbook tells the operator what to do when the dataset is regenerated
    Given the source knowledge dataset has been regenerated by the dataset factory
    When the operator wants the architect knowledge collection to reflect the new dataset
    Then the runbook should direct the operator to bump the collection name (architect-knowledge-v{N+1})
    And the runbook should direct the operator to re-run the FEAT-RAG-02 ingestion script against the new collection name
    And the runbook should direct the operator to update the role configuration to point at the new collection
    And the companion ADR should record this refresh cadence as one-shot per dataset version

  # ------------------------------------------------------------------
  # EDGE CASE EXPANSION: Security
  # ------------------------------------------------------------------

  # Why: Embedding a secret in a copy-pasteable command is the most common way
  # secrets leak into screenshots, support tickets, and chat logs
  @task:TASK-RAG06-005
  @edge-case @security
  Scenario: Runbook command examples use environment-variable placeholders rather than literal secrets
    When the reviewer scans every shell command the runbook tells the operator to run
    Then no command should contain a literal API key, bearer token, or password value
    And every place a secret would appear should reference an environment variable that is documented in .env.example
    And the runbook should instruct the operator to populate .env before running any of the documented commands

  # Why: Backups exfiltrate secrets if they include .env or shell-history files alongside
  # the persistence directory; this is a real failure mode in support hand-offs
  @task:TASK-RAG06-004
  @edge-case @security
  Scenario: The documented backup procedure captures only the ChromaDB persistence directory
    When the operator runs the backup procedure exactly as the runbook documents it
    Then the resulting backup archive should contain only files under the configured Chroma persistence directory
    And the resulting backup archive should not contain .env files
    And the resulting backup archive should not contain shell history, llama-swap configuration, or any file outside the persistence directory
    And the runbook should state explicitly that the backup is safe to share with someone outside the operator's trust boundary if the persistence directory itself is

  # ------------------------------------------------------------------
  # EDGE CASE EXPANSION: Concurrency
  # ------------------------------------------------------------------

  # Why: Re-ingestion concurrent with live retrieval has produced inconsistent
  # results in similar systems; the runbook is the only place this is surfaced
  # [ASSUMPTION: confidence=low] Drain procedure is informal — operator coordination only, since specialist-agent has no formal session lifecycle to drain against
  @task:TASK-RAG06-004
  @edge-case @concurrency
  Scenario: The runbook documents the operational order for re-ingestion against a live collection
    Given an architect_align session may be using the architect-knowledge collection at any time
    When the operator needs to re-ingest into the same collection name
    Then the runbook should instruct the operator to drain or pause active architect sessions before starting ingestion
    And the runbook should instruct the operator to wait for ingestion to complete before resuming sessions
    And the runbook should explain that ingestion and live retrieval against the same collection at the same time may produce inconsistent retrieval results

  # ------------------------------------------------------------------
  # EDGE CASE EXPANSION: Integration boundaries
  # ------------------------------------------------------------------

  # Why: Player tool degrades gracefully on Chroma failure, masking the real cause —
  # operator needs a way to tell "RAG missing because graceful-degradation" from "fine-tune broken"
  # [ASSUMPTION: confidence=low] Health-check coverage is lightweight — a curl against /v1/models for llama-swap, a curl against the Ollama embeddings endpoint, and a Python REPL one-liner that opens the Chroma persistent client. No systemd unit names, log file paths, or restart commands.
  @task:TASK-RAG06-006
  @edge-case @integration
  Scenario: The runbook helps the operator distinguish a fine-tune failure from an embedding-endpoint failure
    Given the operator has run the smoke-test architect_align command and the response contains no citation
    When the operator follows the runbook's diagnostic steps in order
    Then the runbook should instruct the operator to verify llama-swap is reachable and serving the fine-tune model id first
    And the runbook should then instruct the operator to verify the Ollama embeddings endpoint is reachable and returning vectors
    And the diagnostic order should let the operator localise the failure to llama-swap, Ollama, ChromaDB, or the agent host without guessing

  # Why: Cold-start window after llama-swap registers but before model is in VRAM
  # produces slow-or-failing responses that look like a misconfiguration
  # [ASSUMPTION: confidence=low] Warm-up window is described qualitatively — "tens of seconds while the model loads into VRAM" — rather than with a specific second-count, because GB10 + Gemma 4 26B-A4B MoE warm-up has not been measured for this fine-tune yet
  @task:TASK-RAG06-003
  @edge-case @integration
  Scenario: The runbook explains the warm-up window between model registration and first inference
    Given the operator has just registered the fine-tune with llama-swap
    When the operator immediately runs the smoke-test architect_align command
    Then the runbook should explain that the first inference may take noticeably longer than steady-state because the model is loading into VRAM
    And the runbook should give the operator a way to confirm the model is loaded before declaring the smoke test failed
    And the runbook should distinguish this expected first-call latency from a genuine inference failure

  # Why: Role config pinning the collection version is the canonical drift surface
  # between FEAT-RAG-02 ingestion and FEAT-RAG-03 retrieval
  @task:TASK-RAG06-006
  @edge-case @integration
  Scenario: The runbook helps the operator detect a collection-name drift between role config and the GB10 collection
    Given the role configuration pins knowledge_index.collection to a versioned collection name
    When the operator inspects the live collections present on the GB10 host
    Then the runbook should give the operator a command to list the collections that exist on the GB10 host
    And the runbook should tell the operator how to compare that listing against the collection name pinned in role configuration
    And the runbook should give a clear next action when the pinned name is not present on the GB10 host
