# Generated by /feature-spec
# Feature: Provider-conditional Player system prompt + <think>-block handling (FEAT-RAG-05)
# Stack: python
# Assumptions: 11 (see provider-conditional-player-prompt_assumptions.yaml)
# Generated: 2026-05-04T12:00:00Z

@feat-rag-05 @provider-conditional-prompt @think-block-handling
Feature: Provider-conditional Player system prompt and <think>-block handling

  As an operator running the architect role across cloud and local providers
  I want the Player system prompt to switch automatically to the GOAL.md-trained
  prompt when AGENT_MODELS__REASONING_MODEL=local and to strip <think>...</think>
  blocks before Coach evaluation while preserving them in the session log
  So that the SLM-vs-frontier comparison thesis (FEAT-RAG-07-03) is fair —
  the fine-tune is run against the prompt it was trained on, the Coach is not
  scoring chain-of-thought, and full reasoning traces remain auditable.

  Background:
    Given the architect role is loaded from roles/architect/
    And the Phase 0 Player prompt exists at roles/architect/prompts/player.md
    And the GOAL.md-trained prompt is bundled with the architect role
    And the prompt loader exposes a resolve_player_prompt(provider) entry point

  # ──────────────────────────────────────────────────────────────────────
  # GROUP A: Key Examples
  # ──────────────────────────────────────────────────────────────────────

  # Why: Load-bearing thesis path — when running the local fine-tune, the
  #       prompt it was trained against must be loaded verbatim or the
  #       FEAT-RAG-07-03 comparison is not fair (per OD-2 resolution).
  # [ASSUMPTION: confidence=low] The trained prompt artefact lives at
  #       roles/architect/prompts/player_trained.md, snapshot of GOAL.md
  #       §System Prompt (ASSUM-001).
  @task:TASK-RAG05-001
  @key-example @smoke
  Scenario: Local provider loads the GOAL.md-trained Player system prompt verbatim
    Given AGENT_MODELS__REASONING_MODEL is set to "local"
    When the orchestrator resolves the Player system prompt for the architect role
    Then the resolved prompt should be the GOAL.md-trained architect prompt verbatim
    And the resolved prompt should not be modified, wrapped, or augmented

  # Why: Cloud baseline runs (the GPT-5.5 FinProxy baseline used "claude" via
  #       the existing AGENT_MODELS path) must keep using the Phase 0 Player
  #       prompt — the comparison loses meaning if both sides shift.
  @task:TASK-RAG05-001
  @key-example @smoke
  Scenario Outline: Cloud providers continue to use the Phase 0 Player prompt
    Given AGENT_MODELS__REASONING_MODEL is set to "<provider>"
    When the orchestrator resolves the Player system prompt for the architect role
    Then the resolved prompt should be the existing Phase 0 architect Player prompt
    And the resolved prompt should not be the GOAL.md-trained prompt

    Examples:
      | provider |
      | claude   |
      | gemini   |
      | openai   |

  # Why: The fine-tune emits <think>...</think> followed by the answer; the
  #       Coach must score only the answer (per OD-3) so style criteria
  #       like trade-off acknowledgement are evaluated on the visible
  #       response, not the chain-of-thought.
  @task:TASK-RAG05-002
  @key-example @smoke
  Scenario: <think> blocks are stripped from Player output before Coach evaluation
    Given the Player produced output containing a <think>...</think> block followed by an answer
    When the orchestrator prepares the Player output for Coach evaluation
    Then the content sent to the Coach should not contain any <think>...</think> block
    And the visible answer should be preserved unchanged

  # Why: Traceability — operators reviewing a session need to see the
  #       fine-tune's reasoning to diagnose failures. Stripping for the
  #       Coach must not strip from the audit trail.
  @task:TASK-RAG05-002
  @key-example @smoke
  Scenario: Full <think> reasoning is preserved in the session log
    Given the Player produced output containing a <think>...</think> block followed by an answer
    When the orchestrator records the Player output to the session log
    Then the session log entry should contain the full output including the <think> block
    And the session log entry should be marked as the raw Player output

  # ──────────────────────────────────────────────────────────────────────
  # GROUP B: Boundary Conditions
  # ──────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — Player output with no <think> block (cloud
  #       providers, or any local response that skipped reasoning) must
  #       pass through the stripping helper unchanged.
  @task:TASK-RAG05-002
  @boundary
  Scenario: Output with no <think> block passes through the stripping helper unchanged
    Given the Player produced output with no <think> block
    When the orchestrator prepares the Player output for Coach evaluation
    Then the content sent to the Coach should equal the original output byte-for-byte

  # Why: Just-inside boundary — multiple <think> blocks (multi-turn fine-tune
  #       output) must all be stripped, not just the first.
  # [ASSUMPTION: confidence=medium] The fine-tune may emit more than one
  #       <think> block in a single response (multi-turn behaviour layer
  #       per GOAL.md). All occurrences are stripped (ASSUM-002).
  @task:TASK-RAG05-002
  @boundary
  Scenario: Multiple <think> blocks in the same output are all stripped
    Given the Player produced output containing two separate <think>...</think> blocks
    When the orchestrator prepares the Player output for Coach evaluation
    Then the content sent to the Coach should contain no <think>...</think> block
    And the surviving non-<think> text should appear in its original order

  # Why: Just-inside boundary — empty <think></think> is structurally legal
  #       per the trained format but contributes no reasoning. Strip cleanly.
  # [ASSUMPTION: confidence=medium] An empty <think></think> tag pair is
  #       valid input and is removed entirely, including the tags (ASSUM-003).
  @task:TASK-RAG05-002
  @boundary
  Scenario: An empty <think></think> tag pair is removed entirely
    Given the Player produced output containing an empty <think></think> tag pair followed by an answer
    When the orchestrator prepares the Player output for Coach evaluation
    Then the content sent to the Coach should not contain "<think>" or "</think>"
    And the answer text should be preserved

  # Why: Just-inside boundary — environment variable absent means the
  #       provider defaults to the historical Phase 0 path (claude). Must
  #       resolve to the Phase 0 prompt, not the GOAL.md prompt.
  @task:TASK-RAG05-001
  @boundary
  Scenario: AGENT_MODELS__REASONING_MODEL unset falls back to the Phase 0 Player prompt
    Given AGENT_MODELS__REASONING_MODEL is unset
    When the orchestrator resolves the Player system prompt for the architect role
    Then the resolved prompt should be the existing Phase 0 architect Player prompt

  # Why: Just-outside boundary — case mismatch ("Local") is a common
  #       operator mistake. Define behaviour rather than letting case
  #       sensitivity determine which prompt the fine-tune sees.
  # [ASSUMPTION: confidence=low] Provider names are matched
  #       case-insensitively when resolving the prompt. NB: the existing
  #       create_llm_client comparison is case-sensitive — this assumption
  #       diverges from that and may need alignment (ASSUM-004).
  @task:TASK-RAG05-001
  @boundary
  Scenario: Provider name matching is case-insensitive when selecting the prompt
    Given AGENT_MODELS__REASONING_MODEL is set to "Local"
    When the orchestrator resolves the Player system prompt for the architect role
    Then the resolved prompt should be the GOAL.md-trained architect prompt

  # ──────────────────────────────────────────────────────────────────────
  # GROUP C: Negative Cases
  # ──────────────────────────────────────────────────────────────────────

  # Why: Unknown provider must produce a clear configuration error rather
  #       than silently selecting one prompt over the other — wrong
  #       prompt choice silently corrupts the FEAT-RAG-07 comparison.
  @task:TASK-RAG05-001
  @negative
  Scenario: Unknown provider value produces a clear configuration error
    Given AGENT_MODELS__REASONING_MODEL is set to "groq"
    When the orchestrator resolves the Player system prompt for the architect role
    Then the operator should see an error indicating the provider is not recognised
    And no Player prompt should be returned

  # Why: If the GOAL.md-trained prompt artefact is missing from the role
  #       (e.g. installer dropped it), running the local provider must
  #       fail loudly — silently falling back to the Phase 0 prompt
  #       invalidates the thesis without the operator knowing.
  # [ASSUMPTION: confidence=medium] When provider=local but the trained
  #       prompt artefact is missing, the orchestrator raises a clear
  #       error rather than falling back silently to the Phase 0 prompt
  #       (ASSUM-005).
  @task:TASK-RAG05-001
  @negative
  Scenario: Local provider with missing trained-prompt artefact fails loudly
    Given AGENT_MODELS__REASONING_MODEL is set to "local"
    And the GOAL.md-trained prompt artefact is missing from the architect role
    When the orchestrator resolves the Player system prompt for the architect role
    Then the operator should see an error explaining the trained prompt is unavailable
    And the operator should see guidance referencing the architect role configuration

  # Why: Malformed <think> block (opening tag with no closing tag) must
  #       not strip the entire response or hang a regex engine — the
  #       Coach should receive something useful and the failure should
  #       be visible in the session log.
  # [ASSUMPTION: confidence=low] An unterminated <think> tag is treated
  #       as malformed and the original text is sent to the Coach
  #       unchanged; a warning is recorded in the session log (ASSUM-006).
  @task:TASK-RAG05-002
  @negative
  Scenario: Malformed (unterminated) <think> tag is handled without data loss
    Given the Player produced output containing an opening <think> tag with no closing tag
    When the orchestrator prepares the Player output for Coach evaluation
    Then the content sent to the Coach should equal the original output unchanged
    And a malformed-think-block warning should be recorded in the session log

  # ──────────────────────────────────────────────────────────────────────
  # GROUP D: Edge Cases
  # ──────────────────────────────────────────────────────────────────────

  # Why: Two-model split (Player=local, Coach=claude) is endorsed by
  #       phase-rag-build-plan §Risk Mitigation. Prompt selection must
  #       follow the *Player's* provider, not the Coach's, or the local
  #       Player will receive the cloud prompt.
  @task:TASK-RAG05-001
  @edge-case @regression
  Scenario: Two-model split — Player=local, Coach=claude — selects prompts per-role
    Given the Player provider is "local"
    And the Coach provider is "claude"
    When the orchestrator resolves prompts for both roles
    Then the Player prompt should be the GOAL.md-trained architect prompt
    And the Coach prompt should be the existing Phase 0 architect Coach prompt

  # Why: The stripping helper sits in the rejection-revision loop too —
  #       on retry, the Player's revised output (still containing
  #       <think>) must be stripped again before going to the Coach,
  #       not just on the first turn.
  @task:TASK-RAG05-002
  @edge-case
  Scenario: <think> stripping applies on revision turns, not just the first attempt
    Given the Coach rejected the Player's first output
    And the Player produced a revised output containing a <think>...</think> block
    When the orchestrator prepares the revised output for Coach evaluation
    Then the content sent to the Coach should not contain any <think>...</think> block
    And the session log should retain the full revised output for the revision turn

  # Why: D5 invariant — the new prompt-selection logic must not change
  #       Coach tool inventory or factory signature. Regression guard.
  @task:TASK-RAG05-001
  @edge-case @regression @security
  Scenario: Provider-conditional prompt selection does not affect Coach tool inventory
    Given AGENT_MODELS__REASONING_MODEL is set to "local"
    When the Coach is created for the architect role
    Then the Coach should have zero tools
    And the Coach factory should not accept a tools parameter

  # Why: Stripping integrity — the helper must not corrupt content that
  #       happens to contain literal "<think>" text inside a code block
  #       (architects often discuss tags in markdown). Round-trip on
  #       fenced code blocks is required.
  # [ASSUMPTION: confidence=low] <think> appearing inside a fenced code
  #       block (```...```) is preserved as content; only top-level
  #       <think>...</think> tag pairs are treated as reasoning blocks
  #       (ASSUM-007).
  @task:TASK-RAG05-002
  @edge-case
  Scenario: Literal <think> text inside a fenced code block is preserved
    Given the Player produced output containing a fenced code block that mentions the literal string "<think>"
    When the orchestrator prepares the Player output for Coach evaluation
    Then the content sent to the Coach should still contain the fenced code block intact
    And the literal "<think>" inside the code block should not be stripped

  # ──────────────────────────────────────────────────────────────────────
  # GROUP E: Edge Case Expansion — Security / Concurrency / Integration
  # ──────────────────────────────────────────────────────────────────────

  # Why: An adversarial Player output could embed instructions inside a
  #       <think> block designed to leak through if the stripping helper
  #       is naive — e.g. nested tags or content that re-wraps after the
  #       strip. Defence-in-depth: post-strip output must contain no
  #       <think> markers at all, even after multiple strip passes.
  # [ASSUMPTION: confidence=low] The stripping helper is idempotent —
  #       re-running it on already-stripped content produces no change
  #       (ASSUM-008).
  @task:TASK-RAG05-002
  @edge-case @security
  Scenario: Stripping helper is idempotent against re-injection attempts
    Given the Player produced output where stripping <think> blocks once still leaves a <think> token in the result
    When the orchestrator runs the stripping helper twice on the output
    Then the final content sent to the Coach should contain no <think> or </think> token
    And the helper should not loop indefinitely

  # Why: If an attacker (or a misconfigured installer) replaces the
  #       trained prompt with a different one, the FEAT-RAG-07 thesis
  #       result becomes meaningless — the model is no longer being run
  #       against what it was trained on. Operator must be able to
  #       verify the active prompt artefact.
  # [ASSUMPTION: confidence=low] The trained prompt artefact's identity
  #       is recorded in the session log (e.g. its source path or a
  #       content hash) so post-hoc audits can verify which prompt was
  #       actually used in a given session (ASSUM-009).
  @task:TASK-RAG05-001
  @edge-case @security
  Scenario: Active trained-prompt artefact identity is recorded in the session log
    Given AGENT_MODELS__REASONING_MODEL is set to "local"
    When the orchestrator resolves and uses the Player system prompt
    Then the session log should record which prompt artefact was loaded
    And an operator should be able to verify the artefact identity from the log alone

  # Why: Two operators (or a fleet topology — see NATS fleet integration)
  #       may run sessions concurrently with different reasoning_model
  #       settings. Prompt selection must not depend on global mutable
  #       state — each session resolves independently from its own
  #       configuration.
  # [ASSUMPTION: confidence=medium] Each session's prompt is resolved
  #       from the configuration in scope at session-start, not from
  #       any process-wide cache that could be mutated by a later
  #       session (ASSUM-010).
  @task:TASK-RAG05-001
  @edge-case
  Scenario: Concurrent sessions with different providers resolve prompts independently
    Given session A is started with AGENT_MODELS__REASONING_MODEL set to "local"
    And session B is started with AGENT_MODELS__REASONING_MODEL set to "claude"
    When both sessions resolve their Player system prompts at the same time
    Then session A's prompt should be the GOAL.md-trained architect prompt
    And session B's prompt should be the existing Phase 0 architect Player prompt
    And changing the environment variable in one session should not affect the other

  # Why: Architect role has four Player prompt variants (greenfield,
  #       align, exploration, feasibility) — one per mode. The fine-tune
  #       was trained against ONE system prompt (GOAL.md), so when
  #       running locally all four modes must route to the same trained
  #       prompt or the model is run against an unfamiliar prompt for
  #       three of the four modes.
  # [ASSUMPTION: confidence=medium] When provider=local, the trained
  #       GOAL.md prompt replaces the Player system prompt for all four
  #       modes (greenfield, align, exploration, feasibility); cloud
  #       providers continue to use the per-mode Phase 0 prompts
  #       (ASSUM-011).
  @task:TASK-RAG05-001
  @edge-case @regression
  Scenario Outline: All architect modes use the trained prompt when provider is local
    Given AGENT_MODELS__REASONING_MODEL is set to "local"
    When the orchestrator resolves the Player system prompt for the architect role in "<mode>" mode
    Then the resolved prompt should be the GOAL.md-trained architect prompt
    And the resolved prompt should not be the per-mode Phase 0 prompt for "<mode>"

    Examples:
      | mode        |
      | greenfield  |
      | align       |
      | exploration |
      | feasibility |

  # Why: The rejection-revision loop reinjects Coach feedback as a user
  #       message containing the prior Player output (per TASK-REV-R2A1).
  #       After <think> stripping, the feedback that goes back to the
  #       Player must still satisfy assert_no_system_messages — the
  #       stripping must not change the role of the message.
  @task:TASK-RAG05-002
  @edge-case @regression
  Scenario: Stripped output reinjected on revision still satisfies the message-role contract
    Given the Coach rejected the Player's first output
    And the Player's first output contained a <think>...</think> block
    When the orchestrator constructs the revision input for the Player
    Then assert_no_system_messages should pass on the revision input
    And the revision input should contain only "user" or "assistant" roles
