# Generated by /feature-spec
# Feature: Mode 3 Explorer — Codebase Analysis and Drift Detection
# Stack: python
# Assumptions: 6 (see mode-3-explorer_assumptions.yaml)
# Generated: 2026-04-12T00:00:00Z

@mode-3-explorer
Feature: Mode 3 Explorer — Codebase Analysis and Drift Detection
  As an architect or pipeline orchestrator
  I want to analyse a codebase against its documented architecture
  So that I can detect drift, verify module boundaries, and identify undocumented components

  Background:
    Given a target codebase at a known path
    And an architecture documentation directory containing ARCHITECTURE.md

  # ━━ GROUP A: Key Examples ━━

  # Why: Core path — the fundamental value proposition of Mode 3
  @key-example @smoke
  Scenario: Running a drift check produces an exploration report
    Given the target codebase has documented architecture
    When I run an exploration with query "drift check"
    Then an ExplorationReport should be produced
    And the report should contain a summary
    And the report should contain a module map of discovered modules

  # Why: Verifies boundary detection — discovering logical modules from file structure and imports
  @key-example @smoke
  Scenario: Module boundary detection identifies logical modules
    Given the target codebase has multiple directories under src/
    When I run an exploration with query "boundary review"
    Then the module map should contain an entry for each top-level source directory
    And each module entry should list the files belonging to that module

  # Why: Core drift detection — code contradicts documented C4 containers
  @key-example @smoke
  Scenario: Drift detection identifies a component present in code but missing from documentation
    Given the target codebase contains a module not described in ARCHITECTURE.md
    When I run an exploration with query "drift check"
    Then the report should contain a drift finding with category "undocumented_dependency"
    And the finding should include evidence referencing the undocumented module path

  # Why: The inverse drift case — documented but not implemented
  @key-example
  Scenario: Drift detection identifies a documented component missing from code
    Given ARCHITECTURE.md describes a module that does not exist in the codebase
    When I run an exploration with query "drift check"
    Then the report should contain a drift finding with category "missing_component"
    And the finding should reference the documented expectation from ARCHITECTURE.md

  # Why: ADR-specific drift — code contradicts a documented architectural decision
  @key-example
  Scenario: ADR drift detection identifies code contradicting a documented decision
    Given an ADR states that the system uses event-driven communication
    And the codebase contains synchronous REST calls between internal services
    When I run an exploration with query "drift check"
    Then the report should contain a drift finding with category "adr_contradiction"
    And the finding should reference the relevant ADR

  # Why: Verifies the CLI entry point (replacing the existing stub)
  @key-example @smoke
  Scenario: Running the explore CLI command produces output
    Given the target codebase exists at a valid path
    And architecture documentation exists at a valid path
    When I run "specialist-agent explore --codebase <path> --architecture <path> --query 'drift check'"
    Then the command should complete successfully
    And an ExplorationReport should be written to the output directory

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Depth parameter — surface analysis uses file tree and imports only
  # [ASSUMPTION: confidence=high] Default exploration depth is "surface" based on ExplorationRequest type definition
  @boundary
  Scenario: Surface depth exploration scans file tree and imports without reading full source
    Given the target codebase has documented architecture
    When I run an exploration with query "drift check" and depth "surface"
    Then the Explorer should scan the file tree
    And the Explorer should extract import statements
    And the Explorer should not read full source file contents

  # Why: Depth parameter — deep analysis reads source files for detailed understanding
  # [ASSUMPTION: confidence=low] Token budget for deep exploration is 100,000 tokens based on general LLM context window convention
  @boundary
  Scenario: Deep depth exploration reads source files for detailed analysis
    Given the target codebase has documented architecture
    When I run an exploration with query "drift check" and depth "deep"
    Then the Explorer should read source file contents
    And the report findings should include evidence from source file content

  # Why: Empty codebase — edge of the valid input space
  @boundary
  Scenario: Exploring an empty codebase produces a report with no modules
    Given the target codebase directory exists but contains no source files
    When I run an exploration with query "boundary review"
    Then an ExplorationReport should be produced
    And the module map should be empty
    And the summary should indicate no source modules were found

  # Why: Single-file codebase — minimum viable codebase
  @boundary
  Scenario: Exploring a single-file codebase identifies one module
    Given the target codebase contains exactly one source file
    When I run an exploration with query "boundary review"
    Then the module map should contain exactly one entry

  # Why: Architecture docs exist but are empty — valid path, no content
  @boundary
  Scenario: Architecture docs with no content produce findings about missing documentation
    Given the architecture directory exists but ARCHITECTURE.md is empty
    When I run an exploration with query "drift check"
    Then the report should indicate that architecture documentation is insufficient for comparison

  # Why: Token budget boundary — large codebase should not exceed token limits
  # [ASSUMPTION: confidence=low] Token budget for deep exploration is 100,000 tokens based on general LLM context window convention
  @boundary
  Scenario: Large codebase exploration respects the token budget
    Given the target codebase contains more files than the token budget allows
    When I run an exploration with query "drift check" and depth "deep"
    Then the Explorer should read files up to the token budget
    And the report summary should indicate the analysis was truncated

  # ━━ GROUP C: Negative Cases ━━

  # Why: Invalid codebase path — SessionConfig validation (pre-existing)
  @negative
  Scenario: Exploration with a non-existent codebase path is rejected
    Given no directory exists at the specified codebase path
    When I attempt to run an exploration
    Then the operation should fail with an error indicating the codebase path does not exist

  # Why: Missing architecture path — no docs to compare against
  @negative
  Scenario: Exploration with a non-existent architecture path is rejected
    Given the target codebase exists
    But no directory exists at the specified architecture path
    When I attempt to run an exploration
    Then the operation should fail with an error indicating the architecture path does not exist

  # Why: Missing codebase_path in SessionConfig — pre-existing validation
  @negative
  Scenario: Creating an EXPLORATION session without codebase_path raises a validation error
    When I create a SessionConfig with mode EXPLORATION and no codebase_path
    Then a validation error should be raised
    And the error should indicate that codebase_path is required for EXPLORATION mode

  # Why: Read-only invariant — Explorer must never write files
  # [ASSUMPTION: confidence=high] Explorer tool set is scan_file_tree, read_source_file, find_imports, search_codebase (4 tools) per phase3-scope.md
  @negative
  Scenario: Explorer tools do not include any write capability
    Given the Explorer Player agent is created with exploration tools
    Then the agent tool inventory should contain only read-only tools
    And the tool inventory should not contain "write_output" or any file-write tool

  # Why: Coach D5 invariant — Coach has zero tools in exploration mode
  @negative
  Scenario: Exploration mode Coach has zero tools
    Given the Coach agent is created for exploration evaluation
    Then the Coach agent should have exactly zero tools

  # Why: Invalid query type — query must be a non-empty string
  @negative
  Scenario: Exploration with an empty query is rejected
    Given the target codebase has documented architecture
    When I attempt to run an exploration with an empty query
    Then the operation should fail with an error indicating the query must be non-empty

  # ━━ GROUP D: Edge Cases ━━

  # Why: Symlinks — codebase may contain symlinks that create circular references
  @edge-case
  Scenario: File tree scanning handles symbolic links without infinite recursion
    Given the target codebase contains symbolic links creating a circular directory reference
    When I run an exploration with query "boundary review"
    Then the Explorer should complete without hanging
    And the report should note that symbolic links were encountered

  # Why: Binary files — codebase may contain non-text files
  @edge-case
  Scenario: Explorer gracefully skips binary files during source analysis
    Given the target codebase contains binary files alongside source files
    When I run an exploration with query "drift check"
    Then the Explorer should skip binary files
    And the report should only reference analysable source files

  # Why: Mixed language codebase — import analysis starts Python-only per scope
  # [ASSUMPTION: confidence=high] Import analysis supports Python only per phase3-build-plan.md
  @edge-case
  Scenario: Import analysis handles Python files and notes unsupported languages
    Given the target codebase contains both Python and JavaScript source files
    When I run an exploration with query "drift check"
    Then import analysis should be performed for Python files
    And the report should note that non-Python files were present but import analysis was limited

  # Why: No ARCHITECTURE.md but ADRs exist — partial documentation
  @edge-case
  Scenario: Exploration proceeds when ADRs exist but ARCHITECTURE.md is absent
    Given the architecture directory contains ADR files but no ARCHITECTURE.md
    When I run an exploration with query "drift check"
    Then the report should use available ADRs for drift comparison
    And the report should note that no top-level architecture summary was found

  # Why: Coach evaluation is optional for Mode 3 — configurable per scope doc
  # [ASSUMPTION: confidence=medium] Coach evaluation is optional in exploration mode, disabled by default per phase3-scope.md and build plan
  @edge-case
  Scenario: Exploration can run without Coach evaluation when configured
    Given Coach evaluation is disabled for exploration mode
    When I run an exploration with query "drift check"
    Then an ExplorationReport should be produced by the Player
    And the report should not include Coach evaluation scores

  # Why: Concurrent exploration and greenfield sessions — max_concurrent=2
  @edge-case
  Scenario: An exploration session can run alongside a greenfield session
    Given a greenfield architecture session is in progress
    When I start an exploration session for a different codebase
    Then both sessions should proceed independently
    And neither session should affect the other's output

  # ━━ GROUP E: Edge Case Expansion ━━

  # Why: Security — codebase_path must be scoped, no path traversal
  @edge-case @negative
  Scenario: Path traversal attempt in codebase path is rejected
    Given a codebase path containing a traversal sequence such as "../../etc"
    When I attempt to run an exploration
    Then the operation should fail with an error indicating the path is invalid
    And no files outside the intended scope should be accessed

  # Why: Security — filenames in target codebase should not affect report integrity
  @edge-case
  Scenario: Codebase with adversarial filenames does not corrupt the report
    Given the target codebase contains files with unusual names including special characters
    When I run an exploration with query "boundary review"
    Then the ExplorationReport should be produced successfully
    And file references in the report should be safely escaped

  # Why: Data integrity — files may change between tree scan and file read
  @edge-case
  Scenario: File removed between tree scan and read is handled gracefully
    Given the target codebase has documented architecture
    And a source file is removed after the file tree is scanned but before it is read
    When I run an exploration with query "drift check" and depth "deep"
    Then the Explorer should skip the missing file
    And the report should note that some files were unavailable during analysis

  # Why: Data integrity — unreadable files should not abort the entire exploration
  @edge-case
  Scenario: Unreadable source file does not abort the exploration
    Given the target codebase contains a file with restricted read permissions
    When I run an exploration with query "drift check"
    Then the Explorer should skip the unreadable file
    And the report should complete with findings for all readable files

  # Why: Integration — LLM unavailable means Player cannot produce report
  @edge-case
  Scenario: Exploration fails gracefully when the LLM provider is unavailable
    Given the target codebase has documented architecture
    And the configured LLM provider is unreachable
    When I attempt to run an exploration
    Then the operation should fail with an error indicating the LLM provider is unavailable
    And no partial report should be written to the output directory

  # Why: Integration — NATS adapter round-trip for architect_explore tool
  @edge-case
  Scenario: Exploration invoked via NATS architect_explore tool returns an ExplorationReport
    Given the architect agent is registered with the fleet via NATS
    When a fleet agent sends an architect_explore command with a valid codebase path and query
    Then the architect agent should run an exploration session
    And the result payload should contain a serialised ExplorationReport
    And the result should include the correlation_id from the command
