# Generated by /feature-spec
# Feature: Shell Script Step Handlers
# Stack: python
# Assumptions: 14 (see shell-script-step-handlers_assumptions.yaml)
# Generated: 2026-06-22T06:49:07Z
#
# Scope: the two concrete runbook step handlers — deploy_compose and
# run_smoke_tests — that wrap existing shell scripts as subprocesses and are
# registered into the executor's step-type registry (from the Runbook Executor
# feature). Each handler runs a named script in a given working directory with an
# environment file available by path, captures stdout and stderr into the step
# result, and maps the script's exit status to a verdict (zero -> passed, non-zero
# -> failed; for run_smoke_tests the exit status IS the verdict). The handler adds
# no idempotency of its own — the script's own idempotency governs re-runs. It is
# credential-scoped: env_file is a path only and is never read into the result, and
# captured output is scrubbed of postgres DSN and password patterns before being
# stored in the step result or published. The executor's dispatch loop, status
# persistence, resume pointer, and lifecycle events are owned upstream by the
# Runbook Executor feature and are NOT re-specified here. Unit scenarios use a fake
# script exercising the exit-0 and exit-1 paths plus a planted-secret scrub
# assertion; one @integration @slow scenario invokes the real fleet-memory
# deploy/nas/smoke.sh against a throwaway target.

@shell-script-step-handlers
Feature: Shell Script Step Handlers
  As the Forge output-side loop
  I want deploy and smoke-test runbook steps that wrap existing shell scripts as
  subprocesses, mapping each script's exit status to a step verdict and scrubbing
  credentials out of captured output
  So that real deploy/verify scripts run as registry-dispatched steps without the
  executor knowing their internals and without leaking secrets into results or events

  Background:
    Given the deploy and smoke-test handlers are registered in the executor's step-type registry

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Core deploy path — a deploy script that exits cleanly is a passed step
  @task:TASK-SSH-003
  @key-example @smoke
  Scenario: A deploy step whose script exits cleanly is recorded as passed
    Given a deploy step naming a script that exits with status zero
    When the executor runs the step
    Then the script should run once in the step's working directory
    And the step should be recorded as passed
    And the script's exit status and captured output should be recorded in the step result

  # Why: Core smoke path — the smoke script's exit status IS the step's verdict
  @task:TASK-SSH-004
  @key-example @smoke
  Scenario: A smoke-test step whose script exits cleanly is recorded as passed
    Given a smoke-test step naming a script that exits with status zero
    When the executor runs the step
    Then the step should be recorded as passed
    And the smoke script's exit status should be the step's verdict

  # Why: The smoke script's non-zero exit is the failing verdict — this is the gate
  @task:TASK-SSH-004
  @key-example @smoke
  Scenario: A smoke-test step whose script exits non-zero is recorded as failed
    Given a smoke-test step naming a script that exits with a non-zero status
    When the executor runs the step
    Then the step should be recorded as failed
    And the failing exit status should be the step's verdict

  # Why: Both handlers must be reachable by the executor through the registry
  @task:TASK-SSH-005
  @key-example
  Scenario: The deploy and smoke handlers are registered under their step types
    Given the executor's step-type registry
    When the registry is consulted for the deploy and smoke-test step types
    Then a handler should be registered for the deploy step type
    And a handler should be registered for the smoke-test step type

  # Why: The script runs in the named working directory with the env file available
  @task:TASK-SSH-002
  @key-example
  Scenario: The script runs in its working directory with the environment file available
    Given a deploy step naming a script, a working directory, and an environment file path
    When the executor runs the step
    Then the script should run with that working directory as its current directory
    And the environment file should be available to the script by its path

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Just-inside / just-outside the pass boundary — only exit status zero passes
  # [ASSUMPTION: confidence=high] Exit status zero maps to passed; every non-zero status maps to failed.
  @task:TASK-SSH-004
  @boundary
  Scenario Outline: A step's verdict follows the script's exit status
    Given a smoke-test step naming a script that exits with status <exit_status>
    When the executor runs the step
    Then the step should be recorded as <verdict>

    Examples:
      | exit_status | verdict |
      | 0           | passed  |
      | 1           | failed  |
      | 137         | failed  |

  # Why: Zero-length boundary — a script that prints nothing still yields a recorded result
  @task:TASK-SSH-002
  @boundary
  Scenario: A script that produces no output still records a result
    Given a deploy step naming a script that exits with status zero and prints nothing
    When the executor runs the step
    Then the step should be recorded as passed
    And the step result should record empty captured output

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Negative deploy path — a deploy script that exits non-zero fails the step
  @task:TASK-SSH-003
  @negative
  Scenario: A deploy step whose script exits non-zero is recorded as failed
    Given a deploy step naming a script that exits with a non-zero status
    When the executor runs the step
    Then the step should be recorded as failed
    And the script's exit status and captured output should be recorded in the step result

  # Why: A script that cannot be run fails the step rather than crashing the executor
  # [ASSUMPTION: confidence=medium] A missing or non-executable script is contained as a step failure, not an executor crash.
  @task:TASK-SSH-002
  @negative
  Scenario: A step naming a script that cannot be run is recorded as failed
    Given a deploy step naming a script that does not exist or cannot be executed
    When the executor runs the step
    Then the step should be recorded as failed
    And the executor should not crash

  # Why: Credential scope — the env file is passed as a path; its contents are never captured
  # [ASSUMPTION: confidence=high] The handler passes env_file as a path only; it never reads the file contents into the step result or any event.
  @task:TASK-SSH-002
  @negative @edge-case
  Scenario: The environment file contents are never captured into the step result
    Given a smoke-test step whose environment file holds credentials
    When the executor runs the step
    Then the environment file's contents should not appear in the step result
    And the environment file should be referenced only by its path

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ───────────────────────────────────────────────────────────────────────────

  # Why: The handler adds no idempotency of its own — the script's own idempotency governs re-runs
  # [ASSUMPTION: confidence=high] Re-running a step re-invokes the script unchanged; idempotency is the script's responsibility, not the handler's.
  @task:TASK-SSH-003
  @edge-case
  Scenario: Re-running a deploy step re-invokes the script and preserves its own idempotency
    Given a deploy step whose script is idempotent
    When the executor runs the step twice
    Then the script should run on each execution
    And the handler should add no idempotency guard of its own
    And the end state should match the script's own idempotent behaviour

  # Why: Output-scrub on store — a postgres DSN in script output is scrubbed before it reaches the result
  @task:TASK-SSH-001
  @edge-case @smoke
  Scenario: A postgres DSN in the script output is scrubbed before being stored
    Given a deploy step whose script prints a postgres connection string to its output
    When the executor runs the step
    Then the stored step result should not contain the postgres connection string
    And the captured output should show the connection string replaced by a redaction marker

  # Why: Output-scrub on publish — a password in script output is scrubbed before the result is announced
  @task:TASK-SSH-001
  @edge-case
  Scenario: A password in the script output is scrubbed before the result is published
    Given a smoke-test step whose script prints a password to its output
    When the executor runs the step
    Then the published step result should not contain the password
    And the published captured output should show the password replaced by a redaction marker

  # Why: Both streams captured — a secret on the error stream is captured and scrubbed too
  # [ASSUMPTION: confidence=medium] stdout and stderr are both captured into the single captured-output field; scrubbing applies to both.
  @task:TASK-SSH-002
  @edge-case
  Scenario: A secret printed to the error stream is captured and scrubbed
    Given a smoke-test step whose script prints a postgres DSN to its error stream and exits non-zero
    When the executor runs the step
    Then the step should be recorded as failed
    And the captured output should include the error stream
    And the postgres DSN should not appear anywhere in the captured output

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP E — Edge Cases (Credential Scope & Failure Recovery)
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Strongest leak test — even credentials the script itself prints from the env file are scrubbed
  @task:TASK-SSH-001
  @edge-case @negative
  Scenario: Credentials the script prints from its environment file are scrubbed from the result
    Given a smoke-test step whose script prints the contents of its environment file, including a postgres DSN, to its output
    When the executor runs the step
    Then the postgres DSN should not appear in the stored step result
    And the captured output should show the DSN replaced by a redaction marker

  # Why: Scrub-then-store-then-publish must not double-redact — the scrub is idempotent
  # [ASSUMPTION: confidence=medium] The output scrub is idempotent — scrubbing already-redacted output yields the same output.
  @task:TASK-SSH-001
  @edge-case
  Scenario: Output that already contains a redaction marker is left unchanged by the scrub
    Given a deploy step whose script prints output that already contains a redaction marker
    When the executor runs the step
    Then the captured output should retain that redaction marker unchanged
    And no marker should be redacted a second time

  # Why: Scrubbing is independent of verdict — a failing step's output is scrubbed just like a passing one
  @task:TASK-SSH-001
  @edge-case @negative
  Scenario: A postgres DSN is scrubbed even when the script fails
    Given a deploy step whose script prints a postgres DSN and then exits with a non-zero status
    When the executor runs the step
    Then the step should be recorded as failed
    And the postgres DSN should not appear in the stored step result

  # Why: Failure recovery composes with idempotency — an interrupted script leaves the step re-runnable
  # [ASSUMPTION: confidence=medium] A step whose script is interrupted before it exits is not recorded as passed, so a later run re-invokes the script.
  @task:TASK-SSH-003
  @edge-case
  Scenario: A script interrupted before it exits leaves the step re-runnable
    Given a deploy step whose idempotent script is interrupted before it exits
    When the executor runs the step again later
    Then the step should not have been recorded as passed from the interrupted run
    And the script should be re-invoked on the later run

  # Why: The handler does not pre-validate the env-file path — a missing file surfaces as the script's own failure
  # [ASSUMPTION: confidence=low] The handler does not check that the env-file path exists; a missing env file becomes the script's non-zero exit, hence a step failure.
  @task:TASK-SSH-004
  @edge-case @negative
  Scenario: A smoke step whose environment file path does not exist fails via the script's exit status
    Given a smoke-test step whose environment file path does not exist
    When the executor runs the step
    Then the handler should not reject the step before running the script
    And the step's verdict should be the script's exit status

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP F — Integration
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Real-script proof — the actual fleet-memory smoke script is the verdict against a throwaway target
  # [ASSUMPTION: confidence=medium] The integration test is marker-gated and runs only against a disposable target, never production.
  @task:TASK-SSH-006
  @integration @slow
  Scenario: The fleet-memory smoke script runs against a throwaway target and its exit status is the verdict
    Given the fleet-memory smoke-test script and a throwaway target
    When the executor runs a smoke-test step naming that script
    Then the smoke script should run to completion against the throwaway target
    And the step's verdict should be the script's exit status
    And no credentials from the script output should appear in the step result
