# Generated by /feature-spec
# Feature: Ablation Fixture Tooling (FEAT-ABL-005)
# Stack: python
# Assumptions: 8 (see ablation-fixture-tooling_assumptions.yaml)
# Generated: 2026-07-03T12:00:00Z
#
# Context sources: docs/research/ideas/phase-ablation-scope.md (§2 store stats,
# §3.3 fixture + leakage control, §4 FEAT-ABL-005, §7 out-of-scope),
# docs/research/ideas/phase-ablation-build-plan.md (Step 2), src/fleet_memory/store.py,
# src/fleet_memory/settings.py, src/fleet_memory/retrieval/core.py,
# deploy/local/docker-compose.yml
#
# Domain vocabulary: "event timestamp" = episode_meta.occurred_at (when the
# described work actually happened); "ingestion time" = row created_at (when the
# backfill wrote the row, 2026-06-28 onward — never used as the cut axis);
# "corpus" = the set of retrievable memory entries and their search index;
# "scratch namespace" = an isolated area for rollout-time writes.

@ablation-fixture-tooling
Feature: Ablation Fixture Tooling
  As the memory-ablation runner (FEAT-ABL-006)
  I want versioned, hash-verified fixtures of the memory store with per-task temporal cuts and scratch write isolation
  So that every on-arm rollout retrieves from a byte-identical, answer-key-free corpus and rollout writes never contaminate the fixture or the source store

  Background:
    Given a source memory store seeded with entries that carry event timestamps and entries that have none

  # ───────────────────────── Key examples ────────────────────────────

  # Why: Core path — a snapshot produces a versioned, hash-verified fixture
  @task:TASK-ABL5-002
  @key-example @smoke
  Scenario: Snapshotting a store produces a versioned fixture with a content hash
    When I snapshot the store as fixture "v1"
    Then a fixture identified as "v1" should exist
    And the fixture should carry a content hash of its corpus
    And the fixture should record the count of entries that have no event timestamp

  # Why: Core path — restore rebuilds the full corpus in an isolated per-run store
  @task:TASK-ABL5-002
  @key-example @smoke
  Scenario: Restoring a fixture yields the complete corpus in a fresh per-run store
    Given a fixture "v1" snapshotted from the source store
    When I restore fixture "v1" into a fresh per-run store
    Then the per-run store should contain every corpus entry recorded in the fixture
    And every corpus entry should have exactly one matching search index entry

  # Why: The scope acceptance "same fixture id => byte-identical retrieval corpus"
  @task:TASK-ABL5-006
  @key-example @smoke
  Scenario: The same fixture id yields a byte-identical corpus on every restore
    Given a fixture "v1" with a recorded content hash
    When I restore fixture "v1" into a fresh per-run store
    And I re-snapshot the per-run store
    Then the re-snapshotted corpus should be byte-identical to fixture "v1"
    And the re-snapshotted content hash should equal the recorded hash

  # Why: The leakage control — entries from on or after the task's start never reach the on-arm
  @task:TASK-ABL5-003
  @key-example
  Scenario: Applying a task's temporal cut removes entries from on or after the task start date
    Given a per-run store restored from fixture "v1"
    When I apply a temporal cut for a task that started on "2026-06-20"
    Then entries whose event timestamp is on or after "2026-06-20" should be absent from the corpus
    And entries whose event timestamp is before "2026-06-20" should remain in the corpus

  # Why: Rollout-time writes must never contaminate the fixture corpus
  @task:TASK-ABL5-004
  @key-example
  Scenario: Rollout writes land in a scratch namespace and are discarded after the rollout
    Given a per-run store restored from fixture "v1"
    When a rollout writes new entries into its scratch namespace
    And the rollout's scratch namespace is discarded
    Then no entries written by the rollout should remain in the per-run store
    And the fixture corpus in the per-run store should be unchanged

  # ─────────────────────── Boundary conditions ───────────────────────

  # Why: The cut is inclusive at the start date — "occurred_at >= the task's FEAT start date" is excluded
  @task:TASK-ABL5-003
  @boundary
  Scenario Outline: Entries are retained or excluded by their event timestamp relative to the cut
    Given a per-run store containing an entry with event timestamp "<timestamp>"
    When I apply a temporal cut for a task that started on "2026-06-25"
    Then the entry should be <fate>

    Examples:
      | timestamp            | fate     |
      | 2026-06-24T23:59:59Z | retained |
      | 2026-06-25T00:00:00Z | excluded |
      | 2026-06-29T10:00:00Z | excluded |

  # Why: Untimestamped distilled outcomes reference later-era work — answer-key risk, excluded unconditionally
  @task:TASK-ABL5-003
  @boundary @negative
  Scenario: Entries with no event timestamp are excluded by every temporal cut
    Given a per-run store containing entries that have no event timestamp
    When I apply a temporal cut for a task that started on "2026-06-25"
    Then every entry with no event timestamp should be absent from the corpus

  # Why: Ingestion time is backfill-era and useless as the cut axis — old work ingested recently must survive
  # [ASSUMPTION: confidence=high] The cut axis is the event timestamp, never the ingestion time
  @task:TASK-ABL5-003
  @boundary @regression
  Scenario: An entry ingested recently but describing work before the cut is retained
    Given a per-run store containing an entry ingested during the backfill era whose event timestamp is "2026-05-01T09:00:00Z"
    When I apply a temporal cut for a task that started on "2026-06-25"
    Then the entry should be retained

  # Why: Just-inside pair for the untimestamped rule — a timestamped entry before the cut is never confused with an untimestamped one
  @task:TASK-ABL5-003
  @boundary
  Scenario: A timestamped entry before the cut survives a cut that removes all untimestamped entries
    Given a per-run store containing one entry with event timestamp "2026-06-01T00:00:00Z" and one entry with no event timestamp
    When I apply a temporal cut for a task that started on "2026-06-25"
    Then the timestamped entry should be retained
    And the untimestamped entry should be absent from the corpus

  # ───────────────────────── Negative cases ──────────────────────────

  # Why: A missing fixture must fail loudly, not silently run against nothing
  @task:TASK-ABL5-002
  @negative
  Scenario: Restoring an unknown fixture id fails with a clear error
    When I attempt to restore fixture "does_not_exist" into a fresh per-run store
    Then the restore should be refused
    And the error should indicate the fixture is unknown

  # Why: A corrupted or tampered fixture must never grade a rollout
  @task:TASK-ABL5-002
  @negative
  Scenario: A fixture whose content no longer matches its recorded hash is refused
    Given a fixture "v1" whose content has been altered since its hash was recorded
    When I attempt to restore fixture "v1" into a fresh per-run store
    Then the restore should be refused
    And the error should indicate the content hash does not match

  # Why: A cut without a valid task start date would silently skip leakage control
  @task:TASK-ABL5-003
  @negative
  Scenario: A temporal cut without a valid task start date is refused
    Given a per-run store restored from fixture "v1"
    When I attempt to apply a temporal cut without a valid task start date
    Then the cut should be refused
    And the corpus should be unchanged

  # Why: P3 constraint — the live store is read-only for this tooling, always
  @task:TASK-ABL5-006
  @negative @smoke
  Scenario: Snapshotting never modifies the source store
    When I snapshot the store as fixture "v1"
    Then the source store contents should be unchanged
    And no entries should have been added, altered, or removed in the source store

  # ─────────────────────────── Edge cases ────────────────────────────

  # Why: The scope §4 acceptance verbatim — the FEAT-HARV cut excludes the post-FEAT smoke outcome and all untimestamped entries
  @task:TASK-ABL5-006
  @edge-case @regression @smoke
  Scenario: The FEAT-HARV cut excludes the post-FEAT smoke outcome and every untimestamped entry
    Given a per-run store containing a build outcome for "OUT-SMOKE" with event timestamp "2026-06-29T00:00:00Z"
    And the per-run store contains entries with no event timestamp
    When I apply a temporal cut for the FEAT-HARV task that started on "2026-06-25"
    Then the "OUT-SMOKE" build outcome should be absent from the corpus
    And every entry with no event timestamp should be absent from the corpus
    And the count of excluded untimestamped entries should equal the fixture's recorded count

  # Why: A cut that leaves orphaned index entries would corrupt relevance ranking
  @task:TASK-ABL5-003
  @edge-case
  Scenario: The temporal cut leaves no orphaned search index entries
    Given a per-run store restored from fixture "v1"
    When I apply a temporal cut for a task that started on "2026-06-25"
    Then every remaining corpus entry should have exactly one matching search index entry
    And no search index entry should reference an excluded corpus entry

  # Why: Scratch isolation must hold across consecutive rollouts on the same per-run store
  @task:TASK-ABL5-006
  @edge-case
  Scenario: A scratch namespace from a previous rollout never leaks into the next rollout
    Given a per-run store where a previous rollout wrote entries into its scratch namespace
    When the previous rollout's scratch namespace is discarded
    And a new rollout begins with its own scratch namespace
    Then the new rollout should not see any entries written by the previous rollout

  # Why: Re-running the cut (retry, crash recovery) must not change the corpus further
  @task:TASK-ABL5-003
  @edge-case
  Scenario: Re-applying the same temporal cut is idempotent
    Given a per-run store where the temporal cut for a task that started on "2026-06-25" has been applied
    When I apply the same temporal cut again
    Then the corpus should be unchanged
    And the cut should report nothing further to exclude
