# Generated by /feature-spec
# Feature: ADR Output Format for Preferred Directions
# Stack: python
# Assumptions: 5 (see adr-output-format_assumptions.yaml)
# Generated: 2026-04-12T00:00:00Z

@adr-output-format
Feature: ADR Output Format for Preferred Directions
  As an architecture team lead
  I want preferred directions to use structured ADR format with decision statement, rationale, alternatives, and positive/negative consequences
  So that each architectural decision has enough depth to inform a /system-arch session without requiring re-research

  Background:
    Given the adversarial cooperation system is configured with weighted evaluation
    And the Player agent has the structured ADR format instruction in its system prompt
    And the Coach agent has the expanded decision_rationale scoring guide

  # --- GROUP A: Key Examples ---

  # Why: Core format requirement -- each preferred direction must be a structured ADR entry, not a table row
  @key-example @smoke
  Scenario: Player generates preferred directions in structured ADR format
    Given a scope input with technology decisions to be made
    When the Player generates the Preferred Directions section
    Then each preferred direction should be a structured ADR entry with a heading
    And each entry should include a decision statement
    And each entry should include a rationale with evidence from product docs
    And each entry should include at least 2 alternatives considered
    And each entry should include positive consequences
    And each entry should include negative consequences

  # Why: Validates the ADR ID format and heading structure
  # [ASSUMPTION: confidence=medium] ADR heading format is "### ADR-P1-NN -- [Decision title]"
  @key-example @smoke
  Scenario: Each ADR entry uses the correct heading format
    Given the Player generates a conversation starter with preferred directions
    When the Preferred Directions section is rendered
    Then each entry should have a heading matching "ADR-P1-NN -- [Decision title]"
    And the status should be "Preferred Direction"

  # Why: Rationale must trace back to specific source documents, not be generic
  @key-example @smoke
  Scenario: ADR rationale references specific product documentation
    Given product docs that discuss authentication options
    When the Player generates a preferred direction for authentication approach
    Then the rationale should reference specific document names as evidence
    And the rationale should not use generic phrases like "based on requirements"

  # Why: Consequences must be split into positive and negative, not a single list
  # [ASSUMPTION: confidence=medium] Positive and negative consequences are rendered as separate labelled sub-lists within the existing consequences field
  @key-example
  Scenario: ADR consequences are split into positive and negative
    Given the Player generates a preferred direction
    When the consequences section is rendered
    Then there should be at least one positive consequence
    And there should be at least one negative consequence
    And positive and negative consequences should be clearly separated

  # Why: Coach must accept well-formed structured ADR output
  # [ASSUMPTION: confidence=high] decision_rationale >= 0.85 requires structured ADR format
  @key-example @smoke
  Scenario: Coach accepts output with full structured ADR format
    Given the Player generates preferred directions in structured ADR format
    And each direction has a decision statement, rationale, at least 2 alternatives, and positive and negative consequences
    When the Coach evaluates the output
    Then the decision_rationale score should be at least 0.85

  # --- GROUP B: Boundary Conditions ---

  # Why: Minimum alternatives boundary -- exactly 2 alternatives is the minimum acceptable
  @boundary
  Scenario: ADR with exactly 2 alternatives is accepted
    Given the Player generates a preferred direction with exactly 2 alternatives
    When the Coach evaluates the output
    Then the decision_rationale score should be at least 0.85

  # Why: Just-below boundary -- fewer than 2 alternatives should score lower
  @boundary @negative
  Scenario: ADR with fewer than 2 alternatives scores below threshold
    Given the Player generates a preferred direction with only 1 alternative
    When the Coach evaluates the output
    Then the decision_rationale score should be at most 0.5

  # Why: Boundary between table format and structured format scoring
  # [ASSUMPTION: confidence=high] Table format scores at most 0.7 per expanded scoring guide
  @boundary
  Scenario: Table format preferred directions score at most 0.7 for decision_rationale
    Given the Player generates preferred directions as table rows
    And the table includes alternatives and tradeoffs per row
    When the Coach evaluates the output
    Then the decision_rationale score should be at most 0.7

  # Why: Full ADR format with evidence tracing should reach the top of the scale
  @boundary
  Scenario: Full ADR format with evidence tracing scores above 0.85
    Given the Player generates preferred directions in structured ADR format
    And each direction has at least 2 alternatives with trade-offs
    And each direction has positive and negative consequences
    And each rationale traces evidence to named source documents
    When the Coach evaluates the output
    Then the decision_rationale score should be at least 0.85

  # --- GROUP C: Negative Cases ---

  # Why: Flat table format should be penalised compared to structured format
  @negative
  Scenario: Coach penalises flat table format for preferred directions
    Given the Player generates preferred directions as a markdown table
    And each row has a one-line alternative and a one-line tradeoff
    When the Coach evaluates the output
    Then the decision_rationale score should be at most 0.7
    And the Coach feedback should indicate structured ADR format is expected

  # Why: Decisions without any rationale should score near zero
  @negative
  Scenario: Coach rejects preferred directions with no rationale
    Given the Player generates preferred directions with decision statements only
    And no rationale or alternatives are provided
    When the Coach evaluates the output
    Then the decision_rationale score should be at most 0.0

  # Why: Missing consequences (neither positive nor negative) is incomplete
  @negative
  Scenario: Coach penalises ADR entries missing consequences
    Given the Player generates preferred directions in structured ADR format
    But the entries have no consequences section
    When the Coach evaluates the output
    Then the decision_rationale score should be at most 0.5

  # Why: Generic rationale without evidence should be penalised
  @negative
  Scenario: Coach penalises ADR entries with generic rationale
    Given the Player generates preferred directions in structured ADR format
    And the rationale uses only generic phrases like "industry best practice"
    And no product documentation is referenced
    When the Coach evaluates the output
    Then the decision_rationale score should be at most 0.5

  # --- GROUP D: Edge Cases ---

  # Why: Output handler must parse structured ADR format, not just table format
  # [ASSUMPTION: confidence=medium] Handler uses heading-based detection with regex "### ADR-P1-\d+" or "### ADR-\d+"
  @edge-case
  Scenario: Output handler parses heading-based structured ADR format
    Given the Player generates preferred directions as structured ADR headings
    When the output handler parses the raw markdown
    Then each ADR entry should be extracted with its id, title, decision, alternatives, and consequences
    And the parsed ADR objects should have at least 2 alternatives each

  # Why: Backward compatibility -- handler must still parse legacy table format
  @edge-case
  Scenario: Output handler parses legacy table format for backward compatibility
    Given the Player generates preferred directions as a markdown table
    When the output handler parses the raw markdown
    Then each ADR entry should be extracted from the table rows
    And the parsed ADR objects should have the same fields as structured format

  # Why: Mixed format in a single output -- handler should handle gracefully
  @edge-case
  Scenario: Output handler handles mixed table and structured ADR format
    Given the Player generates some preferred directions as table rows
    And other preferred directions as structured ADR headings
    When the output handler parses the raw markdown
    Then all preferred directions should be extracted regardless of format

  # Why: Consequences field must support both positive and negative entries in the ADR type
  @edge-case
  Scenario: ADR type stores positive and negative consequences separately
    Given a structured ADR entry with 2 positive and 1 negative consequence
    When the entry is parsed into an ADR object
    Then the consequences list should contain all 3 consequences
    And the tradeoff field should capture the negative consequence summary

  # --- GROUP D (expanded): Format Resilience + Integration ---

  # Why: Player may produce non-sequential ADR IDs -- handler should not break
  @edge-case
  Scenario: Output handler handles non-sequential ADR numbering
    Given the Player generates ADR entries with IDs "ADR-P1-01", "ADR-P1-03", "ADR-P1-07"
    When the output handler parses the raw markdown
    Then all 3 ADR entries should be extracted
    And the original IDs should be preserved without renumbering

  # Why: Player may use different list formats for alternatives -- handler must be flexible
  @edge-case
  Scenario: Output handler handles varied alternatives list formats
    Given the Player generates one ADR with numbered alternatives
    And another ADR with bullet-point alternatives
    And another ADR with comma-separated inline alternatives
    When the output handler parses the raw markdown
    Then all alternatives should be extracted from each ADR entry

  # Why: Structured format must survive the full parse-validate-format pipeline
  @edge-case @regression
  Scenario: Structured ADR format survives parse-validate-format round-trip
    Given the Player generates preferred directions in structured ADR format
    When the output handler parses the raw markdown
    And the parsed output is validated
    And the validated output is formatted back to markdown
    Then the formatted output should contain structured ADR entries
    And no ADR entries should be lost in the round-trip

  # Why: Preferred Directions section must render in the correct position in the final output
  @edge-case
  Scenario: Formatter renders Preferred Directions in the correct section position
    Given a validated conversation starter with structured ADR preferred directions
    When the formatter renders the full output
    Then the Preferred Directions section should appear after the C4 diagrams
    And the Preferred Directions section should appear before the Open Questions
