# Generated by /feature-spec
# Feature: Outcome-Label Sidecar
# Stack: python
# Assumptions: 7 (see outcome-label-sidecar_assumptions.yaml)
# Generated: 2026-07-10T12:13:06Z

@outcome-label-sidecar
Feature: Outcome-Label Sidecar
  As a dataset-harvest consumer (QAV/coach harvest transforms, the WS4-S7 Chronicler)
  I want disposition verdicts recorded as structured label records adjacent to the evidence they judge, at judgment time
  So that harvests join outcome labels by file read instead of retro archaeology

  Background:
    Given a completed autobuild run has produced evidence artifacts for a task
    And the task's evidence directory is present on this node

  # ── GROUP A: Key Examples ──

  # Why: Core path — the "labels for free" moment: a review disposition immediately produces a label record
  # [ASSUMPTION: confidence=low] Disposition commands write labels automatically; a manual CLI covers operator_caught and live_gate_caught (Option A confirmed by human, with mapping-table and shared-writer riders)
  @task:TASK-LBL-004
  @key-example @smoke
  Scenario: A review disposition produces a label record adjacent to the evidence it judges
    Given a task review has reached a disposition with verdict class "operator_caught"
    When the disposition lands
    Then a label record should exist adjacent to the task's evidence artifacts
    And the label record should carry the task id, the feature id, and the verdict class
    And the label record should reference the evidence directory it judges
    And the label record should carry the disposition timestamp

  # Why: Each disposition source maps to its own verdict class — the four-class taxonomy is the contract,
  # and the source-to-class mapping must be an explicit table in the writer, not folklore
  @task:TASK-LBL-004
  @key-example
  Scenario Outline: Each disposition source records its corresponding verdict class
    Given a <source> disposition has been reached for the task
    When the disposition lands
    Then the label record should carry the verdict class "<verdict_class>"

    Examples:
      | source       | verdict_class       |
      | coach-upheld | coach_correct       |
      | operator     | operator_caught     |
      | merge review | merge_review_caught |
      | live gate    | live_gate_caught    |

  # Why: 9F43 rider — labels must join the run identity so Chronicler rows correlate
  @task:TASK-LBL-002
  @key-example
  Scenario: A label record carries the run correlation identity
    Given the evidence artifacts were produced by a run with a known run identity and attempt number
    When a disposition lands for that task
    Then the label record should carry the same run identity as the evidence it judges
    And the label record should carry the attempt number of the judged turn

  # Why: The consumer contract — a harvest joins labels to evidence purely by reading files
  @task:TASK-LBL-004
  @key-example @smoke
  Scenario: A harvest consumer joins labels to evidence by file read alone
    Given label records exist for several tasks with dispositions
    When a harvest transform reads the label records for a task
    Then it should recover the verdict class, evidence reference, and run identity without consulting any external service
    And it should not require manual retro archaeology to determine the outcome

  # ── GROUP B: Boundary Conditions ──

  # Why: Just-inside boundary — first disposition creates the sidecar; zero-to-one record
  @task:TASK-LBL-001
  @boundary
  Scenario: The first disposition for a task creates the label sidecar
    Given no label records exist for the task
    When the first disposition lands
    Then exactly one label record should exist for the task

  # Why: Append-only at the two-record boundary — a second disposition never replaces the first
  @task:TASK-LBL-001
  @boundary @smoke
  Scenario: A second disposition appends without altering the first label
    Given a label record with verdict class "coach_correct" already exists for the task
    When a later merge-review disposition lands with verdict class "merge_review_caught"
    Then two label records should exist for the task
    And the earlier label record should be unchanged
    And the records should be readable in the order they were written

  # Why: Just-outside enum boundary — the four-class taxonomy is closed; unknown classes must not corrupt the dataset
  @task:TASK-LBL-001
  @boundary @negative
  Scenario: A disposition with an unrecognised verdict class is rejected
    Given a disposition attempts to record the verdict class "coach_wrong"
    When the label write is attempted
    Then the label record should not be written
    And the error should indicate the verdict class is not one of the recognised classes

  # Why: Boundary of the join key — a label with no task id can never be joined and is worse than no label
  @task:TASK-LBL-001
  @boundary @negative
  Scenario: A label record missing its task id is rejected
    Given a disposition attempts to record a label without a task id
    When the label write is attempted
    Then the label record should not be written
    And the error should indicate the task id is required

  # ── GROUP C: Negative Cases ──

  # Why: Append-only invariant — mutation of history would silently corrupt every downstream harvest
  @task:TASK-LBL-001
  @negative
  Scenario: An existing label record cannot be modified or deleted through the sidecar writer
    Given a label record already exists for the task
    When an attempt is made to overwrite or remove that record through the label writer
    Then the attempt should be refused
    And the original record should remain intact

  # Why: The sidecar is an observer, never a gate — a failed label write must not block the disposition itself
  @task:TASK-LBL-004
  @negative @regression
  Scenario: A failed label write does not block the disposition workflow
    Given the label destination is not writable
    When a disposition lands
    Then the disposition itself should complete normally
    And a warning should be surfaced that the outcome label could not be recorded

  # Why: Node-local constraint — no fleet infrastructure may be required for a label to land
  @task:TASK-LBL-004
  @negative
  Scenario: Label writing succeeds with no fleet services available
    Given no fleet-memory or other fleet service is reachable
    When a disposition lands
    Then the label record should be written normally
    And no fleet service should have been contacted

  # ── GROUP D: Edge Cases ──

  # Why: The FEAT-OBSC rider — labels adjacent to live artifacts must survive the archive-before-prune move
  @task:TASK-LBL-006
  @edge-case @smoke @regression
  Scenario: Labels survive the archive-before-prune move
    Given label records exist adjacent to the task's live evidence artifacts
    When the worktree is cleaned up and its artifacts are archived
    Then the archived copy should contain the label records
    And the archived labels should remain joinable by task id

  # Why: Dispositions often land AFTER cleanup (reviews are post-merge) — the sidecar must still have a durable home
  # [ASSUMPTION: confidence=high] Post-archival labels are written to the durable archive home for the task, honouring the configured archive root override
  @task:TASK-LBL-003
  @edge-case
  Scenario: A disposition landing after archival writes its label to the archive home
    Given the task's evidence artifacts have already been archived and the live worktree pruned
    When a disposition lands for that task
    Then the label record should be written to the archived evidence's home
    And it should be joinable by task id alongside the archived artifacts

  # Why: D-S10-1 consumer — class coverage over labels feeds the Coach v4 per-class floor
  # [ASSUMPTION: confidence=medium] Label records carry an optional defect-class field from the retro taxonomy; records without it count as unattributed
  @task:TASK-LBL-004
  @edge-case
  Scenario: Label class coverage is derivable from the label records alone
    Given label records exist carrying defect-class attributions across several classes
    When class coverage is computed from the label records
    Then the count of labels per defect class should be reported
    And the coverage report should make visible whether the mandatory classes meet the ten-per-class floor

  # Why: Two dispositions can land near-simultaneously (parallel reviews) — appends must not lose records
  @task:TASK-LBL-001
  @edge-case
  Scenario: Concurrent dispositions for the same task both land
    Given two dispositions for the same task land at nearly the same time
    When both label writes complete
    Then both label records should exist
    And neither record should be truncated or interleaved

  # ── Expansion: security ──

  # Why: A cross-task mislabel would poison the harvest join — the evidence reference must belong to the labelled task
  @task:TASK-LBL-001
  @edge-case @negative
  Scenario: A label referencing another task's evidence is refused
    Given a disposition for one task attempts to reference the evidence directory of a different task
    When the label write is attempted
    Then the label record should not be written
    And the error should indicate the evidence reference does not belong to the labelled task

  # Why: The task id determines where the sidecar lands — the join key must not become a write primitive
  @task:TASK-LBL-003
  @edge-case @negative
  Scenario: A task id containing path traversal characters is handled safely
    Given a disposition carries a task id containing path traversal characters
    When the label write is attempted
    Then the label record should not be written outside the evidence home
    And no file outside the evidence home should be affected

  # ── Expansion: data integrity ──

  # Why: Append-only files accumulate damage — one bad record must not orphan a task's entire label history
  @task:TASK-LBL-006
  @edge-case
  Scenario: A corrupt record does not break appends or harvest reads
    Given the task's label sidecar contains one corrupt record among valid records
    When a new disposition lands and a harvest later reads the labels
    Then the new label record should be appended successfully
    And the harvest should recover all valid records
    And the corrupt record should be skipped with a warning rather than failing the read

  # Why: Retries must not create conflicting verdicts — label identity is content-addressed so dedupe is mechanical
  # [ASSUMPTION: confidence=low] Label identity is content-addressed over the judged fields excluding timestamp (overridden to Option B by human)
  @task:TASK-LBL-004
  @edge-case
  Scenario: A re-emitted disposition is idempotent by label identity
    Given a disposition has already produced a label record
    When the same disposition is re-emitted on a retry
    Then any additional record should carry the same label identity as the first
    And a harvest deduplicating by label identity should recover exactly one label

  # ── Expansion: integration boundaries ──

  # Why: The archive home can be offline (network storage) — mirrors the non-blocking posture at the archive seam
  @task:TASK-LBL-003
  @edge-case
  Scenario: An unreachable archive home does not block a post-archival disposition
    Given the task's artifacts are archived and the archive home is unreachable
    When a disposition lands for that task
    Then the disposition itself should complete normally
    And a warning should be surfaced that the outcome label could not be recorded

  # Why: Harvests run on live nodes — a reader overlapping an append must never see a torn record
  @task:TASK-LBL-001
  @edge-case
  Scenario: A harvest reading during an append sees only complete records
    Given a harvest reads the task's label records while a disposition is being appended
    When the read completes
    Then every record returned should be complete and well formed
    And no partially written record should be returned
