# Generated by /feature-spec
# Feature: Version Endpoint
# Stack: generic
# Assumptions: 3 (see version-endpoint_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@service-metadata
Feature: Version Endpoint
  As a service operator or automated checker
  I want a read-only /version endpoint that returns application metadata
  So that I can verify the running build identity and service name

  Background:
    Given the api_test service is running
    And the application version, git commit, and service name are available as build-time-injected values

  # Why: Core happy-path — confirms GET /version returns all three fields populated
  @key-example @smoke
  Scenario: A GET request to /version returns the application metadata
    When I send a GET request to /version
    Then the request should succeed
    And the response should contain the application version string
    And the response should contain the git commit hash
    And the response should contain the service name

  # Why: Just-inside boundary — GET is the only allowed method; POST must be rejected
  @boundary
  Scenario: A POST request to /version is rejected as method not allowed
    When I send a POST request to /version
    Then the request should be rejected with method not allowed

  # Why: Just-outside boundary — PUT must also be rejected
  @boundary
  Scenario: A PUT request to /version is rejected as method not allowed
    When I send a PUT request to /version
    Then the request should be rejected with method not allowed

  # Why: Just-outside boundary — PATCH must also be rejected
  @boundary
  Scenario: A PATCH request to /version is rejected as method not allowed
    When I send a PATCH request to /version
    Then the request should be rejected with method not allowed

  # Why: Just-outside boundary — DELETE must also be rejected
  @boundary
  Scenario: A DELETE request to /version is rejected as method not allowed
    When I send a DELETE request to /version
    Then the request should be rejected with method not allowed

  # Why: Negative case — response must be valid JSON with exactly the three expected keys
  @negative
  Scenario: The /version response is valid JSON with the expected keys
    When I send a GET request to /version
    Then the request should succeed
    And the response should be valid JSON
    And the response should contain exactly the keys: version, commit, and service

  # Why: Negative case — no authentication should be required (read-only, public contract)
  @negative
  Scenario: Accessing /version without authentication succeeds
    When I send a GET request to /version without authentication
    Then the request should succeed
    And the response should contain the application version string
    And the response should contain the git commit hash
    And the response should contain the service name

  # Why: Assumption-driven — git commit hash format (short vs. full) affects validation
  # [ASSUMPTION: confidence=low] The git commit hash returned is a short (7-character) hash, not a full SHA
  @negative
  Scenario: The git commit hash returned is a short 7-character string
    When I send a GET request to /version
    Then the request should succeed
    And the git commit hash field should be a 7-character alphanumeric string

  # Why: Assumption-driven — response shape mirrors existing /uptime and /stats endpoints (flat JSON)
  # [ASSUMPTION: confidence=low] The /version response is a flat JSON object with no nested structures, matching the shape of /uptime and /stats
  @negative
  Scenario: The /version response has a flat JSON structure with no nesting
    When I send a GET request to /version
    Then the request should succeed
    And the response should be a flat JSON object with no nested objects or arrays

  # Why: Assumption-driven — JSON key naming convention (lowercase, no prefixes)
  # [ASSUMPTION: confidence=low] The JSON keys are named exactly "version", "commit", and "service" (lowercase, no prefixes like "app_" or "git_")
  @negative
  Scenario: The JSON response uses the keys "version", "commit", and "service"
    When I send a GET request to /version
    Then the request should succeed
    And the response should contain the key "version"
    And the response should contain the key "commit"
    And the response should contain the key "service"
    And the response should not contain any unexpected keys