# Generated by /feature-spec
# Feature: Factory self-fix — durable receipts, command oracles, bounded judge input
# Stack: python
# Assumptions: 5 (see factory-self-fix_assumptions.yaml)
# Generated: 2026-07-25T14:35:00Z

@factory-self-fix
Feature: Factory self-fix — durable receipts, command oracles, bounded judge input
  As the factory's verification layer
  I want receipts that survive run shutdown, runtime checks any tech stack can declare, and judge input that always fits the judge
  So that the verification loop's own evidence and reach stop having known holes

  # Why: the run's LAST verdict reliably lost its receipt — the thread died with the process
  @key-example @smoke
  Scenario: A shadow receipt survives the run ending immediately after the verdict
    Given the shadow lane is enabled with a slow second-opinion seat
    When a verdict lands and the run finishes immediately afterwards
    Then the per-turn receipt file should still be written beside the verdict

  # Why: the lane's founding law must hold through the fix
  @key-example
  Scenario: A disabled shadow lane remains a provable no-op
    Given the shadow lane is disabled
    When a verdict lands
    Then no probe no seat call and no file should occur

  @negative
  Scenario: The shadow never blocks or changes the verdict it accompanies
    Given the shadow seat hangs past its time budget
    When a verdict lands
    Then the verdict should complete unchanged and on time
    And the receipt should record the absent outcome with its named reason

  # Why: the stack-agnosticism cure — any stack declares a command, no Python anywhere
  @key-example @smoke
  Scenario: A declared oracle command runs and reports a pass
    Given a worktree with no Python oracle file and a declared oracle command that succeeds
    When the coach gathers evidence
    Then the runtime-check result should report ran and passed with the command named as its origin

  @negative
  Scenario: A failing oracle command reports a failure
    Given a worktree with a declared oracle command that fails
    When the coach gathers evidence
    Then the runtime-check result should report ran and not passed with the failure output captured

  @negative
  Scenario: An oracle command that overruns its time budget is reported as timed out
    Given a declared oracle command that never finishes
    When the coach gathers evidence
    Then the runtime-check result should report timed out within the existing oracle time budget

  @boundary
  Scenario: The Python file convention takes precedence over a declared command
    Given a worktree with both a Python oracle file and a declared oracle command
    When the coach gathers evidence
    Then the file-based oracle should run and the command should not

  # Why: operator policy from committed configuration is trustworthy by construction
  @key-example
  Scenario: A command declared in committed configuration is treated as independent
    Given a declared oracle command from the feature configuration
    When the coach gathers evidence
    Then the result should never be downgraded as author-influenced

  # Why: 109,634 tokens met a 98,304 window — the judge's input must fit the judge
  @key-example @smoke
  Scenario: An oversized evidence bundle is trimmed to the judge's input budget
    Given an evidence bundle far larger than the configured input budget
    When the judging prompt is built
    Then the rendered prompt should fit within the budget
    And it should carry a visible notice naming what was trimmed

  @boundary
  Scenario: A normal-sized evidence bundle is rendered untouched
    Given an evidence bundle comfortably inside the input budget
    When the judging prompt is built
    Then the rendered prompt should contain the bundle unaltered with no trim notice

  # Why: silent trimming is the absence-of-failure trap
  @negative
  Scenario: Trimming is never silent
    Given any bundle that gets trimmed
    When the judging prompt is built
    Then a warning should be logged naming the trim and its size
