# Generated by /feature-spec
# Feature: Doc Reader Tool and Player-Coach Agent Factories
# Stack: python
# Assumptions: 3 (see doc-reader-player-coach-factories_assumptions.yaml)
# Generated: 2026-04-07T00:00:00Z

@doc-reader @agent-factories @feat-002
Feature: Doc Reader Tool and Player-Coach Agent Factories
  As an architect agent developer
  I want the doc reader tool to assemble product documentation and the Player-Coach agent
  factories to enforce tool separation
  So that the generation loop has a doc-reading Player with exactly one tool and
  an evaluation-only Coach with zero tools

  Background:
    Given the architect agent project is initialised
    And a valid LLM client is available

  # ━━ GROUP A: Key Examples ━━

  # Why: Core doc reading -- the Player's only tool assembles product docs for the prompt
  @key-example @smoke
  Scenario: Reading product docs from a valid directory
    Given a directory containing 3 markdown files
    When I call read_product_docs with that directory
    Then the result should contain content from all 3 files
    And each file's content should be preceded by a file header
    And the files should be ordered alphabetically by filename

  # Why: File header format -- downstream parsing depends on this format
  @key-example
  Scenario: Doc reader includes standardised file headers
    Given a directory containing a file named "architecture.md" with content "System overview"
    When I call read_product_docs with that directory
    Then the result should contain "## File: architecture.md"
    And the content "System overview" should follow the header
    And a separator should follow the content

  # Why: Mixed file types -- only .md and .txt are included
  @key-example
  Scenario: Doc reader includes only markdown and text files
    Given a directory containing "notes.md", "spec.txt", "image.png", and "data.json"
    When I call read_product_docs with that directory
    Then the result should contain content from "notes.md" and "spec.txt"
    And the result should not contain content from "image.png" or "data.json"

  # Why: Core factory -- Player must have exactly one tool: read_product_docs
  @key-example @smoke
  Scenario: Player factory creates an agent with exactly the read_product_docs tool
    Given a valid model configuration
    And a domain prompt for architecture generation
    And the read_product_docs tool
    When I create a Player agent
    Then the Player's tool inventory should be exactly {"read_product_docs"}

  # Why: Core factory -- Player uses create_agent, NOT create_deep_agent
  @key-example @smoke
  Scenario: Player factory uses create_agent to prevent middleware tool injection
    Given a valid model configuration
    When I create a Player agent
    Then the factory should use create_agent
    And the factory should NOT use create_deep_agent

  # Why: D5 invariant -- Coach has NO tools, evaluation only
  @key-example @smoke
  Scenario: Coach factory creates an agent with zero tools
    Given a valid model configuration
    And a domain prompt for architecture evaluation
    When I create a Coach agent
    Then the Coach's tool inventory should be exactly the empty set

  # Why: D5 invariant enforcement -- Coach factory signature omits tools parameter
  @key-example @smoke
  Scenario: Coach factory uses create_agent with an explicit empty tools list
    Given a valid model configuration
    When I create a Coach agent
    Then the factory should use create_agent
    And the factory should NOT use create_deep_agent
    And the factory should pass an empty list for tools

  # Why: Domain prompt injection -- both agents receive domain context via system prompt
  @key-example
  Scenario: Player system prompt includes the domain prompt
    Given a domain prompt containing "Evaluate C4 completeness"
    When I create a Player agent
    Then the Player's system prompt should contain the Player role instructions
    And the Player's system prompt should contain "Evaluate C4 completeness"

  # Why: Domain prompt injection -- Coach receives same domain context for evaluation criteria
  @key-example
  Scenario: Coach system prompt includes the domain prompt
    Given a domain prompt containing "Score each criterion 0.0 to 1.0"
    When I create a Coach agent
    Then the Coach's system prompt should contain the Coach role instructions
    And the Coach's system prompt should contain "Score each criterion 0.0 to 1.0"

  # ━━ GROUP B: Boundary Conditions ━━

  # [ASSUMPTION: confidence=high] Token budget is 100K tokens based on PLAN.md and API contract
  # Why: Token budget boundary -- content at exactly the limit should be included in full
  @boundary
  Scenario: Doc reader includes all content when total is at exactly the token budget
    Given a directory with files totalling approximately 100K tokens
    When I call read_product_docs with that directory
    Then all file content should be included
    And no truncation warning should be present

  # Why: Just-outside token budget -- exceeding the limit triggers truncation
  @boundary @negative
  Scenario: Doc reader truncates content when total exceeds the token budget
    Given a directory with files totalling approximately 110K tokens
    When I call read_product_docs with that directory
    Then the earlier files should be included in full
    And the later files should be truncated or omitted
    And a truncation warning should be appended

  # Why: Single file at budget -- one large file should still be read up to the limit
  @boundary
  Scenario: A single large file at the token budget is included
    Given a directory containing one markdown file of approximately 100K tokens
    When I call read_product_docs with that directory
    Then the file content should be included up to the budget
    And no truncation warning should be present

  # Why: Empty directory -- edge of "zero files" boundary
  @boundary
  Scenario: Doc reader handles an empty directory
    Given an empty directory
    When I call read_product_docs with that directory
    Then the result should be empty or contain only a no-files-found message

  # Why: Single file -- minimum valid directory content
  @boundary
  Scenario: Doc reader reads a single markdown file
    Given a directory containing exactly 1 markdown file
    When I call read_product_docs with the directory
    Then the result should contain exactly one file header and its content

  # [ASSUMPTION: confidence=medium] Token estimation uses ~4 chars per token based on PLAN.md
  # Why: Token estimation accuracy -- the 4 chars/token heuristic must be consistent
  @boundary
  Scenario: Token budget estimation is consistent with the 4 chars per token heuristic
    Given a directory with files totalling exactly 400,000 characters
    When I call read_product_docs with that directory
    Then the result should be at the token budget boundary

  # ━━ GROUP C: Negative Cases ━━

  # Why: Non-existent path -- fail fast with clear error
  @negative
  Scenario: Doc reader rejects a non-existent directory path
    Given a docs path that does not exist
    When I call read_product_docs with that path
    Then the operation should fail
    And the error should indicate the path does not exist

  # Why: Path is a file, not a directory -- docs_path must be a directory
  @negative
  Scenario: Doc reader rejects a file path instead of a directory
    Given a docs path pointing to a single file instead of a directory
    When I call read_product_docs with that path
    Then the operation should fail
    And the error should indicate the path must be a directory

  # Why: Tool separation violation -- Player must NOT have write_output
  @negative @smoke
  Scenario: Player factory rejects a tool list containing write_output
    Given a tool list containing read_product_docs and write_output
    When I create a Player agent with this tool list
    Then the factory should raise a tool separation violation error
    And the error should indicate Player must not have write_output

  # Why: Tool inventory mismatch -- unexpected tools injected must be caught
  @negative
  Scenario: Player factory detects unexpected tools in the agent inventory
    Given a Player agent that somehow has additional tools beyond read_product_docs
    When the tool inventory assertion runs
    Then the assertion should fail
    And the error should list the unexpected tools

  # Why: Coach with tools would violate D5 invariant -- must be impossible
  @negative
  Scenario: Coach factory does not accept tools in its signature
    Given an attempt to pass tools to the Coach factory
    When I inspect the Coach factory's function signature
    Then the signature should not include a tools parameter

  # Why: create_deep_agent would inject filesystem middleware -- must never be used
  @negative
  Scenario: Neither factory module imports create_deep_agent
    Given the Player and Coach factory source files
    When I inspect their imports
    Then neither module should import create_deep_agent

  # Why: Null domain prompt would leave agents without evaluation context
  @negative
  Scenario: Player factory rejects an empty domain prompt
    Given an empty domain prompt
    When I create a Player agent with the empty prompt
    Then the factory should reject the empty domain prompt
    And the error should indicate domain prompt is required

  # ━━ GROUP D: Edge Cases ━━

  # Why: Subdirectories -- doc_reader should handle nested docs
  @edge-case
  Scenario: Doc reader handles subdirectories within the docs path
    Given a directory with markdown files in both the root and a subdirectory
    When I call read_product_docs with the root directory
    Then files from both the root and subdirectory should be included
    And alphabetical ordering should apply within each level

  # Why: Unicode filenames and content -- common in international projects
  @edge-case
  Scenario: Doc reader handles files with unicode content
    Given a directory containing a markdown file with unicode characters in its content
    When I call read_product_docs with that directory
    Then the unicode content should be preserved correctly in the output

  # Why: Large number of small files -- ensures no performance degradation
  @edge-case
  Scenario: Doc reader handles a directory with many small files
    Given a directory containing 500 small markdown files within the token budget
    When I call read_product_docs with that directory
    Then all files should be included
    And the files should be ordered alphabetically

  # [ASSUMPTION: confidence=medium] Symlinks are followed, based on standard Python pathlib behaviour
  # Why: Symlinked docs directories are common in monorepos
  @edge-case
  Scenario: Doc reader follows symbolic links to markdown files
    Given a directory containing a symbolic link to a markdown file
    When I call read_product_docs with that directory
    Then the linked file's content should be included

  # Why: assert_tool_inventory must run at factory exit, not lazily
  @edge-case
  Scenario: Tool inventory assertion runs at factory creation time, not at first invocation
    Given a valid model configuration
    When I create a Player agent
    Then the tool inventory assertion should have already executed
    And the assertion result should be verifiable without invoking the agent

  # Why: Both agents receive the same domain prompt -- ensures evaluation consistency
  @edge-case
  Scenario: Player and Coach receive identical domain prompt content
    Given a specific domain prompt text
    When I create both a Player and a Coach with the same domain prompt
    Then the domain prompt portion of both system prompts should be identical

  # ━━ EDGE CASE EXPANSION: Security, Concurrency, Integration ━━

  # Why: Path traversal -- docs_path must not escape its intended directory
  @edge-case @security
  Scenario: Doc reader rejects a path traversal attempt
    Given a docs path containing "../../etc/passwd"
    When I call read_product_docs with that path
    Then the operation should fail
    And the error should indicate the path is invalid

  # Why: Prompt injection via file content -- malicious markdown must not alter agent behaviour
  @edge-case @security
  Scenario: Doc reader passes through file content without interpretation
    Given a directory containing a markdown file with embedded prompt injection text
    When I call read_product_docs with that directory
    Then the raw file content should be returned as-is
    And no instructions within the file content should be executed

  # Why: File modified mid-read -- graceful handling prevents partial or corrupt output
  @edge-case
  Scenario: Doc reader handles a file being modified during reading
    Given a directory containing markdown files
    And one file is modified while the reader is assembling content
    When I call read_product_docs with that directory
    Then the operation should complete without crashing
    And the result should contain either the original or updated content

  # Why: TASK-REV-R2A1 -- system role messages in Player input cause vLLM 400 errors
  @edge-case @smoke
  Scenario: Player agent rejects input messages with system role
    Given a Player agent created by the factory
    And input messages containing a message with role "system"
    When the input is validated before invocation
    Then the validation should fail
    And the error should indicate system messages are not allowed in ainvoke input

  # Why: TASK-REV-R2A1 -- same contract applies to Coach invocations
  @edge-case @smoke
  Scenario: Coach agent rejects input messages with system role
    Given a Coach agent created by the factory
    And input messages containing a message with role "system"
    When the input is validated before invocation
    Then the validation should fail
    And the error should indicate system messages are not allowed in ainvoke input

  # Why: Unreadable files should not crash the entire doc reading operation
  @edge-case
  Scenario: Doc reader skips files without read permissions
    Given a directory containing 3 markdown files where one lacks read permissions
    When I call read_product_docs with that directory
    Then the result should contain content from the 2 readable files
    And a warning should indicate one file could not be read
