# Generated by /feature-spec
# Feature: Relay Integration (FEAT-MEM-04)
# Stack: python
# Assumptions: 11 (see relay-integration_assumptions.yaml)
# Generated: 2026-06-13T11:04:22Z
#
# Context sources: docs/research/ideas/phase-core-build-plan.md (FEAT-MEM-04),
# docs/research/ideas/phase-core-scope.md, features/typed-payload-registry/typed-payload-registry.feature,
# features/deterministic-writer/deterministic-writer.feature, src/fleet_memory/store.py, src/fleet_memory/embed.py
#
# Relay ack/nak/DLQ semantics (D5/D9) and max_deliver inherit from the
# nats-infrastructure memory-relay scope, which is not readable from this repo;
# those values are carried here as low-confidence assumptions for Coach review.
#
# Background applies: every scenario assumes the durable consumer is subscribed
# to the MEMORY stream with the registry, writer, embedding service, and store available.

@relay-integration
Feature: Relay Integration
  As the fleet-memory relay consumer on the MEMORY stream
  I want every published MemoryEpisodeV1 routed by its content format — structured payloads through the registry to the deterministic writer, prose chunked and embedded — and acknowledged only once durably stored, with poison episodes parked and redeliveries made inert
  So that capture is fire-and-forget and lossless, no episode is silently dropped, no language model touches the write path, and at-least-once redelivery can never duplicate a memory

  Background:
    Given the relay consumer is subscribed to the MEMORY stream as a durable consumer
    And the typed payload registry and deterministic writer are available
    And the embedding service and store are available

  # ───────────────────────── Key examples ────────────────────────────

  # Why: Core structured path — content_format json dispatches through the registry to the writer
  @task:TASK-RLY-005
  @key-example @smoke
  Scenario: A structured JSON episode is dispatched through the registry to the deterministic writer
    Given a MemoryEpisodeV1 whose content format is structured JSON for a known payload type
    When the consumer receives the episode
    Then the payload should be dispatched through the registry to the deterministic writer
    And a typed record for that payload should exist in the project namespace
    And the episode should be acknowledged

  # Why: Core prose path — markdown is chunked heading-aware, embedded, and stored as chunks
  @task:TASK-RLY-005
  @key-example @smoke
  Scenario: A markdown episode is chunked, embedded, and stored as chunks under the project chunk namespace
    Given a MemoryEpisodeV1 whose content format is markdown for project "guardkit"
    When the consumer receives the episode
    Then the body should be split into heading-aware chunks
    And each chunk should be embedded and stored under the project chunk namespace
    And the episode should be acknowledged

  # Why: Plain text takes the same chunk+embed path as markdown (RD-7 — unstructured = chunk+embed)
  @task:TASK-RLY-005
  @key-example
  Scenario: A plain text episode is chunked and embedded on the same path as markdown
    Given a MemoryEpisodeV1 whose content format is plain text
    When the consumer receives the episode
    Then the body should be chunked and embedded and stored as chunks
    And the episode should be acknowledged

  # Why: Content format is the routing key — it alone selects which write path runs
  @task:TASK-RLY-005
  @key-example @smoke
  Scenario Outline: The episode content format selects the write path
    Given a MemoryEpisodeV1 whose content format is "<format>"
    When the consumer receives the episode
    Then it should be processed by the "<path>" path

    Examples:
      | format   | path       |
      | json     | structured |
      | markdown | chunk      |
      | text     | chunk      |

  # Why: The headline acceptance criterion — a mixed batch produces typed records and chunks together
  @task:TASK-RLY-005
  @key-example @smoke
  Scenario: A mixed batch of structured and prose episodes yields typed records and chunks
    Given 3 structured JSON episodes for known payload types
    And 2 markdown episodes
    When the consumer processes all five episodes
    Then 3 typed records should exist
    And the markdown episodes should produce one or more chunks
    And all five episodes should be acknowledged

  # Why: Ack-after-commit is what makes at-least-once delivery safe — nothing is acked until it is durable
  # [ASSUMPTION: confidence=medium] An episode is acknowledged only after its write has durably committed to the store
  @task:TASK-RLY-006
  @key-example @smoke
  Scenario: An episode is acknowledged only after it is durably stored
    Given a MemoryEpisodeV1 ready to process
    When the consumer processes the episode
    Then the episode should not be acknowledged before its write has committed
    And it should be acknowledged once the write has committed

  # Why: Provenance must survive ingestion — every chunk traces back to its source episode
  @task:TASK-RLY-004
  @key-example
  Scenario: Each stored chunk carries the source reference and project of its originating episode
    Given a markdown episode for project "guardkit" with a known source reference
    When the consumer processes the episode
    Then every resulting chunk should record that source reference
    And every resulting chunk should be stored in the "guardkit" project namespace

  # ───────────────────── Boundary conditions ─────────────────────────

  # Why: Chunk-count boundary — content below, at, and above one chunk produces the expected chunk counts
  # [ASSUMPTION: confidence=medium] Target chunk size is approximately 1000 tokens (OD-1 starting value)
  @task:TASK-RLY-003
  @boundary
  Scenario Outline: Prose content produces a chunk count proportional to its size
    Given a markdown episode whose body is <size>
    When the consumer processes the episode
    Then it should produce <chunks> chunk(s)

    Examples:
      | size                 | chunks   |
      | well under one chunk | 1        |
      | exactly one chunk    | 1        |
      | just over one chunk  | 2        |
      | several chunks long  | multiple |

  # Why: Just-inside overlap — adjacent chunks must share overlapping content so meaning is not severed at a cut
  # [ASSUMPTION: confidence=medium] Adjacent chunks overlap by approximately 15% of chunk size (OD-1 starting value)
  @task:TASK-RLY-003
  @boundary
  Scenario: Adjacent chunks of a multi-chunk document share overlapping content
    Given a markdown episode long enough to span at least two chunks
    When the consumer processes the episode
    Then each chunk after the first should begin with content overlapping the previous chunk

  # Why: Heading awareness — a chunk boundary should prefer a heading break over splitting mid-section
  @task:TASK-RLY-003
  @boundary
  Scenario: Chunk boundaries prefer heading breaks over splitting a section mid-sentence
    Given a markdown episode with multiple headings and sections
    When the consumer processes the episode
    Then chunk boundaries should fall at heading breaks where possible
    And no heading line should be separated from the section it introduces

  # Why: Empty-body boundary — an episode with no usable content produces no chunks but is still accounted for
  # [ASSUMPTION: confidence=low] An episode whose body is empty or whitespace-only produces zero chunks and is acknowledged, not parked
  @task:TASK-RLY-005
  @boundary
  Scenario: A prose episode with an empty body produces no chunks and is acknowledged
    Given a markdown episode whose body is empty
    When the consumer processes the episode
    Then no chunk should be created
    And the episode should be acknowledged

  # Why: Just-inside redelivery — a transient failure short of the delivery limit is retried, not parked
  # [ASSUMPTION: confidence=low] The consumer parks an episode only after max_deliver attempts; max_deliver is 5
  @task:TASK-RLY-006
  @boundary
  Scenario: An episode that has failed fewer than the delivery limit is redelivered, not parked
    Given an episode that has been delivered 4 times without being acknowledged
    When it is delivered once more and processing succeeds
    Then the episode should be acknowledged
    And it should not be sent to the dead-letter subject

  # Why: Just-outside redelivery — the attempt that reaches the limit parks the episode
  @task:TASK-RLY-006
  @boundary @negative
  Scenario: An episode that reaches the delivery limit is parked on the dead-letter subject
    Given an episode that keeps failing on every delivery
    When it has been delivered the maximum number of times
    Then the episode should be sent to the dead-letter subject
    And the consumer should continue processing other episodes

  # ─────────────────────── Negative cases ────────────────────────────

  # Why: A poison body that can never parse is parked — retrying it forever would stall the stream
  # [ASSUMPTION: confidence=medium] A body that cannot be parsed is a deterministic (poison) failure routed to the dead-letter subject
  @task:TASK-RLY-005
  @negative
  Scenario: An episode whose body cannot be parsed is routed to the dead-letter subject
    Given a MemoryEpisodeV1 whose body is not parseable for its declared content format
    When the consumer receives the episode
    Then the episode should be routed to the dead-letter subject with a recorded reason
    And the consumer should continue processing other episodes

  # Why: An unknown payload type cannot be dispatched — registry has no silent fallback (FEAT-MEM-02 contract)
  @task:TASK-RLY-005
  @negative
  Scenario: A structured episode declaring an unknown payload type is parked
    Given a structured JSON episode declaring a payload type the registry does not know
    When the consumer receives the episode
    Then no record should be written
    And the episode should be routed to the dead-letter subject naming the unknown payload type

  # Why: A structured body missing a required field is a deterministic validation failure, never a write
  @task:TASK-RLY-005
  @negative
  Scenario: A structured episode that fails payload validation is parked without a write
    Given a structured JSON episode missing a field its payload type requires
    When the consumer receives the episode
    Then no record should be written
    And the episode should be routed to the dead-letter subject

  # Why: An unrecognized content format has no path — it must be parked, not guessed at
  # [ASSUMPTION: confidence=low] The only recognized content formats are json, markdown, and text
  @task:TASK-RLY-005
  @negative
  Scenario: An episode with an unrecognized content format is parked
    Given a MemoryEpisodeV1 whose content format is "yaml"
    When the consumer receives the episode
    Then no record or chunk should be created
    And the episode should be routed to the dead-letter subject

  # Why: Underscores-everywhere — a hyphenated project is rejected before any write, on both paths
  @task:TASK-RLY-005
  @negative
  Scenario: An episode whose project contains a hyphen is parked before any write
    Given a MemoryEpisodeV1 for project "guard-kit"
    When the consumer receives the episode
    Then no record or chunk should be created
    And the episode should be routed to the dead-letter subject

  # Why: Transient failures must be retried, never parked — distinguishing them from poison is the core ack/nak decision
  # [ASSUMPTION: confidence=medium] A transient downstream failure causes a negative-acknowledge and redelivery, not dead-lettering
  @task:TASK-RLY-005
  @negative
  Scenario: A transient downstream failure causes redelivery rather than dead-lettering
    Given the embedding service is temporarily unavailable
    When the consumer processes a markdown episode
    Then the episode should be negatively acknowledged for redelivery
    And the episode should not be sent to the dead-letter subject

  # ──────────────────────── Edge cases ───────────────────────────────

  # Why: AC — redelivery of an acked structured episode changes nothing (writer natural-key upsert is the ledger)
  @task:TASK-RLY-005
  @edge-case @regression
  Scenario: Redelivery of an already-stored structured episode changes nothing
    Given a structured episode that has already been processed and stored
    When the same episode is delivered again
    Then only one record should exist for that payload's natural key
    And the redelivery should leave the stored record unchanged

  # Why: AC — redelivery of an acked prose episode produces no duplicate chunks (episode_id keys are the ledger)
  # [ASSUMPTION: confidence=medium] Chunk identity is derived from the episode_id plus chunk position, making re-chunking idempotent
  @task:TASK-RLY-005
  @edge-case @regression
  Scenario: Redelivery of an already-chunked prose episode creates no duplicate chunks
    Given a markdown episode that has already been chunked and stored
    When the same episode is delivered again
    Then the chunk set for that episode should be identical to before
    And no duplicate chunk should be created

  # Why: AC — a poison episode is parked after the delivery limit and the consumer keeps going
  @task:TASK-RLY-006
  @edge-case @regression
  Scenario: A poison episode is parked and the consumer keeps processing the episodes behind it
    Given a poison episode at the head of the stream followed by valid episodes
    When the consumer works through the stream
    Then the poison episode should end up on the dead-letter subject
    And every valid episode behind it should be processed and acknowledged

  # Why: The at-least-once seam — a crash after commit but before ack must redeliver to an idempotent no-op
  @task:TASK-RLY-005
  @edge-case @regression
  Scenario: A crash after the write commits but before the ack results in an idempotent redelivery
    Given an episode whose write commits but whose acknowledgement is lost to a crash
    When the episode is redelivered after restart
    Then no second record or duplicate chunk should be created
    And the episode should then be acknowledged

  # Why: AC — no language model touches the ingestion path (the whole thesis, as an enforceable check)
  @task:TASK-RLY-005
  @edge-case @regression @negative
  Scenario: Ingesting episodes makes no language-model or chat-completion calls
    Given a batch of structured and prose episodes
    When the consumer ingests the entire batch
    Then no language-model or chat-completion request should be made on the write path

  # Why: Structured and prose episodes are independent — one path failing must not block the other
  @task:TASK-RLY-005
  @edge-case
  Scenario: A failing prose episode does not block structured episodes interleaved with it
    Given a stream interleaving a failing markdown episode with valid structured episodes
    When the consumer processes the stream
    Then the structured episodes should be stored and acknowledged
    And the failing markdown episode should be handled by its own ack or dead-letter decision

  # Why: Chunk-write atomicity — a mid-document failure must not leave a half-chunked episode behind
  # [ASSUMPTION: confidence=low] A prose episode's chunks are committed so that a partial failure leaves no incomplete chunk set for that episode_id
  @task:TASK-RLY-005
  @edge-case
  Scenario: A prose episode interrupted partway through chunking leaves no partial chunk set
    Given a markdown episode whose chunk writes fail partway through
    When the episode is redelivered and reprocessed
    Then the stored chunk set for that episode should be complete
    And no orphaned partial chunks should remain for that episode

  # ──────────────── Edge cases — security / injection ─────────────────

  # Why: Memory content is data, never instructions — hostile prose must round-trip inert through chunking
  @task:TASK-RLY-005
  @edge-case @negative
  Scenario: A prose episode containing injection-shaped text is chunked and stored verbatim and stays inert
    Given a markdown episode whose body contains database commands and prompt-injection text
    When the consumer chunks and stores the episode
    Then the stored chunks should contain that text byte-for-byte as written
    And no command in the content should be executed
    And no other record or namespace should be affected

  # Why: Chunk identity is derived data — delimiter or path text in episode metadata must not forge identity elsewhere
  @task:TASK-RLY-004
  @edge-case @negative
  Scenario: An episode whose identifiers carry delimiter or path text cannot forge a chunk identity in another namespace
    Given a markdown episode for project "guardkit" whose episode reference carries key-delimiter or path-shaped text
    When the consumer processes the episode
    Then every resulting chunk should be confined to the "guardkit" chunk namespace
    And no chunk should be written outside that project namespace

  # ──────────────────── Edge cases — concurrency ──────────────────────

  # Why: At-least-once delivery can race the same episode against itself — both deliveries must converge to one outcome
  @task:TASK-RLY-005
  @edge-case @regression
  Scenario: The same episode delivered twice concurrently converges to a single stored outcome
    Given the same episode delivered twice at the same time under at-least-once delivery
    When the consumer processes both deliveries concurrently
    Then exactly one record or one chunk set should exist for that episode
    And no duplicate should ever be created

  # Why: Concurrent episodes for one project must not cross-contaminate each other's writes
  @task:TASK-RLY-005
  @edge-case
  Scenario: Two different episodes for the same project processed concurrently write independently
    Given two different episodes for project "guardkit" arriving at the same time
    When the consumer processes both concurrently
    Then each episode should produce its own record or chunk set
    And neither episode's content should appear in the other's stored output

  # ─────────────── Edge cases — integration boundaries ────────────────

  # Why: Zero capture loss is the founding invariant — a store outage must redeliver, never silently drop in-flight work
  @task:TASK-RLY-006
  @edge-case @negative @regression
  Scenario: A store outage mid-batch redelivers in-flight episodes rather than losing them
    Given a batch of episodes being processed when the store becomes unreachable
    When the in-flight writes fail
    Then the affected episodes should be negatively acknowledged for redelivery
    And no in-flight episode should be acknowledged as stored
    And every episode should later be either stored or recorded on the dead-letter subject

  # Why: A wrong-dimension embedding must fail loudly, never persist a malformed chunk
  @task:TASK-RLY-004
  @edge-case @negative
  Scenario: An embedding with the wrong dimensions fails the chunk write and parks the episode
    Given the store is configured for its fixed embedding dimensions
    When the consumer stores a chunk whose embedding has a different number of dimensions
    Then the chunk write should fail with a dimension mismatch
    And no malformed chunk should be stored
