# Generated by /feature-spec
# Feature: System Architecture & Design Commands
# Stack: python
# Assumptions: 12 (see system-arch-design-commands_assumptions.yaml)
# Generated: 2026-03-01T00:00:00Z

@system-arch-design
Feature: System Architecture & Design Commands
  As a developer using GuardKit
  I want to define system-level architecture and design decisions before feature work begins
  So that downstream commands (/system-plan, /feature-spec, /feature-plan) are grounded in explicit architectural context rather than assumptions

  Background:
    Given I have a project with GuardKit initialised
    And the Graphiti knowledge graph is available

  # ━━ GROUP A: Key Examples ━━

  # Why: Core entry point — a developer runs /system-arch on a new project for the first time
  @key-example @smoke
  Scenario: Running /system-arch on a project with no existing architecture context
    Given no architecture context exists in Graphiti
    When I run /system-arch for my project
    Then the command should detect setup mode automatically
    And I should be presented with structured questions across domain, structure, decisions, and infrastructure categories
    And each category should have a checkpoint where I can continue, revise, skip, or capture an ADR

  # Why: Core output — verifies the command produces all mandatory artefacts
  @key-example @smoke
  Scenario: /system-arch generates all mandatory output artefacts
    Given I have completed the /system-arch interactive session
    When the command generates output artefacts
    Then a domain model document should be created
    And architectural decision records should be created for each decision made
    And a C4 Context diagram should be generated in Mermaid format
    And a C4 Container diagram should be generated in Mermaid format
    And an assumptions manifest should be created in YAML format
    And an architecture summary should be created for /system-plan consumption

  # Why: Core downstream value — /system-plan benefits from seeded architecture
  @key-example @smoke
  Scenario: /system-plan reads architecture context seeded by /system-arch
    Given I have completed /system-arch and all artefacts are seeded in Graphiti
    When I run /system-plan for a new feature
    Then the planning session should already know the domain structure
    And the planning session should reference the relevant bounded contexts or modules
    And the planning session should surface relevant ADRs as constraints
    And I should not need to re-explain the architecture

  # Why: Core design command — verifies /system-design reads from /system-arch output
  @key-example
  Scenario: /system-design depends on /system-arch having been run
    Given /system-arch has been completed and artefacts are in Graphiti
    When I run /system-design
    Then the command should read bounded contexts and structural decisions from Graphiti
    And it should propose API contracts per bounded context or module
    And it should design multi-protocol surfaces for each consumer type

  # Why: Core design output — verifies contract artefacts
  @key-example
  Scenario: /system-design generates API contract and data model artefacts
    Given I have completed the /system-design interactive session
    When the command generates output artefacts
    Then API contracts per bounded context should be created
    And an OpenAPI 3.x specification should be generated
    And data model definitions with core entities and relationships should be created
    And C4 Component diagrams should be generated for designed containers
    And design decision records should be created
    And all artefacts should be seeded into Graphiti

  # Why: Validates the full pipeline from arch through to feature spec
  @key-example
  Scenario: /feature-spec references real endpoints after /system-design has run
    Given /system-arch and /system-design have been completed
    And API contracts and domain entities are seeded in Graphiti
    When I run /feature-spec for a feature within a defined bounded context
    Then the generated Gherkin scenarios should reference real domain entities from the data model
    And assumption confidence should be higher for values derivable from the API contracts

  # Why: C4 diagrams are a mandatory verification gate, not optional output
  @key-example
  Scenario: C4 diagrams are presented as a mandatory review gate
    Given /system-arch has generated C4 Context and Container diagrams
    When the diagrams are presented to me
    Then the command should pause and require my explicit approval of each diagram
    And I should not be able to proceed to output generation without approving the diagrams

  # Why: Stack agnosticism — the command must not assume any technology
  @key-example
  Scenario: /system-arch asks clarifying questions about structural pattern and technology stack
    Given I am running /system-arch in setup mode
    When the command reaches the structural and technology decision categories
    Then I should be asked to choose a structural pattern with trade-offs surfaced
    And I should be asked to choose a technology stack
    And both decisions should be recorded as ADRs with rationale and alternatives considered

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Just-inside boundary — minimal viable architecture (single module, no external systems)
  @boundary
  Scenario: Running /system-arch on a minimal single-module project
    Given my project has only one module and no external integrations
    When I complete the /system-arch session
    Then the architecture should be captured with a single module
    And the C4 Context diagram should show the system with only user actors
    And the Container diagram should show one container
    And the output should still be valid and complete

  # Why: Just-inside boundary — maximum practical complexity
  @boundary
  Scenario: Running /system-arch on a project with many bounded contexts
    Given my project has 10 bounded contexts with complex inter-context relationships
    When I complete the /system-arch session
    Then all 10 bounded contexts should be captured with their relationships
    And domain events between contexts should be recorded
    # [ASSUMPTION: confidence=medium] C4 diagrams are split into sub-diagrams when they exceed 30 nodes
    And the C4 diagrams should be split into sub-diagrams if they exceed 30 nodes

  # Why: Just-outside boundary — /system-design without /system-arch
  @boundary @negative
  Scenario: Running /system-design before /system-arch
    Given no architecture context exists in Graphiti
    When I attempt to run /system-design
    Then I should be informed that /system-arch must be run first
    And the command should offer to run /system-arch instead

  # [ASSUMPTION: confidence=medium] C4 diagrams are split into sub-diagrams when they exceed 30 nodes
  # Why: Boundary on diagram size — diagrams must stay under 30 nodes
  @boundary
  Scenario: C4 diagram with exactly 30 nodes renders as a single diagram
    Given the architecture has exactly 30 elements including actors and external systems
    When the C4 Context diagram is generated
    Then it should render as a single diagram without splitting

  # Why: Just-outside diagram size boundary
  @boundary
  Scenario: C4 diagram with more than 30 nodes is split into sub-diagrams
    Given the architecture has 35 elements including actors and external systems
    When the C4 Context diagram is generated
    Then it should be split into sub-diagrams with clear cross-references

  # Why: Boundary on ADR numbering when ADRs already exist
  @boundary
  Scenario: ADR numbering continues from existing ADRs
    Given 5 ADRs already exist in the project
    When I capture a new ADR during /system-arch
    Then the new ADR should be numbered ADR-006
    And existing ADRs should not be renumbered or modified

  # ━━ GROUP C: Negative Cases ━━

  # Why: Graphiti unavailable — must degrade gracefully, not crash
  @negative
  Scenario: Running /system-arch when Graphiti is unavailable
    Given the Graphiti knowledge graph is not available
    When I run /system-arch
    Then I should be warned that persistence is unavailable
    And I should be offered the choice to continue without persistence
    And if I continue, markdown artefacts should still be generated
    And the output should note that context was not seeded into Graphiti

  # Why: User cancels mid-session — partial work must be preserved
  @negative
  Scenario: Cancelling the /system-arch session after completing some categories
    Given I have completed categories 1 through 3 of the /system-arch session
    When I choose to skip remaining categories at a checkpoint
    Then the completed categories should be persisted to Graphiti
    And markdown artefacts should be generated for the completed categories
    And I should be informed which categories were skipped
    And I should be told to run /system-arch again to complete

  # Why: Empty answers — placeholder behaviour
  @negative
  Scenario: Providing empty answers to /system-arch questions
    Given I am in the /system-arch interactive session
    When I provide an empty answer to a question
    Then a placeholder value should be used
    And I should be warned that the answer was empty
    And the session should continue without blocking

  # Why: Invalid structural pattern choice
  @negative
  Scenario: Selecting an unrecognised structural pattern
    Given I am asked to choose a structural pattern
    When I enter an unrecognised option
    Then I should be shown the valid options again
    And the session should not proceed until a valid choice is made

  # Why: /system-design run against stale /system-arch context
  @negative
  Scenario: /system-design detects that /system-arch context has been superseded
    Given /system-arch was run and architecture decisions were seeded
    And an /arch-refine has since superseded some of those decisions
    When I run /system-design
    Then the command should use the latest (superseded) versions of decisions
    And I should be informed which decisions have been updated since the last /system-design run

  # Why: No description provided
  @negative
  Scenario: Running /system-arch without a project description
    Given I have not provided a project description
    When I run /system-arch
    Then I should see a usage error with syntax examples
    And the command should not proceed

  # ━━ GROUP D: Edge Cases ━━

  # Why: Refinement with temporal superseding — core of /arch-refine
  @edge-case
  Scenario: /arch-refine supersedes an existing ADR with impact analysis
    Given ADR-003 states "Use synchronous HTTP for all inter-service communication"
    And feature specs reference this decision
    When I run /arch-refine to change to asynchronous communication
    Then the command should show the impact on downstream artefacts
    And I should see which feature specs may reference stale contracts
    # [ASSUMPTION: confidence=low] Temporal superseding queries prior node by ADR ID and creates a "supersedes" relationship
    And upon confirmation, a new ADR should be created that supersedes ADR-003
    And the prior ADR should remain queryable in Graphiti with its history

  # Why: Multi-consumer API design — the system must serve web clients, agents, and internal flows
  @edge-case
  Scenario: /system-design explicitly designs for multiple consumer types
    Given the architecture identifies three consumer types: web clients, agents, and internal flows
    When I complete the /system-design session
    Then separate API surface designs should exist for each consumer type
    And REST or GraphQL contracts should be generated for web clients
    # [ASSUMPTION: confidence=low] Agent protocol scope includes MCP, Google A2A, and ACP
    And MCP tool definitions or A2A task schemas should be generated for agent consumers
    And internal event contracts should be generated for internal flows

  # Why: Disambiguation in /arch-refine via semantic search
  @edge-case
  Scenario: /arch-refine resolves ambiguous references via semantic search and confirmation
    Given the architecture has multiple areas that share the term "user"
    When I say "I need to change the user model"
    # [ASSUMPTION: confidence=medium] Semantic search results are capped at 3-5 matches
    Then the command should search Graphiti semantically for matching artefacts
    And it should present the top 3-5 matches grouped by relevance
    And I should confirm which artefacts I mean before any changes are applied

  # Why: /design-refine cascade — design change should flag downstream staleness
  @edge-case
  Scenario: /design-refine flags stale feature specs after an API contract change
    Given a /feature-spec has been generated that references an API contract
    When I run /design-refine and change that API contract
    Then the command should flag the affected feature specs as potentially stale
    And I should be given the choice to re-run /feature-spec on those areas or accept the delta

  # Why: Pipeline ordering enforcement — verifies the intended upstream-to-downstream flow
  @edge-case
  Scenario: The command pipeline enforces the correct execution order
    Given the intended pipeline is /system-arch then /system-design then /system-plan then /feature-spec
    When I attempt to run a downstream command before its upstream dependency
    Then I should be informed of the recommended execution order
    And the downstream command should offer to run the missing upstream command first

  # ━━ EDGE CASE EXPANSION: Security ━━

  # Why: Graphiti seeding must sanitise input — ADR rationale is free-text and could contain injection attempts
  @edge-case
  Scenario: Graphiti seeding handles adversarial content in ADR rationale
    Given I am capturing an ADR during /system-arch
    When I provide rationale text containing script tags, SQL fragments, or control characters
    Then the content should be stored safely without executing or corrupting the knowledge graph
    And the ADR should be retrievable with its original content intact

  # Why: Semantic search in /arch-refine could be manipulated to match unintended artefacts
  @edge-case
  Scenario: Semantic search in /arch-refine does not match unrelated artefacts from adversarial queries
    Given the architecture has bounded contexts for "Payment" and "User Profile"
    When I run /arch-refine with an intentionally vague query like "everything"
    Then the results should be capped at the top 3-5 most relevant matches
    And I should be asked to confirm before any artefacts are modified
    And no artefacts should be changed without explicit confirmation

  # ━━ EDGE CASE EXPANSION: Concurrency ━━

  # Why: Two developers on the same project could run /system-arch at the same time, creating conflicting state
  @edge-case
  Scenario: Concurrent /system-arch sessions on the same project do not corrupt Graphiti state
    Given two developers run /system-arch simultaneously on the same project
    When both sessions attempt to seed architecture context into Graphiti
    Then the knowledge graph should not contain duplicate or contradictory entities
    And the last-written values should take precedence
    And both sessions should complete without error

  # Why: /arch-refine could change context that /feature-spec is actively reading mid-session
  @edge-case
  Scenario: /feature-spec handles architecture context changing during its session
    Given /feature-spec is mid-session and has loaded architecture context from Graphiti
    And /arch-refine completes and supersedes a decision that /feature-spec already read
    When /feature-spec generates its output
    Then the generated scenarios should reflect the context as it was when the session started
    And the output summary should not silently incorporate the mid-session change

  # ━━ EDGE CASE EXPANSION: Data Integrity ━━

  # Why: Partial seeding failure leaves Graphiti in an inconsistent state — downstream commands see incomplete architecture
  @edge-case
  Scenario: Partial Graphiti seeding failure is detected and reported
    Given I have completed the /system-arch interactive session
    When Graphiti seeding fails after persisting categories 1-3 but before categories 4-6
    Then I should be informed which categories were successfully persisted
    And I should be informed which categories failed to persist
    And the generated markdown artefacts should still be complete
    And I should be advised to retry seeding for the failed categories

  # Why: /system-design might generate contracts that violate constraints recorded in ADRs
  @edge-case
  Scenario: /system-design detects contradictions between proposed contracts and existing ADRs
    Given an ADR states "All inter-service communication must be synchronous HTTP"
    When /system-design proposes an event-driven contract between two bounded contexts
    Then the contradiction should be flagged before the contract is finalised
    And I should be offered the choice to revise the contract or supersede the ADR

  # ━━ EDGE CASE EXPANSION: Integration Boundaries ━━

  # Why: Graphiti connection loss mid-session — must not lose interactive work already captured
  @edge-case
  Scenario: /system-arch preserves session progress when Graphiti connection drops mid-session
    Given I am mid-way through the /system-arch interactive session
    And categories 1-3 have been persisted to Graphiti
    When the Graphiti connection drops before category 4 is persisted
    Then the interactive session should continue without crashing
    And I should be warned that persistence is no longer available
    And all remaining categories should still be captured in markdown artefacts
    And I should be advised to re-seed the unpersisted categories when Graphiti is restored

  # Why: MCP design-patterns server could return recommendations that contradict the architecture already decided
  @edge-case
  Scenario: MCP design-patterns recommendations that contradict architecture decisions are flagged
    Given /system-arch has recorded a decision to use a modular monolith pattern
    When the MCP design-patterns server recommends a microservices pattern for a component
    Then the contradiction with the existing ADR should be surfaced
    And the recommendation should be presented as an option, not applied automatically
    And I should decide whether to adopt the recommendation or retain the existing decision
