# Generated by /feature-spec
# Feature: Architecture Knowledge Query Tool
# Stack: python
# Assumptions: 12 (see architecture-knowledge-query-tool_assumptions.yaml)
# Generated: 2026-05-05T00:00:00Z

@architecture-knowledge-query @feat-RAG-03
Feature: Architecture Knowledge Query Tool
  As a specialist agent operator
  I want the Player agent to query the architecture-books knowledge index
  for paragraph-level extracts grounded in Evans, Vernon, Ousterhout, Ford,
  Kleppmann, Skelton & Pais, Tornhill, Hohpe, Harmel-Law et al.
  So that the Player can ground architectural claims in cited source material
  rather than producing verbose generic AI prose

  Background:
    Given the architect agent project is initialised
    And a valid LLM client is available
    And the architect role configuration is loaded

  # ━━ GROUP A: Key Examples ━━

  # Why: Core capability — Player gains the new tool when knowledge_index is enabled
  # [ASSUMPTION: confidence=high] When enabled, Player tool inventory is exactly {read_product_docs, web_search, graphiti_query, architecture_knowledge_query}
  @task:TASK-AKQT-004
  @key-example @smoke
  Scenario: Player tool inventory includes architecture_knowledge_query when knowledge_index is enabled
    Given knowledge_index is enabled in the role configuration
    And the architect role configuration lists "architecture_knowledge_query" in player.tools
    When I create a Player agent
    Then the Player's tool inventory should include "architecture_knowledge_query"
    And the Player's tool inventory should include "read_product_docs"
    And the Player's tool inventory should include "graphiti_query"

  # Why: Tool separation (D5 invariant) — Coach remains at zero tools regardless of knowledge_index
  # [ASSUMPTION: confidence=high] Coach inventory is always the empty set, independent of knowledge_index state
  @task:TASK-AKQT-004
  @key-example @smoke
  Scenario: Coach agent has zero tools when knowledge_index is enabled
    Given knowledge_index is enabled in the role configuration
    When I create a Coach agent
    Then the Coach's tool inventory should be exactly the empty set

  # Why: Core retrieval — Player can search by natural language and receive cited extracts
  # [ASSUMPTION: confidence=high] Citation format is "[source_book: topic]" per feature description
  @task:TASK-AKQT-001
  @key-example @smoke
  Scenario: architecture_knowledge_query returns cited extracts for a valid query
    Given the architecture knowledge index is available
    And the index contains extracts on bounded contexts from Evans
    When the Player invokes architecture_knowledge_query with query "bounded context boundaries"
    Then the result should contain paragraph-level extracts
    And each extract should be prefixed with a citation in the form "[source_book: topic]"
    And the citation should reference a known architecture book

  # Why: Cross-book grounding — claims should be traceable to the specific book that supplied them
  @task:TASK-AKQT-001
  @key-example
  Scenario: Result citations name the source book for each extract
    Given the architecture knowledge index is available
    And the index contains extracts from "Domain-Driven Design" and "Building Evolutionary Architectures"
    When the Player invokes architecture_knowledge_query with query "fitness functions and ubiquitous language"
    Then the result should include at least one extract cited from "Domain-Driven Design"
    And the result should include at least one extract cited from "Building Evolutionary Architectures"

  # Why: Filter by dimension — narrows retrieval to one of the dataset-factory dimensions
  @task:TASK-AKQT-001
  @key-example
  Scenario: Filtering by dimension narrows the result set
    Given the architecture knowledge index is available
    And the index contains extracts across multiple dimensions
    When the Player invokes architecture_knowledge_query with query "team topologies" and dimension "organisational"
    Then every returned extract should originate from the "organisational" dimension
    And no extract should originate from a different dimension

  # Why: Filter by source_book — lets the Player ground a claim against a specific author
  @task:TASK-AKQT-001
  @key-example
  Scenario: Filtering by source_book restricts results to that book
    Given the architecture knowledge index is available
    And the index contains extracts from multiple books
    When the Player invokes architecture_knowledge_query with query "stream-aligned teams" and source_book "Team Topologies"
    Then every returned extract should be cited as "[Team Topologies: ...]"
    And no extract from another book should appear

  # Why: Read-only retrieval — the tool may not mutate the index
  @task:TASK-AKQT-001
  @key-example
  Scenario: architecture_knowledge_query is read-only
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query
    Then the tool should provide no mechanism to add, modify, or delete extracts
    And the tool should provide no mechanism to overwrite the collection

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Just-inside boundary — query at exactly the configured max_results limit
  # [ASSUMPTION: confidence=high] Default max_results is 8 per feature description
  @task:TASK-AKQT-001
  @boundary
  Scenario Outline: Query returns up to the specified max_results limit
    Given the architecture knowledge index is available
    And the index contains 20 relevant extracts for the query
    When the Player invokes architecture_knowledge_query with query "modularity" and max_results <limit>
    Then exactly <expected> extracts should be returned

    Examples:
      | limit | expected |
      | 1     | 1        |
      | 8     | 8        |
      | 20    | 20       |

  # Why: Just-outside boundary — requesting more results than exist returns all available
  @task:TASK-AKQT-001
  @boundary
  Scenario: Query requesting more extracts than available returns all available
    Given the architecture knowledge index is available
    And the index contains 3 extracts relevant to the query
    When the Player invokes architecture_knowledge_query with query "phantom architectural concept" and max_results 8
    Then exactly 3 extracts should be returned
    And no padding or placeholder extracts should be added

  # Why: Default applied when max_results is not provided
  @task:TASK-AKQT-001
  @boundary
  Scenario: max_results defaults to 8 when omitted by the caller
    Given the architecture knowledge index is available
    And the index contains 20 relevant extracts for the query
    When the Player invokes architecture_knowledge_query with query "domain events" and no max_results argument
    Then exactly 8 extracts should be returned

  # Why: Boundary — an upper clamp prevents overly large retrievals
  # [ASSUMPTION: confidence=medium] Maximum results upper bound is 50, matching graphiti_query
  @task:TASK-AKQT-001
  @boundary @negative
  Scenario: max_results exceeding the upper bound is clamped
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query with query "modularity" and max_results 100
    Then the effective max_results should be clamped to 50
    And the result should not exceed 50 extracts

  # Why: Boundary — minimum query length to prevent overly broad searches
  # [ASSUMPTION: confidence=medium] Minimum query length is 3 characters, matching graphiti_query
  @task:TASK-AKQT-001
  @boundary @negative
  Scenario: Query shorter than the minimum length is rejected
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query with query "ab"
    Then the tool should return an error indicating the query is too short

  # ━━ GROUP C: Negative Cases ━━

  # Why: Graceful degradation — Chroma unreachable does not fail the session
  # [ASSUMPTION: confidence=high] Exact degradation string is "Knowledge index unavailable — proceed without RAG context."
  @task:TASK-AKQT-001
  @negative @smoke
  Scenario: architecture_knowledge_query degrades gracefully when ChromaDB is unreachable
    Given the architecture knowledge index is unreachable
    When the Player invokes architecture_knowledge_query with query "modular monolith trade-offs"
    Then the tool should return the string "Knowledge index unavailable — proceed without RAG context."
    And no unhandled exception should be raised

  # Why: Graceful degradation — collection missing on a reachable host
  @task:TASK-AKQT-001
  @negative
  Scenario: architecture_knowledge_query degrades gracefully when the collection is missing
    Given the architecture knowledge index host is reachable
    But the "architect-knowledge-v1" collection does not exist
    When the Player invokes architecture_knowledge_query with query "evolutionary architecture"
    Then the tool should return the string "Knowledge index unavailable — proceed without RAG context."
    And no unhandled exception should be raised

  # Why: Lazy-import contract — chromadb must not be required at module import time
  # [ASSUMPTION: confidence=high] chromadb is a lazy-imported optional dependency under the rag extra
  @task:TASK-AKQT-001
  @negative
  Scenario: Tool module imports successfully without chromadb installed
    Given the chromadb package is not installed
    When the application imports specialist_agent.tools.architecture_knowledge
    Then the import should succeed without raising
    And invoking architecture_knowledge_query should return the unavailability string

  # Why: Empty query string is invalid
  # [ASSUMPTION: confidence=medium] Empty query is rejected with a clear error message
  @task:TASK-AKQT-001
  @negative
  Scenario: Empty query string is rejected with a clear message
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query with query ""
    Then the tool should return an error indicating the query must not be empty

  # Why: Tool gating — when knowledge_index is disabled the Player must not have the tool
  @task:TASK-AKQT-004
  @negative
  Scenario: Player tool inventory excludes architecture_knowledge_query when knowledge_index is disabled
    Given knowledge_index is disabled in the role configuration
    When I create a Player agent
    Then the Player's tool inventory should not include "architecture_knowledge_query"
    And factory tool-inventory assertion should still pass

  # Why: Filter validation — an unknown dimension should not silently leak unrelated extracts
  @task:TASK-AKQT-001
  @negative
  Scenario: Filtering by an unknown dimension returns an empty result set
    Given the architecture knowledge index is available
    And the index contains no extracts tagged with dimension "fictional-dimension"
    When the Player invokes architecture_knowledge_query with query "anything" and dimension "fictional-dimension"
    Then the result should be the empty result set
    And no extracts from other dimensions should be returned

  # ━━ GROUP D: Edge Cases ━━

  # Why: Combined filters — applying both dimension and source_book together
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Combined dimension and source_book filters are applied together
    Given the architecture knowledge index is available
    And the index contains extracts across dimensions and books
    When the Player invokes architecture_knowledge_query with query "team boundaries" and dimension "organisational" and source_book "Team Topologies"
    Then every returned extract should originate from the "organisational" dimension
    And every returned extract should be cited as "[Team Topologies: ...]"

  # Why: Plural metadata field — source_books is stored as a list per metadata schema
  @task:TASK-AKQT-001
  @edge-case
  Scenario: source_book filter matches an extract whose metadata source_books list contains that book
    Given the architecture knowledge index is available
    And an extract has metadata source_books ["Domain-Driven Design", "Implementing Domain-Driven Design"]
    When the Player invokes architecture_knowledge_query with query "aggregate root design" and source_book "Implementing Domain-Driven Design"
    Then that extract should be included in the result

  # Why: Citation formatting — extracts must always carry a citation prefix
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Every returned extract is prefixed with a citation line
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query with query "consistency boundaries"
    Then every returned extract should begin with a "[source_book: topic]" citation line
    And no extract should be returned without a citation

  # Why: Independence — multiple invocations in one session must not share state across queries
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Multiple queries in the same session return independent results
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query with query "domain events"
    And then invokes architecture_knowledge_query with query "team topologies"
    Then the first query should return domain-event extracts
    And the second query should return team-topology extracts
    And the results should be independent of each other

  # Why: Special characters — Unicode and punctuation in queries should not crash the tool
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Query with special characters is handled safely
    Given the architecture knowledge index is available
    When the Player invokes architecture_knowledge_query with query "Conway's law & socio-technical boundaries"
    Then the result should be returned without error
    And no parsing or filter-construction failure should occur

  # ━━ GROUP D (Extended): Security, Concurrency, Integration ━━

  # Why: Injection prevention — query text must not be interpretable as a Chroma mutation
  @task:TASK-AKQT-001
  @edge-case @security
  Scenario: Malicious query string cannot mutate the architecture knowledge collection
    Given the architecture knowledge index is available
    And the collection contains 100 extracts
    When the Player invokes architecture_knowledge_query with query "DROP COLLECTION; bounded contexts"
    Then the collection should still contain 100 extracts
    And the tool should return retrieval results or the empty result set
    And no collection mutations should have occurred

  # Why: Filter-injection prevention — crafted filter values must not bypass the where= clause
  @task:TASK-AKQT-001
  @edge-case @security
  Scenario: Crafted filter values cannot bypass dimension scoping
    Given the architecture knowledge index is available
    And the index contains extracts across multiple dimensions
    When the Player invokes architecture_knowledge_query with query "anything" and dimension "organisational' OR '1'='1"
    Then the tool should either reject the filter value or treat the entire string as a literal dimension value
    And no extracts from outside the literal dimension value should be returned

  # Why: Concurrent invocations — two Player sessions must not interfere on shared retrieval state
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Simultaneous queries from different Player sessions do not interfere
    Given the architecture knowledge index is available
    And two Player sessions are active concurrently
    When both sessions invoke architecture_knowledge_query simultaneously with different queries
    Then each session should receive results scoped to its own query
    And no cross-contamination of extracts should occur
    And neither session should observe the other's filter parameters

  # Why: Embedding-endpoint outage — Ollama unavailable is unavailability, not a session failure
  # [ASSUMPTION: confidence=low] Embedding endpoint timeout is treated as index unavailability rather than a separate error class
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Embedding endpoint timeout is treated as index unavailability
    Given the architecture knowledge index host is reachable
    But the embedding endpoint does not respond within its timeout
    When the Player invokes architecture_knowledge_query with query "modular monolith trade-offs"
    Then the tool should return the string "Knowledge index unavailable — proceed without RAG context."
    And no unhandled exception should be raised

  # Why: Malformed response — Chroma returns unparseable data
  @task:TASK-AKQT-001
  @edge-case @regression
  Scenario: Malformed response from ChromaDB is handled without crashing
    Given the architecture knowledge index host is reachable
    But the service returns a malformed response
    When the Player invokes architecture_knowledge_query with query "evolutionary architecture"
    Then the tool should return the string "Knowledge index unavailable — proceed without RAG context."
    And no unhandled exception should propagate to the Player

  # Why: Metadata robustness — extracts with missing topic must not crash citation formatting
  # [ASSUMPTION: confidence=low] Fallback citation label for missing topic metadata is "untopic'd"
  @task:TASK-AKQT-001
  @edge-case
  Scenario: Extract with missing topic metadata is cited with a fallback label
    Given the architecture knowledge index is available
    And an extract has metadata source_books ["Domain-Driven Design"] but no topic key
    When the Player invokes architecture_knowledge_query with query "ubiquitous language"
    Then that extract should be returned with a citation that names the source book
    And the citation should use the fallback label "untopic'd" in place of the missing topic
    And no exception should be raised during citation formatting
