# Generated by /feature-spec
# Feature: LPA Document Parsing and Extraction
# Stack: python
# Assumptions: 6 (see FEAT-POC-002-lpa-parsing_assumptions.yaml)
# Generated: 2026-05-27T00:00:00Z

@feat:FEAT-POC-002-lpa-parsing @lpa
Feature: LPA Document Parsing and Extraction
  As a signed-in donor
  I want to upload my Lasting Power of Attorney document and have its rules extracted for review
  So that the platform understands who my attorneys are, what they can and cannot do, and can flag transactions that conflict with my wishes

  Background:
    Given the document extraction service is available

  # ---------------------------------------------------------------------------
  # GROUP A: Key Examples
  # ---------------------------------------------------------------------------

  # Why: Core happy path — the upload kicks off the two-step extraction pipeline (Docling VLM then Qwen3.6) per ADR-POC-009
  @task:TASK-LPA02-007
  @key-example @smoke
  Scenario: Uploading a valid LPA PDF queues it for extraction
    Given I am signed in as a donor
    And no LPA has yet been uploaded for my account
    When I upload a PDF of my Lasting Power of Attorney
    Then the upload should be accepted
    And the LPA should be recorded against my account
    And the extraction should be reported as queued
    And the original document should be stored for later retrieval
    And the upload event should appear in my audit log

  # Why: HTMX and any future React client both poll the same status endpoint while extraction runs — content-negotiated per ADR-POC-014
  @task:TASK-LPA02-007
  @key-example @smoke
  Scenario: Polling shows progress while extraction is in flight
    Given I am signed in as a donor
    And I have just uploaded an LPA PDF
    When I check the status of the extraction
    Then I should see the current stage of the extraction
    And I should see the progress as a percentage between zero and one hundred
    And the extraction should not yet be ready for review

  # Why: Successful extraction emits the canonical rule shape — donor PII, attorneys, instructions, preferences, decision mode, limits
  @task:TASK-LPA02-007
  @key-example @smoke
  Scenario: Extracted rules become reviewable when the pipeline succeeds
    Given I am signed in as a donor
    And the extraction pipeline has finished successfully on my LPA
    When I view the extracted summary
    Then I should see my donor details as extracted from the LPA
    And I should see the primary attorneys named on the LPA
    And I should see the replacement attorneys named on the LPA
    And I should see the decision-making mode
    And I should see each instruction as a binding rule
    And I should see each preference as an advisory rule
    And I should see any spending limits the LPA records
    And the extraction-completed event should appear in my audit log

  # Why: Donor confirmation is the trigger that promotes extracted data to authoritative state and unblocks downstream rule application
  @task:TASK-LPA02-007
  @key-example @smoke
  Scenario: Donor confirms an accurate extraction
    Given I am signed in as a donor
    And the extraction has finished and is awaiting my review
    When I confirm the extracted summary without changes
    Then the LPA should be recorded as confirmed by me
    And the confirmation timestamp should be recorded
    And the confirmation event should appear in my audit log

  # Why: The review UI is editable — donors can correct mis-extracted PII or rule wording before confirming
  @task:TASK-LPA02-007
  @key-example
  Scenario: Donor corrects fields before confirming
    Given I am signed in as a donor
    And the extraction has finished and is awaiting my review
    And the extracted donor postcode is wrong
    When I correct the donor postcode and confirm
    Then my corrections should be saved as the authoritative extracted rules
    And the LPA should be recorded as confirmed by me
    And both the correction and the confirmation should appear in my audit log

  # Why: POC scope is one LPA per donor — re-upload supersedes prior LPA records cleanly
  @task:TASK-LPA02-006
  @key-example
  Scenario: Re-uploading an LPA replaces the previous one
    Given I am signed in as a donor
    And I have previously uploaded and confirmed an LPA
    When I upload a new LPA PDF
    Then the new LPA should become my current LPA
    And the new LPA's extraction should be queued
    And the previous LPA should no longer be returned as my current LPA

  # ---------------------------------------------------------------------------
  # GROUP B: Boundary Conditions
  # ---------------------------------------------------------------------------

  # [ASSUMPTION: confidence=low] Maximum LPA PDF file size is 25 MB; see ASSUM-001
  # Why: Just-inside file-size and page-count boundaries — must be accepted
  @task:TASK-LPA02-007
  @boundary
  Scenario Outline: LPA PDFs within the documented limits are accepted
    Given I am signed in as a donor
    And no LPA has yet been uploaded for my account
    When I upload an LPA PDF described as "<size_description>"
    Then the upload should be accepted
    And the extraction should be reported as queued

    Examples:
      | size_description                              |
      | a single-page LPA at the minimum useful size  |
      | a typical 23-page OPG LPA at around one and a half megabytes |
      | a high-resolution LPA at the 25 megabyte limit |

  # [ASSUMPTION: confidence=low] Maximum LPA PDF file size is 25 MB; see ASSUM-001
  # Why: Just-outside file-size boundary — must be rejected
  @task:TASK-LPA02-007
  @boundary @negative
  Scenario: A PDF larger than the maximum allowed size is rejected
    Given I am signed in as a donor
    When I attempt to upload an LPA PDF larger than the maximum allowed size
    Then the upload should be rejected
    And the rejection should indicate the file is too large
    And no LPA record should be created
    And no extraction should be queued

  # Why: MIME boundary — PDF is the only permitted type at POC stage
  @task:TASK-LPA02-007
  @boundary @negative
  Scenario Outline: Files that are not PDFs are rejected at upload
    Given I am signed in as a donor
    When I attempt to upload "<kind_of_file>" as my LPA
    Then the upload should be rejected
    And the rejection should indicate the file type is not allowed
    And no LPA record should be created

    Examples:
      | kind_of_file       |
      | a Word document    |
      | a JPEG image       |
      | a plain text file  |
      | a ZIP archive      |

  # Why: An LPA may legitimately name only one primary attorney and no replacements — extraction must tolerate this
  @task:TASK-LPA02-006
  @boundary
  Scenario: An LPA naming a single attorney and no replacements extracts cleanly
    Given I am signed in as a donor
    And I upload an LPA naming exactly one primary attorney and no replacement attorneys
    When the extraction pipeline completes
    Then the extracted primary attorneys list should contain one person
    And the extracted replacement attorneys list should be empty
    And the decision-making mode should be recorded as individual

  # Why: An LPA may name the maximum slots the OPG form allows (four attorneys plus two replacements) — must extract all
  @task:TASK-LPA02-006
  @boundary
  Scenario: An LPA naming the maximum attorneys and replacements extracts cleanly
    Given I am signed in as a donor
    And I upload an LPA naming four primary attorneys and two replacement attorneys
    When the extraction pipeline completes
    Then the extracted primary attorneys list should contain four people
    And the extracted replacement attorneys list should contain two people
    And every named person should have name, date of birth, and address recorded

  # ---------------------------------------------------------------------------
  # GROUP C: Negative Cases
  # ---------------------------------------------------------------------------

  # Why: LPA upload is a donor-only action — unauthenticated visitors must be refused
  @task:TASK-LPA02-007
  @negative
  Scenario: An unauthenticated visitor cannot upload an LPA
    Given I am not signed in
    When I attempt to upload an LPA PDF
    Then the request should be refused as unauthenticated

  # Why: Role-based authorisation — only donors upload LPAs
  @task:TASK-LPA02-007
  @negative
  Scenario: A user signed in as an attorney cannot upload an LPA
    Given I am signed in as an attorney
    When I attempt to upload an LPA PDF
    Then the request should be refused as unauthorised

  # Why: Ownership check — a donor cannot read another donor's LPA or its extraction
  @task:TASK-LPA02-007
  @negative
  Scenario: A donor cannot view another donor's LPA extraction
    Given I am signed in as a donor
    And another donor has uploaded an LPA
    When I attempt to view that donor's extracted rules
    Then the request should be refused as unauthorised

  # Why: The original-file stream endpoint must enforce ownership as strictly as the extracted-rules endpoint
  @task:TASK-LPA02-007
  @negative
  Scenario: A donor cannot download another donor's LPA file
    Given I am signed in as a donor
    And another donor has uploaded an LPA
    When I attempt to download that donor's original LPA file
    Then the request should be refused as unauthorised

  # Why: Confirmation only makes sense once extraction has produced reviewable output
  @task:TASK-LPA02-007
  @negative
  Scenario: Confirming before extraction has finished is rejected
    Given I am signed in as a donor
    And my LPA upload is still being extracted
    When I attempt to confirm the extracted summary
    Then the confirmation should be refused
    And the rejection should indicate the extraction is not yet ready

  # Why: A failed extraction cannot be confirmed — the donor must re-upload
  @task:TASK-LPA02-007
  @negative
  Scenario: Confirming a failed extraction is rejected
    Given I am signed in as a donor
    And my LPA extraction has failed
    When I attempt to confirm the extracted summary
    Then the confirmation should be refused
    And the rejection should indicate the extraction did not complete

  # Why: Attorneys can read confirmed LPA rules only via an active donor relationship — not opportunistically
  @task:TASK-LPA02-007
  @negative
  Scenario: An attorney without an active relationship cannot view a donor's LPA
    Given I am signed in as an attorney
    And I have no active relationship with a given donor
    When I attempt to view that donor's LPA
    Then the request should be refused as unauthorised

  # ---------------------------------------------------------------------------
  # GROUP D: Edge Cases
  # ---------------------------------------------------------------------------

  # Why: Docling VLM is the first step of the pipeline; if it is unreachable the failure must be observable and recoverable
  @task:TASK-LPA02-006
  @edge-case
  Scenario: Extraction fails gracefully when the document understanding service is unavailable
    Given I am signed in as a donor
    And the document understanding service is unavailable
    When I upload an LPA PDF
    Then the extraction should be reported as failed
    And the failure reason should indicate the document understanding service could not be reached
    And the failure should appear in my audit log
    And my original LPA file should still be retrievable

  # [ASSUMPTION: confidence=high] The pipeline falls back to a secondary model after two consecutive parse failures (ADR-POC-009); see ASSUM-005
  # Why: ADR-POC-009 specifies Claude API failover after two consecutive parse failures from Qwen3.6
  @task:TASK-LPA02-005
  @edge-case
  Scenario: The pipeline falls back to the secondary model after repeated parse failures
    Given I am signed in as a donor
    And the primary extraction model returns unparseable output twice in a row
    When the pipeline retries on the secondary model
    Then the extraction should complete using the secondary model
    And the secondary model should be recorded against the extraction
    And the donor should not need to take any action

  # [ASSUMPTION: confidence=medium] Re-uploading while an extraction is in flight supersedes the in-flight one (one LPA per donor); see ASSUM-006
  # Why: Extraction is a BackgroundTask in-process; uploading again must not corrupt the in-flight one
  @task:TASK-LPA02-006
  @edge-case
  Scenario: Uploading a new LPA while extraction is still running supersedes the in-flight one
    Given I am signed in as a donor
    And my LPA upload is still being extracted
    When I upload a different LPA PDF
    Then the new LPA should become my current LPA
    And the new extraction should be queued
    And the previous in-flight extraction should be abandoned or marked as superseded

  # Why: PDFs that do not look like an LPA must surface as a useful error — not silently produce empty rules
  @task:TASK-LPA02-006
  @edge-case
  Scenario: A PDF that is not recognisable as an LPA fails extraction with a helpful reason
    Given I am signed in as a donor
    When I upload a PDF that is not a Lasting Power of Attorney form
    Then the extraction should be reported as failed
    And the failure reason should indicate the document was not recognised as an LPA
    And the failure should appear in my audit log

  # Why: A malformed or password-protected PDF cannot be rasterised — must fail early, not hang the pipeline
  @task:TASK-LPA02-006
  @edge-case @negative
  Scenario Outline: Unreadable PDFs fail extraction with a clear reason
    Given I am signed in as a donor
    When I upload "<kind_of_pdf>"
    Then the extraction should be reported as failed
    And the failure reason should indicate the document could not be read

    Examples:
      | kind_of_pdf                            |
      | a password-protected PDF               |
      | a corrupted PDF                        |
      | a zero-byte file with a .pdf extension |

  # Why: Replacement attorney PII is captured for reference but must not be exposed to anyone other than the donor
  @task:TASK-LPA02-002
  @edge-case @security
  Scenario: Attorneys never see replacement attorney details
    Given the donor has confirmed an LPA naming both primary and replacement attorneys
    And I am signed in as a primary attorney with an active relationship with that donor
    When I view the donor's LPA
    Then I should see the primary attorneys and decision-making mode
    But I should not see any replacement attorney details

  # Why: Audit log is the FCA-narrative artefact; every meaningful state transition must be recorded
  @task:TASK-LPA02-009
  @edge-case @regression
  Scenario: Every meaningful step in the LPA lifecycle is captured in the audit log
    Given I am signed in as a donor
    When I upload an LPA, the system extracts it, and I confirm it
    Then the audit log should contain the upload event
    And the audit log should contain the extraction-started event
    And the audit log should contain the extraction-completed event
    And the audit log should contain the confirmation event

  # Why: Filenames are donor-supplied — must not be allowed to traverse storage or overwrite other donors' files
  @task:TASK-LPA02-004
  @edge-case @security
  Scenario: A maliciously-named LPA filename is handled safely
    Given I am signed in as a donor
    When I upload an LPA PDF whose filename attempts a path traversal
    Then the upload should either be accepted under a system-controlled name or be rejected
    And no file should be written outside the document storage area
    And no other donor's file should be affected

  # ---------------------------------------------------------------------------
  # GROUP E: Edge Case Expansion — Security
  # ---------------------------------------------------------------------------

  # Why: PDF content check beats extension check — extension alone must not be trusted
  @task:TASK-LPA02-007
  @edge-case @security @negative
  Scenario: A file with a PDF extension but non-PDF contents is rejected
    Given I am signed in as a donor
    When I attempt to upload a file with a .pdf extension whose contents are not a valid PDF
    Then the upload should be rejected
    And the rejection should indicate the file is not a valid PDF
    And no LPA record should be created

  # Why: Session expiry between extraction and confirm must not silently succeed — donor must re-authenticate
  @task:TASK-LPA02-007
  @edge-case @security
  Scenario: A confirmation attempt after the donor's session expires is refused
    Given I was signed in as a donor and the extraction is awaiting my review
    And my session has since expired
    When I attempt to confirm the extracted summary
    Then the confirmation should be refused as unauthenticated
    And the LPA should remain unconfirmed

  # ---------------------------------------------------------------------------
  # GROUP E: Edge Case Expansion — Concurrency and state
  # ---------------------------------------------------------------------------

  # Why: Donor may double-click confirm; the second confirm must not re-trigger downstream work or audit twice
  @task:TASK-LPA02-007
  @edge-case @regression
  Scenario: Confirming an already-confirmed LPA is treated idempotently
    Given I am signed in as a donor
    And I have already confirmed my extracted LPA
    When I submit the same confirmation a second time
    Then the LPA should remain confirmed with the original confirmation timestamp
    And the audit log should not record a second confirmation event

  # Why: HTMX polling plus a second browser tab — both must observe the same state machine without races or rewinds
  @task:TASK-LPA02-006
  @edge-case
  Scenario: Concurrent status polls see consistent state transitions
    Given I am signed in as a donor
    And I have just uploaded an LPA PDF
    When the extraction progresses through its stages while two clients poll concurrently
    Then both clients should observe the stages in the documented order
    And neither client should ever observe the status moving backwards

  # ---------------------------------------------------------------------------
  # GROUP E: Edge Case Expansion — Integration boundaries
  # ---------------------------------------------------------------------------

  # [ASSUMPTION: confidence=low] The pipeline enforces a hard 5-minute time budget on the structured-extraction step before declaring failure; see ASSUM-003
  # Why: Docling output is the debuggable intermediate per ADR-POC-009 — it must survive an LLM-step failure
  @task:TASK-LPA02-005
  @edge-case
  Scenario: An LLM-step failure preserves the document-understanding intermediate for debugging
    Given I am signed in as a donor
    And the document understanding step succeeded
    But the structured extraction step did not complete within its time budget
    Then the extraction should be reported as failed
    And the document understanding intermediate should be retained for diagnosis
    And the failure should appear in my audit log

  # [ASSUMPTION: confidence=low] Fields with confidence below 0.7 are highlighted for donor verification; see ASSUM-004
  # Why: Per-field confidence scores feed the review UI — donors must be cued to verify uncertain fields
  @task:TASK-LPA02-008
  @edge-case
  Scenario: Low-confidence fields are highlighted in the review summary
    Given I am signed in as a donor
    And the extraction has finished
    And the pipeline reported low confidence in the donor's date of birth
    When I view the extracted summary
    Then the donor's date of birth should be flagged for me to verify
    And other high-confidence fields should not be flagged
