# Generated by /feature-spec
# Feature: Attorney Invitation and Management
# Stack: python
# Assumptions: 10 (see FEAT-POC-005-attorney-management_assumptions.yaml)
# Generated: 2026-06-14T00:00:00Z

@feat:FEAT-POC-005-attorney-management @attorney
Feature: Attorney Invitation and Management
  As a donor
  I want to invite the primary attorneys named on my LPA and control their access to my financial data
  So that the people I have authorised — and only those people — can oversee my finances on my behalf

  Background:
    Given a donor has a confirmed LPA naming their primary attorneys

  # ---------------------------------------------------------------------------
  # GROUP A: Key Examples
  # ---------------------------------------------------------------------------

  # [ASSUMPTION: confidence=high] The invite code is a 6-character Crockford base32 code, single-use while pending; see ASSUM-006
  # Why: Core path — donor invites a specific primary attorney named on the LPA; a pending relationship and shareable code are created
  @key-example @smoke
  Scenario: Donor invites a primary attorney named on their LPA
    Given I am signed in as the donor
    When I invite the first primary attorney named on my LPA
    Then a pending invitation should be created for that attorney
    And I should be given a unique invite code to share with them
    And the invitation should carry the attorney's details as captured from my LPA
    And the attorney-invited event should appear in my audit log

  # Why: The donor's management surface — see who has been invited and the state of each relationship
  @key-example @smoke
  Scenario: Donor views the attorneys they have invited
    Given I am signed in as the donor
    And I have invited a primary attorney who has not yet claimed their invite
    When I view my attorneys
    Then I should see that attorney listed as pending alongside their invite code

  # Why: THE activation path — attorney whose identity matches the LPA-extracted details claims the invite and is granted access
  @key-example @smoke
  Scenario: A matching attorney claims an invite and is activated
    Given I am signed in as an attorney whose name and date of birth match a primary attorney on the donor's LPA
    And the donor has invited me with an invite code
    When I submit that invite code
    Then my relationship with the donor should become active
    And the donor should appear among the donors I oversee
    And the attorney-activated event should appear in the donor's audit log

  # Why: The attorney's dashboard — the list of donors they may oversee, with a financial summary per donor
  @key-example @smoke
  Scenario: An activated attorney lists the donors they oversee
    Given I am signed in as an attorney with an active relationship to a donor
    When I view the donors I oversee
    Then I should see that donor with a summary of their accounts and active flags

  # Why: Donors stay in control — revoking an attorney withdraws delegated access entirely
  @key-example @smoke
  Scenario: Donor revokes an attorney's access
    Given I am signed in as the donor
    And I have an attorney with an active relationship to me
    When I revoke that attorney's access
    Then the relationship should be recorded as revoked
    And the attorney should no longer be able to view my financial data
    And the attorney-revoked event should appear in my audit log

  # [ASSUMPTION: confidence=medium] Resending rotates the code and invalidates the previous one immediately; see ASSUM-008
  # Why: A donor can reissue a code if the first is lost or compromised; the old one must stop working
  @key-example
  Scenario: Donor resends an invitation to rotate the code
    Given I am signed in as the donor
    And I have invited a primary attorney who has not yet claimed their invite
    When I resend the invitation
    Then a new invite code should be issued for that attorney
    And the previous invite code should no longer be usable

  # Why: ADR-POC-014 — the attorney list is served identically as structured data and as a page fragment
  @key-example
  Scenario: The attorney list is served both as structured data and as a page fragment
    Given I am signed in as the donor
    And I have invited a primary attorney
    When I request my attorneys as structured data and again as a page fragment
    Then both responses should describe the same attorney with the same status

  # ---------------------------------------------------------------------------
  # GROUP B: Boundary Conditions
  # ---------------------------------------------------------------------------

  # [ASSUMPTION: confidence=high] An invite activates only when the identity match score reaches 0.85, weighted 0.7 name and 0.3 date of birth; see ASSUM-001, ASSUM-002
  # Why: Just-inside / just-outside the PII-match activation threshold
  @boundary
  Scenario Outline: An invite activates only when the identity match reaches the threshold
    Given I am signed in as an attorney claiming a donor's invite
    And my details produce <match_quality> against the named attorney
    When I submit the invite code
    Then the claim should be <outcome>

    Examples:
      | match_quality                               | outcome  |
      | a score exactly at the activation threshold | accepted |
      | a score just below the activation threshold | rejected |

  # [ASSUMPTION: confidence=high] Invite codes expire 30 days after they are issued; see ASSUM-003
  # Why: Just-inside boundary — a code claimed within its 30-day life still activates
  @boundary
  Scenario: An invite claimed just inside its thirty-day life activates
    Given I am signed in as a matching attorney
    And the donor invited me 29 days and 23 hours ago
    When I submit the invite code
    Then my relationship with the donor should become active

  # [ASSUMPTION: confidence=high] Invite codes expire 30 days after they are issued; see ASSUM-003
  # Why: Just-outside boundary — an expired code is refused and the invitation is closed off
  @boundary @negative
  Scenario: An invite claimed just after its thirty-day life is refused as expired
    Given I am signed in as a matching attorney
    And the donor invited me 30 days and 1 minute ago
    When I submit the invite code
    Then the claim should be refused because the invitation has expired
    And the expired invitation should be recorded as revoked
    And I should be invited to ask the donor for a new code

  # [ASSUMPTION: confidence=high] An invitation is revoked after three failed claim attempts; see ASSUM-004
  # Why: Just-outside the attempt limit — a third failed claim revokes the code (brute-force protection)
  @boundary @negative
  Scenario: A third failed claim revokes the invitation
    Given the donor has issued an invite code
    And that code has been submitted twice by someone whose details do not match
    When the code is submitted a third time by someone whose details do not match
    Then the claim should be refused
    And the invitation should be revoked so it can no longer be claimed
    And the donor must reissue an invitation for the genuine attorney to try again

  # [ASSUMPTION: confidence=high] An invitation is revoked after three failed claim attempts; see ASSUM-004
  # Why: Just-inside the attempt limit — a genuine match within the allowed attempts still activates
  @boundary
  Scenario: A matching attorney still activates within the attempt limit
    Given the donor has issued an invite code
    And that code has been submitted twice by someone whose details do not match
    When the genuinely matching attorney submits the code
    Then my relationship with the donor should become active
    And the invitation should not be revoked

  # Why: Invites target a specific named attorney by position — valid positions accepted, out-of-range refused
  @boundary
  Scenario Outline: Inviting by attorney position respects the list of named attorneys
    Given I am signed in as a donor whose LPA names three primary attorneys
    When I invite the attorney at <position>
    Then the invitation request should be <outcome>

    Examples:
      | position                                 | outcome  |
      | the first named primary attorney         | accepted |
      | the third named primary attorney         | accepted |
      | a fourth position that names no attorney | rejected |

  # ---------------------------------------------------------------------------
  # GROUP C: Negative Cases
  # ---------------------------------------------------------------------------

  # Why: Inviting is a donor-only action — an attorney cannot invite
  @negative
  Scenario: A user signed in as an attorney cannot invite attorneys
    Given I am signed in as an attorney
    When I attempt to invite a primary attorney to a donor's LPA
    Then the request should be refused as unauthorised

  # Why: All invitation actions require a signed-in donor
  @negative
  Scenario: An unauthenticated visitor cannot invite an attorney
    Given I am not signed in
    When I attempt to invite a primary attorney
    Then the request should be refused as unauthenticated

  # Why: POC scope — replacement attorneys are data only; they have no accounts, invites, or activation
  @negative
  Scenario: A donor cannot invite a replacement attorney
    Given I am signed in as a donor whose LPA names both primary and replacement attorneys
    When I attempt to invite one of the replacement attorneys
    Then the request should be refused
    And no invitation should be created

  # [ASSUMPTION: confidence=medium] A donor must have a confirmed LPA before inviting attorneys; see ASSUM-007
  # Why: Invitations snapshot extracted attorney PII — there is nothing to snapshot before confirmation
  @negative
  Scenario: A donor without a confirmed LPA cannot invite an attorney
    Given I am signed in as a donor who has not confirmed an LPA
    When I attempt to invite a primary attorney
    Then the request should be refused
    And I should be told to confirm my LPA first

  # Why: Donor-to-donor isolation — invitations are personal to the inviting donor
  @negative
  Scenario: A donor cannot manage another donor's invitation
    Given I am signed in as the donor
    And another donor has invited one of their attorneys
    When I attempt to revoke or resend that other donor's invitation
    Then the request should be refused
    And the other donor's invitation should remain unchanged

  # Why: An unrecognised or mistyped code must not reveal whether any invitation exists
  @negative
  Scenario: An unrecognised invite code is refused
    Given I am signed in as an attorney
    When I submit an invite code that matches no invitation
    Then the claim should be refused
    And I should be told the code is not recognised

  # Why: A code is single-use — once it has activated a relationship it cannot create another
  @negative
  Scenario: An already-claimed invite code cannot be claimed again
    Given an invitation has already been claimed and activated by its attorney
    When the same invite code is submitted again
    Then the claim should be refused
    And no second relationship should be created

  # Why: Claiming is an attorney-only action — a donor cannot claim an attorney invite
  @negative
  Scenario: A user signed in as a donor cannot claim an attorney invite
    Given I am signed in as a donor
    When I submit an attorney invite code
    Then the claim should be refused as unauthorised

  # [ASSUMPTION: confidence=medium] A primary attorney with a pending or active invitation cannot be invited again; the donor resends instead; see ASSUM-009
  # Why: Prevents duplicate relationships for the same named attorney
  @negative
  Scenario: Inviting the same primary attorney twice is prevented
    Given I am signed in as the donor
    And I have already invited the first primary attorney and that invitation is still pending
    When I attempt to invite the same primary attorney again
    Then the request should be refused
    And I should be directed to resend the existing invitation instead

  # ---------------------------------------------------------------------------
  # GROUP D: Edge Cases
  # ---------------------------------------------------------------------------

  # [ASSUMPTION: confidence=high] A failed claim records why it failed — name, date of birth, or both; see ASSUM-005
  # Why: A right-name wrong-DOB claim must be rejected with a specific, auditable reason (the attorney-bad demo persona)
  @edge-case
  Scenario: A claim whose name matches but date of birth does not is rejected
    Given I am signed in as an attorney whose name matches a named attorney but whose date of birth does not
    And the donor has invited that attorney with a code I hold
    When I submit the invite code
    Then the claim should be refused for a date-of-birth mismatch
    And the match score should be recorded against the invitation regardless of the outcome

  # Why: A wholly different identity must be rejected and recorded
  @edge-case
  Scenario: A claim whose name and date of birth both differ is rejected
    Given I am signed in as an attorney whose name and date of birth both differ from the named attorney
    And the donor has invited that attorney with a code I hold
    When I submit the invite code
    Then the claim should be refused for a mismatch on both name and date of birth
    And the failed match should be recorded for the donor to review

  # Why: Revocation must take effect immediately — a previously-working attorney loses access at once
  @edge-case @security
  Scenario: Revoking an active attorney cuts their access immediately
    Given I am signed in as the donor
    And an attorney has an active relationship and has been viewing my transactions
    When I revoke that attorney's access
    Then the attorney's next attempt to view my data should be refused
    And the revocation should appear in my audit log

  # [ASSUMPTION: confidence=medium] An invitation matches against the attorney details captured when it was issued, not the live LPA; see ASSUM-010
  # Why: The extracted attorney PII is snapshotted at invite time, so later LPA edits don't move the match target
  @edge-case
  Scenario: An outstanding invitation keeps matching against the details captured when issued
    Given I am signed in as the donor
    And I have invited a primary attorney, capturing their details from my LPA
    When I later re-confirm my LPA with a correction to an unrelated field
    Then the outstanding invitation should still match against the details captured when it was issued

  # Why: FCA narrative — the donor can always see the recorded match score, accepted or rejected
  @edge-case @regression
  Scenario: The identity match score is recorded whether the claim succeeds or fails
    Given an attorney has attempted to claim a donor's invitation
    When I view that attorney's relationship as the donor
    Then I should see the recorded match score for the attempt
    And the score should be present whether the attorney was accepted or rejected

  # Why: The audit log is the FCA-narrative artefact — every relationship state change must be captured
  @edge-case @regression
  Scenario: Every step of the attorney lifecycle is captured in the audit log
    Given I am signed in as the donor
    When I invite an attorney, they claim and are activated, and I later revoke them
    Then the audit log should contain the invitation event
    And the audit log should contain the activation event
    And the audit log should contain the revocation event

  # Why: The donor's attorney list shows recency — last-seen updates whenever the attorney reads the donor's data
  @edge-case
  Scenario: An attorney's last-seen time updates when they access a donor's data
    Given I am signed in as an attorney with an active relationship to a donor
    When I view that donor's financial data
    Then the time I was last seen should be updated on my relationship with that donor

  # ---------------------------------------------------------------------------
  # GROUP E: Expansion — Security
  # ---------------------------------------------------------------------------

  # Why: The code is a convenience, not the security boundary — PII match is. A leaked code is useless to an impostor
  @edge-case @security
  Scenario: A leaked invite code is useless to someone whose identity does not match
    Given an invite code intended for a named attorney has been leaked
    When someone whose name and date of birth do not match submits that code
    Then the claim should be refused
    And no relationship should become active for them

  # Why: PII isolation per ADR-POC-013 — a donor sees only their own attorneys' details and match scores
  @edge-case @security
  Scenario: A donor cannot see another donor's attorney relationships or match scores
    Given I am signed in as the donor
    And another donor has invited and activated their own attorney
    When I view my attorneys
    Then I should see only the attorneys I have invited
    And I should not see the other donor's attorney details or match scores

  # Why: Invite codes must resist guessing — the claim surface must not become an enumeration oracle
  @edge-case @security
  Scenario: Repeated guesses at invite codes do not reveal or activate any relationship
    Given I am signed in as an attorney
    When I submit many different unrecognised invite codes in succession
    Then every attempt should be refused as unrecognised
    And no attempt should reveal whether a similar code exists
    And no relationship should become active

  # ---------------------------------------------------------------------------
  # GROUP F: Expansion — Concurrency & Integrity
  # ---------------------------------------------------------------------------

  # Why: The single-use invariant must hold under a race, not just sequential replay
  @edge-case
  Scenario: Simultaneous claims of the same invite activate exactly one relationship
    Given the donor has issued an invite code to a matching attorney
    When the same invite code is submitted twice at the same instant
    Then exactly one relationship should become active
    And the other attempt should be refused

  # Why: A revoke racing an in-flight read must resolve cleanly to "no access" — never a partial grant
  @edge-case @security
  Scenario: A revoke that races an attorney's data read resolves to no access
    Given an attorney has an active relationship and is loading my data
    When I revoke that attorney's access at the same moment
    Then the attorney should not be left with continued access
    And any further attempt to view my data should be refused

  # Why: Rotating a code mid-claim must not leave a half-created relationship against the stale code
  @edge-case
  Scenario: A resend issued while a claim is in flight leaves no half-created relationship
    Given I have invited a primary attorney who is part-way through claiming the original code
    When I resend the invitation before that claim completes
    Then the in-flight claim against the previous code should be refused
    And only the reissued code should be able to activate the relationship

  # ---------------------------------------------------------------------------
  # GROUP G: Expansion — Integration Boundaries
  # ---------------------------------------------------------------------------

  # Why: The match depends on the attorney's identity profile — if it cannot be read, fail safe, never silently activate
  @edge-case @security
  Scenario: A claim is refused safely when the attorney's identity details cannot be read
    Given I am signed in as an attorney holding a valid invite code
    And my identity details needed for the match cannot be read at this moment
    When I submit the invite code
    Then the claim should be refused rather than activated
    And I should be able to try again once my details are available

  # Why: The audit trail is the FCA narrative — relationship events must be tamper-evident (append-only role grant)
  @edge-case @regression
  Scenario: Attorney lifecycle audit records cannot be altered or removed
    Given invitation, activation, and revocation events have been recorded in the audit log
    When any attempt is made through the application to alter or delete those records
    Then the records should remain exactly as first written
