# Generated by /feature-spec
# Feature: LPA Rules Application to Transactions
# Stack: python
# Assumptions: 4 (see FEAT-POC-004-rules-application_assumptions.yaml)
# Generated: 2026-06-14T00:00:00Z

@feat:FEAT-POC-004-rules-application @rules
Feature: LPA Rules Application to Transactions
  As an attorney overseeing a donor's finances
  I want the donor's transactions checked against the rules extracted from their LPA
  So that I can see at a glance which transactions may breach the donor's instructions or preferences

  Background:
    Given the donor has a confirmed LPA with extracted rules
    And the donor has a connected bank account with cached transactions

  # ---------------------------------------------------------------------------
  # GROUP A: Key Examples
  # ---------------------------------------------------------------------------

  # Why: The primary automatic trigger — a sync that brings new transactions queues rule checking in the background (Sequence 2 + ADR-POC-008)
  @key-example @smoke
  Scenario: Newly synced transactions are checked against the LPA rules
    Given a fresh sync has brought in transactions not seen before
    When the rule check runs over those new transactions
    Then transactions that match an LPA rule should be flagged
    And the rules-applied event should appear in the donor's audit log

  # Why: Confirming or correcting an LPA changes the rules, so every cached transaction must be re-checked
  @key-example @smoke
  Scenario: Confirming an LPA re-checks all cached transactions
    Given the donor has cached transactions that were checked under earlier rules
    When the donor confirms a correction to their LPA rules
    Then all of the donor's cached transactions should be re-checked against the new rules
    And the resulting flags should reflect the corrected rules

  # Why: The donor's manual escape hatch to re-run checking on demand
  @key-example
  Scenario: Donor manually re-runs rule application
    Given the donor has cached transactions
    When the donor asks for the rules to be applied again
    Then a rule-application job should be accepted and run in the background
    And the donor should be able to follow the job until it completes

  # Why: Binding "must" rule violated — the red flag that is the whole point of the feature
  @key-example @smoke
  Scenario: A transaction breaching a binding instruction is flagged as an instruction violation
    Given the LPA contains a binding instruction the donor's spending must obey
    And a transaction breaches that instruction
    When the rule check runs
    Then that transaction should carry an instruction-level flag
    And the flag should name the rule it breached and explain why

  # Why: Advisory "should" rule conflicted — the amber flag
  @key-example
  Scenario: A transaction conflicting with a preference is flagged as a preference advisory
    Given the LPA contains a preference about how the donor's money should be spent
    And a transaction conflicts with that preference
    When the rule check runs
    Then that transaction should carry a preference-level flag
    And the flag should explain how it conflicts with the preference

  # Why: Unusual activity with no matching LPA rule still surfaces for attorney attention — the blue flag
  @key-example
  Scenario: An unusual transaction with no matching rule is flagged as advisory
    Given a transaction is an unusual pattern such as a large round-number payment to a new merchant
    And no LPA instruction or preference directly addresses it
    When the rule check runs
    Then that transaction should carry an advisory-level flag
    And the flag should explain why it was considered unusual

  # Why: The donor's own dashboard view of every flag across all their accounts
  @key-example
  Scenario: Donor views their flags across all accounts
    Given the donor has flagged transactions across more than one account
    When the donor views their flags
    Then they should see each flag with its severity, the transaction, the rule and the reason
    And they should be able to filter the flags by severity

  # Why: Drill-down to the full LLM reasoning behind a single flag (FlagDetail)
  @key-example
  Scenario: Donor opens a single flag to see the full reasoning
    Given the donor has a flagged transaction
    When the donor opens that flag
    Then they should see the full reasoning behind the flag
    And they should see the rule text as it stood when the flag was raised

  # Why: THE delegation payoff — attorney sees the donor's flags through the platform, never touching Moneyhub (Sequence 2)
  @key-example @smoke
  Scenario: Attorney views a donor's flags through delegation
    Given I am an attorney with an active relationship to the donor
    When I view that donor's flags
    Then I should see the same flags the donor would see
    And my viewing of the donor's data should be recorded in the audit log

  # Why: Flags are also surfaced inline on the transaction list, not only on the flags dashboard
  @key-example
  Scenario: Flags appear attached to the transactions they relate to
    Given some of the donor's transactions have been flagged
    When the donor or their attorney views the transaction list
    Then each flagged transaction should carry its severity and the reason it was flagged
    And unflagged transactions should carry no flag

  # ---------------------------------------------------------------------------
  # GROUP B: Boundary Conditions
  # ---------------------------------------------------------------------------

  # Why: Just-inside / just-outside the model's confidence threshold for showing a flag
  # [ASSUMPTION: confidence=high] ASSUM-001 — the confidence threshold for surfacing a flag is 0.70; candidates below it are stored but hidden
  @boundary
  Scenario Outline: Only flags at or above the confidence threshold are shown
    Given the rule check produces a flag candidate with confidence <confidence>
    When the rule check completes
    Then the candidate should be <visibility>

    Examples:
      | confidence | visibility        |
      | 0.70       | shown as a flag   |
      | 0.71       | shown as a flag   |
      | 0.69       | stored but hidden |

  # Why: Just-inside / just-outside a spending limit — a deterministic numeric boundary fed to the check
  @boundary
  Scenario Outline: A per-transaction spending cap flags only amounts over the cap
    Given a binding instruction caps any single transaction at £500
    And a transaction of <amount> exists
    When the rule check runs
    Then the transaction should be <result>

    Examples:
      | amount  | result                              |
      | £499.99 | left unflagged                      |
      | £500.00 | left unflagged                      |
      | £500.01 | flagged as an instruction violation |

  # Why: Just-inside boundary — a batch at the maximum batch size is checked in a single pass
  # [ASSUMPTION: confidence=medium] ASSUM-002 — transactions are checked in batches of up to 50 per model call
  @boundary
  Scenario: A batch at the maximum size is checked in a single pass
    Given exactly 50 transactions are due for checking
    When the rule check runs
    Then all 50 transactions should be checked
    And the job should report 50 transactions scanned

  # Why: Just-outside boundary — exceeding the batch size splits into multiple passes with no transaction missed
  @boundary
  Scenario: More transactions than one batch are checked across multiple passes
    Given 51 transactions are due for checking
    When the rule check runs
    Then all 51 transactions should be checked
    And the job should report 51 transactions scanned

  # Why: Pagination contract for the flags dashboard, mirroring the transactions list
  # [ASSUMPTION: confidence=low] ASSUM-003 — default flag page size is 50 and the maximum requestable page size is 200
  @boundary
  Scenario Outline: Flag pages respect the requested page size
    Given the donor has 250 flags
    When the donor views their flags requesting <requested> per page
    Then they should receive <returned> flags
    And they should be told the total count and whether more pages remain

    Examples:
      | requested   | returned |
      | 1           | 1        |
      | the default | 50       |
      | 200         | 200      |

  # Why: Empty boundary — a donor with no rules or no transactions yields an empty, successful check
  @boundary
  Scenario: A rule check over nothing to flag completes cleanly with no flags
    Given the donor has a confirmed LPA but no transactions yet
    When the rule check runs
    Then the job should complete successfully
    And no flags should be generated

  # ---------------------------------------------------------------------------
  # GROUP C: Negative Cases
  # ---------------------------------------------------------------------------

  # Why: The central authorisation rule — no active relationship, no delegated access to flags (mirrors FEAT-POC-003)
  @negative @smoke
  Scenario: An attorney with no relationship to a donor cannot view their flags
    Given I am an attorney with no relationship to a particular donor
    When I attempt to view that donor's flags
    Then I should be refused because I am not linked to that donor

  # Why: Only ACTIVE relationships confer access — pending, dormant and revoked all deny
  @negative
  Scenario Outline: Only an active relationship grants delegated access to flags
    Given I am an attorney whose relationship with a donor is <status>
    When I attempt to view that donor's flags
    Then I should be refused because I am not actively linked to that donor

    Examples:
      | status  |
      | pending |
      | dormant |
      | revoked |

  # Why: Donor-to-donor isolation — flags are personal to the donor
  @negative
  Scenario: A donor cannot view another donor's flags
    Given another donor has flagged transactions
    When I attempt to view that other donor's flags
    Then I should be refused

  # Why: All flag surfaces require a signed-in user
  @negative
  Scenario: Flags are not available without signing in
    Given I am not signed in
    When I attempt to view flags
    Then I should be asked to sign in

  # Why: Rules can only be applied against rules the donor has confirmed — unconfirmed extraction must not flag
  @negative
  Scenario: Rule application does not run against an unconfirmed LPA
    Given the donor has an extracted LPA that has not yet been confirmed
    When a rule check is requested for that donor
    Then no flags should be generated
    And the donor should be told the LPA must be confirmed first

  # Why: Manual apply with no confirmed LPA at all has nothing to check against
  @negative
  Scenario: Manual rule application is refused when the donor has no confirmed LPA
    Given the donor has no confirmed LPA
    When the donor asks for the rules to be applied
    Then the request should be refused with an explanation
    And no rule-application job should be started

  # Why: Delegation is read-only — attorneys observe flags, they never trigger rule application
  @negative
  Scenario: An attorney cannot trigger rule application for a donor
    Given I am an attorney with an active relationship to the donor
    When I attempt to start a rule check on the donor's behalf
    Then I should be refused

  # ---------------------------------------------------------------------------
  # GROUP D: Edge Cases
  # ---------------------------------------------------------------------------

  # Why: Re-application replaces the prior flag set for the checked transactions — no soft-delete, no stale flags
  # [ASSUMPTION: confidence=high] ASSUM-004 — re-running rule application replaces the previous flags for the checked transactions
  @edge-case
  Scenario: Re-running rule application replaces the previous flags for those transactions
    Given a transaction was previously flagged under an earlier rule check
    When the rules are applied again and that transaction no longer breaches any rule
    Then the transaction's earlier flag should no longer be shown

  # Why: Idempotency — re-checking unchanged transactions against unchanged rules must not duplicate flags
  @edge-case
  Scenario: Re-checking unchanged transactions does not duplicate flags
    Given the donor's transactions and rules are unchanged since the last check
    When the rule check runs again
    Then each flagged transaction should carry the same flags only once

  # Why: The check is fire-and-forget; if the model is unavailable the job fails cleanly and prior flags survive
  @edge-case
  Scenario: Rule application fails cleanly when the model is unavailable
    Given the language model used for rule checking is unavailable
    When a rule check runs
    Then the job should be recorded as failed with a reason
    And any flags from the previous successful check should remain visible
    And the application-failed event should appear in the donor's audit log

  # Why: A single transaction can breach more than one rule and should show every flag it earns
  @edge-case
  Scenario: A transaction breaching several rules shows a flag for each
    Given a transaction breaches both a binding instruction and a preference
    When the rule check runs
    Then that transaction should carry an instruction flag and a preference flag

  # Why: Flags are owned by their transaction — replacing the cached transaction set must not orphan flags
  @edge-case
  Scenario: Flags are removed when their transaction leaves the cache
    Given a transaction has a flag
    When that transaction is removed from the donor's cache
    Then its flag should no longer appear anywhere

  # Why: Below-threshold candidates are never shown to either the donor or the attorney
  @edge-case
  Scenario: Low-confidence candidates are never surfaced to the attorney
    Given the rule check produced a below-threshold candidate for a transaction
    When the attorney views that donor's flags
    Then the below-threshold candidate should not appear

  # Why: Decision-making mode informs the check as context but does not itself raise flags (attorneys don't initiate transactions in the POC)
  @edge-case
  Scenario: Decision-making mode alone does not raise a flag
    Given the LPA requires attorneys to act jointly
    And no transaction breaches any instruction or preference
    When the rule check runs
    Then no flag should be raised on the basis of the decision-making mode alone

  # Why: Category-based rules pivot on Moneyhub enrichment — a restricted category is matched even when the description is opaque
  @edge-case
  Scenario: A category-restricted transaction is flagged using its enriched category
    Given a binding instruction forbids spending in the gambling category
    And a transaction is enriched by the bank data as a gambling transaction
    When the rule check runs
    Then that transaction should carry an instruction-level flag for the restricted category

  # ---------------------------------------------------------------------------
  # GROUP E: Expansion — Security
  # ---------------------------------------------------------------------------

  # Why: The audit trail is the FCA narrative — rule-application and flag events must be tamper-evident (append-only role grant)
  @edge-case @negative
  Scenario: Rule-application audit events cannot be altered or removed
    Given rule-application and flagging events have been recorded in the audit log
    When any attempt is made through the application to alter or delete those records
    Then the records should remain exactly as first written

  # Why: The model must not invent flags for transactions outside the batch it was given
  @edge-case @negative
  Scenario: A flag for a transaction that was not checked is ignored
    Given the model returns a flag naming a transaction that was not in the batch
    When the rule check completes
    Then that flag should be discarded
    And no flag should be attached to a transaction that was never checked

  # Why: Transaction descriptions are untrusted text — they must not be able to steer the rule check
  @edge-case @negative
  Scenario: A transaction description attempting to manipulate the check has no effect
    Given a transaction description contains text instructing the checker to ignore all rules
    When the rule check runs
    Then the donor's actual LPA rules should still be applied unchanged
    And the manipulative text should not suppress or fabricate any flag

  # ---------------------------------------------------------------------------
  # GROUP F: Expansion — Concurrency
  # ---------------------------------------------------------------------------

  # Why: Donors and triggers can overlap — concurrent runs must converge on one consistent, non-duplicated flag set
  @edge-case
  Scenario: Two rule-application runs at the same time produce one consistent flag set
    Given a rule check is already running for the donor
    When a second rule check for the same donor starts at the same time
    Then each flagged transaction should end up with its flags only once
    And the final flags should be consistent with the donor's current rules

  # ---------------------------------------------------------------------------
  # GROUP G: Expansion — Integration Boundaries
  # ---------------------------------------------------------------------------

  # Why: The model can name a rule that does not exist — such a flag has no provenance and must be rejected
  @edge-case @negative
  Scenario: A flag citing a rule that is not in the LPA is rejected
    Given the model returns a flag citing a rule that is not among the donor's extracted rules
    When the rule check completes
    Then that flag should be rejected
    And only flags citing real LPA rules should be kept

  # Why: A multi-batch check that fails partway must not discard the work already done
  @edge-case
  Scenario: A multi-batch check that fails partway keeps the flags already produced
    Given the donor's transactions are checked across several batches
    When one batch fails after earlier batches have produced flags
    Then the flags from the successful batches should be kept
    And the job should report that the check did not complete in full
