# Generated by /feature-spec
# Feature: Conversation Starter Formatter and Structured Session Logger
# Stack: python
# Assumptions: 4 (see conversation-starter-formatter-session-logger_assumptions.yaml)
# Generated: 2026-04-07T00:00:00Z

@output @feat-004
Feature: Conversation Starter Formatter and Structured Session Logger
  As an architect agent developer
  I want the OutputFormatter to produce GuardKit-format markdown and the SessionLogger to write structured JSON
  So that the architect agent produces conversation starters ready for /system-arch and leaves an auditable session trail

  Background:
    Given a valid session with project name "FinProxy"
    And a conversation starter containing C4 diagrams and ADRs
    And an evaluation with criterion scores and detection findings

  # ━━ GROUP A: Key Examples ━━

  # Why: Core formatter path -- all 11 required sections must appear in correct order
  @key-example @smoke
  Scenario: Formatting a complete conversation starter
    Given a conversation starter with context and container C4 diagrams
    And 3 preferred decisions with alternatives considered
    And 2 open questions for /system-arch
    And a constraints section
    When I format the conversation starter
    Then the output should be valid markdown
    And the output should contain 11 required sections in order:
      | section                                                    |
      | # FinProxy -- Conversation Starter                         |
      | ## Purpose of this document                                |
      | ## What is FinProxy?                                       |
      | ## Key architectural principle                             |
      | ## C4 Level 1: System Context                              |
      | ## C4 Level 2: Container Diagram                           |
      | ## Preferred Decisions (challenge only with new evidence)  |
      | ## Open Questions for /system-arch to Resolve              |
      | ## Constraints                                             |
      | ## Source Documents                                        |
      | ## Suggested Research Topics                               |

  # Why: Decision framing is critical -- "Preferred Decisions" not "Resolved Decisions"
  @key-example @smoke
  Scenario: Decision table uses the preferred framing
    Given 2 preferred decisions each with at least 2 alternatives considered
    When I format the conversation starter
    Then the decisions section heading should be "Preferred Decisions (challenge only with new evidence)"
    And each decision row should include the chosen option and alternatives considered

  # Why: C4 diagrams must be renderable -- Mermaid fences are the output contract
  @key-example
  Scenario: C4 diagrams are wrapped in Mermaid code fences
    Given a context C4 diagram and a container C4 diagram
    When I format the conversation starter
    Then each C4 diagram should be enclosed in a mermaid code fence
    And the context diagram should appear before the container diagram

  # Why: Core logger path -- validates the JSON structure contract
  @key-example @smoke
  Scenario: Logging a single Player-Coach iteration
    Given a session with ID "abc12345"
    And iteration 1 with an adjusted score of 0.62
    And criterion scores for all 6 evaluation criteria
    And 1 detection finding of severity "major"
    And token usage of 4500 input and 2200 output tokens
    And a duration of 12.5 seconds
    When I log the iteration
    Then the session log should contain a valid JSON entry for iteration 1
    And the entry should include session ID, iteration number, score, criterion scores, detection findings, token usage, and duration

  # Why: Session completion captures the final state for audit and replay
  @key-example
  Scenario: Logging session completion
    Given a session that completed after 3 iterations
    And a final evaluation with an adjusted score of 0.68
    And a verdict of "ACCEPTABLE"
    When I log the session as complete
    Then the session log should contain the final score, verdict, total tokens, and total duration
    # [ASSUMPTION: confidence=high] Session log filename is {project_name}-session-log.json per PLAN.md FEAT-004
    And the log file should be written to the configured output path as "FinProxy-session-log.json"

  # Why: Multiple iterations must accumulate correctly in a single log
  @key-example
  Scenario: Logging multiple iterations in sequence
    Given 3 completed Player-Coach iterations with scores 0.45, 0.55, and 0.68
    When each iteration is logged in order
    Then the session log should contain 3 iteration entries
    And the entries should appear in chronological order
    And each entry should have a distinct iteration number

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Minimum viable conversation starter -- Context + Container C4 is the floor
  @boundary
  Scenario: Formatting a conversation starter with exactly the minimum C4 diagrams
    Given a conversation starter with exactly a context and a container C4 diagram
    And no component-level diagrams
    When I format the conversation starter
    Then the output should include the System Context and Container Diagram sections
    And no component diagram section should appear

  # Why: Zero ADRs is a valid edge -- formatter must not crash or produce empty table
  @boundary
  Scenario: Formatting with no preferred decisions
    Given a conversation starter with zero preferred decisions
    When I format the conversation starter
    # [ASSUMPTION: confidence=medium] Empty sections use placeholder text rather than being omitted
    Then the preferred decisions section should indicate no decisions have been made yet
    And the output should still contain all 11 sections

  # Why: Zero open questions -- valid state when the starter is fully resolved
  @boundary
  Scenario: Formatting with no open questions
    Given a conversation starter with zero open questions
    When I format the conversation starter
    # [ASSUMPTION: confidence=medium] Empty sections use placeholder text rather than being omitted
    Then the open questions section should indicate no open questions remain
    And the output should still contain all 11 sections

  # Why: Score at exact threshold boundary -- 0.6 is ACCEPTABLE, not REVISE
  @boundary
  Scenario: Logging an iteration at the exact acceptance threshold
    Given an iteration with an adjusted score of exactly 0.6
    When I log the iteration
    Then the logged verdict should be "ACCEPTABLE"

  # Why: Just-below threshold -- 0.59 is REVISE
  @boundary
  Scenario: Logging an iteration just below the acceptance threshold
    Given an iteration with an adjusted score of 0.59
    When I log the iteration
    Then the logged verdict should be "REVISE"

  # ━━ GROUP C: Negative Cases ━━

  # Why: Conversation starter without minimum C4 should be rejected
  @negative
  Scenario: Formatting a conversation starter missing the context C4 diagram
    Given a conversation starter with no context C4 diagram
    When I attempt to format the conversation starter
    Then the formatter should raise a validation error
    And the error should indicate a context C4 diagram is required

  # Why: Conversation starter without container diagram violates the minimum contract
  @negative
  Scenario: Formatting a conversation starter missing the container C4 diagram
    Given a conversation starter with a context C4 diagram but no container C4 diagram
    When I attempt to format the conversation starter
    Then the formatter should raise a validation error
    And the error should indicate a container C4 diagram is required

  # Why: Logger must handle invalid output path gracefully
  @negative
  Scenario: Logging to a non-existent output directory
    Given an output path that does not exist
    When I attempt to log an iteration
    Then the logger should raise an error indicating the output directory is missing

  # Why: ADRs with fewer than 2 alternatives violate the generation type invariant
  @negative
  Scenario: Formatting a decision with fewer than 2 alternatives considered
    Given a preferred decision with only 1 alternative considered
    When I attempt to format the conversation starter
    Then the formatter should raise a validation error
    And the error should indicate each ADR must have at least 2 alternatives

  # ━━ GROUP D: Edge Cases ━━

  # Why: Very long product descriptions should not break formatting
  @edge-case
  Scenario: Formatting a conversation starter with a very long project description
    Given a conversation starter with a project description exceeding 5000 characters
    When I format the conversation starter
    Then the output should be valid markdown
    And the project description should be included in full without truncation

  # Why: Detection findings with mixed severities must all appear in the log
  @edge-case
  Scenario: Logging an iteration with multiple detection findings of different severities
    Given an iteration with detection findings:
      | type              | severity |
      | PHANTOM           | critical |
      | UNGROUNDED        | major    |
      | MISSING_TRADEOFF  | major    |
    When I log the iteration
    Then all 3 detection findings should appear in the log entry
    And the total penalty should be recorded as 0.20

  # Why: First iteration may produce a session log file that doesn't exist yet
  @edge-case
  Scenario: Logging the first iteration creates the session log file
    Given no session log file exists at the output path
    When I log the first iteration
    Then a new session log file should be created
    And the file should contain valid JSON with the first iteration entry

  # Why: Special characters in project name must be handled safely in filenames
  @edge-case
  Scenario: Formatting a conversation starter with special characters in the project name
    Given a session with project name "My Project (v2.0)"
    When I format the conversation starter
    Then the heading should include the full project name
    # [ASSUMPTION: confidence=medium] Special characters replaced with hyphens, lowercased for filenames
    And the session log filename should be safely encoded

  # ━━ GROUP E: Edge Cases (Expansion) — Data Integrity ━━

  # Why: Partial write could leave invalid JSON -- logger must handle gracefully
  @edge-case
  Scenario: Logging after a corrupted session log file
    Given a session log file that contains truncated JSON from a prior interrupted write
    When I log a new iteration
    # [ASSUMPTION: confidence=low] Corrupted file renamed with .bak suffix, fresh log started
    Then the logger should recover the valid entries from the corrupted file
    And the new iteration should be appended
    And the resulting file should contain valid JSON

  # Why: Parallel sessions must not interfere with each other's log files
  @edge-case
  Scenario: Concurrent sessions write to distinct log files
    Given two sessions with project names "ProjectA" and "ProjectB"
    When both sessions log iterations simultaneously
    Then "ProjectA-session-log.json" should contain only ProjectA entries
    And "ProjectB-session-log.json" should contain only ProjectB entries

  # Why: Process restart should not lose prior iteration data
  @edge-case
  Scenario: Logging preserves prior entries after process restart
    Given a session log with 2 previously logged iterations
    And a new SessionLogger instance is created for the same output path
    When I log iteration 3
    Then the session log should contain all 3 iterations
    And iterations 1 and 2 should be unchanged

  # ━━ GROUP F: Edge Cases (Expansion) — Integration Boundaries ━━

  # Why: Formatter is not a Mermaid linter -- it wraps content, doesn't validate syntax
  @edge-case
  Scenario: Formatting a conversation starter with Mermaid syntax errors
    Given a C4 diagram containing invalid Mermaid syntax
    When I format the conversation starter
    Then the formatter should include the diagram as-is within the mermaid code fence
    And no syntax validation error should be raised

  # Why: Cached or tool-only responses may report zero tokens -- must not crash
  @edge-case
  Scenario: Logging an iteration with zero token usage
    Given an iteration with token usage of 0 input and 0 output tokens
    When I log the iteration
    Then the log entry should record token usage as zero for both input and output
    And the entry should be valid

  # Why: The formatter's output IS the input to /system-arch -- it must parse cleanly
  @edge-case
  Scenario: Formatted conversation starter is valid input for system-arch
    Given a fully formatted conversation starter
    When the output is parsed as markdown
    Then all section headings should be extractable
    And all mermaid code fences should be properly closed
    And the document should not contain raw template placeholders
