# Generated by /feature-spec
# Feature: Role Learning Metrics
# Stack: python
# Assumptions: 8 (see role-learning-metrics_assumptions.yaml)
# Generated: 2026-04-12T00:00:00Z

@role-learning-metrics @graphiti @feat-g03
Feature: Role Learning Metrics
  As a specialist agent operator
  I want session metrics tracked per role, role knowledge summarised periodically,
  stale patterns detected, and a CLI report showing compounding progress
  So that I can verify the system is learning from accumulated sessions and prune
  outdated knowledge before it degrades output quality

  Background:
    Given the Graphiti service is available
    And a role configuration exists for "architect" with knowledge_graph enabled
    And the "architect" role has completed at least 1 prior session

  # ━━ GROUP A: Key Examples (6 scenarios) ━━

  # Why: Core metric — iterations-to-pass is the primary compounding signal
  @key-example @smoke
  Scenario: Session metrics record iterations-to-pass after an approved session
    Given a greenfield session completes for role "architect" on project "finproxy"
    And the session required 3 iterations with scores 0.45, 0.58, and 0.72
    When the session metrics are written to Graphiti
    Then a metrics episode should be written with group_id "role:architect"
    And the episode should contain iterations_to_pass of 3

  # Why: First-iteration score tracks whether the Player's starting quality improves over time
  @key-example @smoke
  Scenario: Session metrics record first-iteration score
    Given a greenfield session completes for role "architect" on project "finproxy"
    And the first iteration scored 0.55
    When the session metrics are written to Graphiti
    Then the metrics episode should contain first_iteration_score of 0.55

  # Why: Detection counts track whether the Player learns to avoid anti-patterns
  @key-example @smoke
  Scenario: Session metrics record detection findings count and types
    Given a greenfield session completes for role "architect" on project "finproxy"
    And 2 detection findings were recorded: "SCOPE_CREEP" and "PHANTOM"
    When the session metrics are written to Graphiti
    Then the metrics episode should contain detection_count of 2
    And the metrics episode should list detection types "SCOPE_CREEP" and "PHANTOM"

  # Why: Role knowledge summary aggregates accumulated patterns into a queryable snapshot
  @key-example @smoke
  Scenario: Role knowledge summary is generated from accumulated sessions
    Given the "architect" role has completed 5 sessions across 3 projects
    And 8 pattern facts and 4 quality signal facts exist in group_id "role:architect"
    When a role knowledge summary is requested for "architect"
    Then a summary episode should be written to group_id "role:architect"
    And the summary should contain the total session count
    And the summary should contain the average iterations-to-pass
    And the summary should contain the most frequent detection types
    And the summary should contain the highest-scoring architectural patterns

  # Why: Staleness detection prevents outdated patterns from degrading output quality
  # [ASSUMPTION: confidence=high] Staleness threshold is 180 days based on role.yaml design
  @key-example @smoke
  Scenario: Stale patterns are flagged when not reinforced within the threshold
    Given a pattern "modular monolith for small teams" was last reinforced 200 days ago
    And the staleness threshold is 180 days
    When staleness detection runs for role "architect"
    Then the pattern should be flagged as stale
    And the stale pattern should appear in the staleness report

  # Why: The CLI report is the operator-facing proof that compounding is happening
  # [ASSUMPTION: confidence=low] CLI subcommand is "specialist-agent report"
  @key-example @smoke
  Scenario: CLI report command displays compounding metrics for a role
    Given the "architect" role has session metrics for 5 sessions
    When I run "specialist-agent report --role architect"
    Then the output should include the total session count
    And the output should include the average iterations-to-pass
    And the output should include the trend in first-iteration scores
    And the output should include the count of stale patterns

  # ━━ GROUP B: Boundary Conditions (6 scenarios) ━━

  # Why: First session for a role — no prior data to aggregate
  @boundary
  Scenario: Session metrics for the first-ever session of a role
    Given the "architect" role has no prior session metrics in Graphiti
    And a greenfield session completes with 4 iterations
    When the session metrics are written to Graphiti
    Then the metrics episode should be written with group_id "role:architect"
    And no role knowledge summary should exist yet

  # Why: Boundary — session passes on first iteration (best case)
  @boundary
  Scenario: Session that passes on the first iteration records iterations-to-pass of 1
    Given a greenfield session completes for role "architect"
    And the first iteration scored 0.78 which exceeds the pass threshold
    When the session metrics are written to Graphiti
    Then the metrics episode should contain iterations_to_pass of 1
    And the metrics episode should contain detection_count of 0

  # Why: Boundary — session exhausts all iterations without passing
  @boundary @negative
  Scenario: Failed session records metrics but marks success as false
    Given a greenfield session exhausts 5 iterations without reaching the threshold
    And the final score was 0.52
    When the session metrics are written to Graphiti
    Then the metrics episode should contain session_passed as false
    And the metrics episode should contain iterations_to_pass as null
    And the metrics episode should contain the full score history

  # Why: Boundary — staleness exactly at threshold (180 days)
  # [ASSUMPTION: confidence=high] Staleness threshold is 180 days
  @boundary
  Scenario Outline: Pattern staleness at and around the threshold boundary
    Given a pattern was last reinforced <days_ago> days ago
    And the staleness threshold is 180 days
    When staleness detection runs
    Then the pattern should be flagged as <result>

    Examples:
      | days_ago | result |
      | 179      | fresh  |
      | 180      | fresh  |
      | 181      | stale  |

  # Why: Boundary — role knowledge summary with exactly 1 session
  # [ASSUMPTION: confidence=low] Trend requires minimum 3 sessions to compute
  @boundary
  Scenario: Role knowledge summary with a single session
    Given the "architect" role has completed exactly 1 session
    When a role knowledge summary is requested for "architect"
    Then the summary should contain session count of 1
    And the summary should not compute a trend (insufficient data)

  # Why: Boundary — staleness threshold of 0 days (all patterns immediately stale)
  # [ASSUMPTION: confidence=low] Minimum staleness threshold is 1 day
  @boundary @negative
  Scenario: Staleness threshold below minimum is rejected
    Given a role configuration with staleness_threshold_days of 0
    When the configuration is loaded
    Then a validation error should indicate the staleness threshold must be at least 1

  # ━━ GROUP C: Negative Cases (5 scenarios) ━━

  # Why: Graphiti outage should not fail an otherwise successful session
  # [ASSUMPTION: confidence=medium] Graphiti write failure is non-blocking (log and continue)
  @negative
  Scenario: No metrics are written when Graphiti is unavailable
    Given a greenfield session completes successfully
    And the Graphiti service is unavailable
    When the session metrics write is attempted
    Then the write failure should be logged as a warning
    And the session should still complete successfully
    And no metrics episode should exist in Graphiti

  # Why: CLI report for a role with no sessions should not crash
  @negative
  Scenario: CLI report for a role with no session history
    Given the "ideation" role has no session metrics in Graphiti
    When I run "specialist-agent report --role ideation"
    Then the output should indicate no session data is available for this role
    And the exit code should be 0

  # Why: Invalid role ID should produce a clear error
  @negative
  Scenario: CLI report for a nonexistent role
    When I run "specialist-agent report --role nonexistent-role"
    Then the error output should indicate the role was not found
    And the exit code should be 2

  # Why: Role knowledge summary should handle corrupted Graphiti data gracefully
  @negative
  Scenario: Role knowledge summary handles malformed metrics episodes
    Given the "architect" role has 3 valid and 1 malformed metrics episode in Graphiti
    When a role knowledge summary is requested for "architect"
    Then the summary should be computed from the 3 valid episodes
    And a warning should be logged for the malformed episode

  # Why: Staleness detection with no patterns should complete without error
  @negative
  Scenario: Staleness detection for a role with no learned patterns
    Given the "architect" role has session metrics but no learned patterns
    When staleness detection runs for "architect"
    Then the staleness report should indicate no patterns to evaluate

  # ━━ GROUP D: Edge Cases (10 scenarios) ━━

  # Why: Cross-role isolation — one role's metrics must not leak into another's
  @edge-case
  Scenario: Metrics for different roles are isolated by group_id
    Given the "architect" role completes a session with 3 iterations
    And the "product-owner" role completes a session with 2 iterations
    When I query session metrics for group_id "role:architect"
    Then only the architect's metrics should be returned
    And no product-owner metrics should appear

  # Why: Rapid consecutive sessions should not produce duplicate or conflicting metrics
  @edge-case
  Scenario: Two sessions for the same role complete in rapid succession
    Given the "architect" role completes a session on project "finproxy"
    And the "architect" role immediately completes another session on project "gcse-tutor"
    When I query session metrics for group_id "role:architect"
    Then both sessions should have distinct metrics episodes
    And the role knowledge summary should aggregate both sessions

  # Why: Score history must preserve chronological ordering for trend analysis
  @edge-case
  Scenario: Session metrics preserve score history in chronological order
    Given a session with score history [0.45, 0.52, 0.38, 0.61, 0.72]
    When the session metrics are written to Graphiti
    Then the score_history field should contain the scores in the original order

  # Why: Compounding report must handle roles with different session counts
  # [ASSUMPTION: confidence=low] --all-roles flag on report subcommand
  @edge-case
  Scenario: CLI report across multiple roles shows per-role summaries
    Given the "architect" role has 10 session metrics
    And the "product-owner" role has 3 session metrics
    And the "ideation" role has 0 session metrics
    When I run "specialist-agent report --all-roles"
    Then the report should show summaries for "architect" and "product-owner"
    And the report should indicate "ideation" has no data

  # Why: Partial write must not leave corrupted episodes in the graph
  @edge-case
  Scenario: Metrics write interrupted mid-operation does not leave partial episodes
    Given a greenfield session completes successfully
    And the Graphiti connection drops during the metrics write
    When the write operation fails partway through
    Then no partial metrics episode should exist in Graphiti
    And the failure should be logged with the episode content for manual recovery

  # Why: Concurrent sessions completing for the same role must not corrupt the summary
  @edge-case
  Scenario: Role knowledge summary handles concurrent session completion
    Given the "architect" role has two sessions completing simultaneously
    And both sessions trigger a role knowledge summary update
    When both summary writes execute
    Then the final summary should reflect data from both sessions
    And no summary data should be lost or duplicated

  # Why: Malformed scores from LLM parse errors must not corrupt aggregate metrics
  @edge-case
  Scenario: Score history containing invalid values is sanitised before writing
    Given a session produces a score history containing a parse failure placeholder
    When the session metrics are written to Graphiti
    Then invalid score entries should be excluded from the metrics episode
    And the metrics episode should record the count of excluded scores
    And a warning should be logged for each excluded score

  # Why: Stale Graphiti cache during summary could produce outdated aggregation
  @edge-case
  Scenario: Role knowledge summary uses fresh data despite Graphiti caching
    Given the "architect" role just completed a new session
    And the metrics episode was successfully written
    When a role knowledge summary is generated immediately after
    Then the summary should include the newly written session metrics
    And the summary should not reflect only previously cached data

  # Why: Empty results for a known-populated role indicate a query or connectivity issue
  @edge-case
  Scenario: CLI report warns when Graphiti returns empty results for a populated role
    Given the "architect" role has session metrics in Graphiti
    And the Graphiti query returns zero results due to a transient issue
    When I run "specialist-agent report --role architect"
    Then the output should warn that results may be incomplete
    And the output should suggest retrying or checking Graphiti connectivity

  # Why: Crafted role_id must not allow cross-scope group_id access
  @edge-case @negative
  Scenario: Role ID with path traversal is rejected before Graphiti query
    Given a role_id of "../../appmilla-fleet"
    When session metrics or a report is requested for this role
    Then the request should be rejected with a validation error
    And no Graphiti query should be executed with the crafted group_id
