# Generated by /feature-spec
# Feature: DDD Context Map Generation
# Stack: python
# Assumptions: 5 (see ddd-context-map-generation_assumptions.yaml)
# Generated: 2026-04-12T00:00:00Z

@ddd-context-map-generation
Feature: DDD Context Map Generation
  As an architecture team lead
  I want the Player to identify bounded contexts from product docs and generate a DDD context map with labelled relationship patterns
  So that conversation starters communicate domain boundaries and integration strategies — not just container structure

  Background:
    Given the adversarial cooperation system is configured with weighted evaluation
    And the Player agent has DDD context map instructions in its system prompt
    And the Coach agent evaluates DDD quality as part of the boundary_clarity criterion
    And the formatter supports an optional DDD Context Map section

  # --- GROUP A: Key Examples ---

  # Why: Core path — Player identifies bounded contexts from product docs and produces a context map
  @key-example @smoke
  Scenario: Player generates a DDD context map when bounded contexts are identifiable
    Given product documentation describing an open banking platform with user authentication, transaction retrieval, and payment initiation
    When the Player generates a conversation starter
    Then the output should include a "DDD Context Map" section
    And the section should contain a Mermaid diagram
    And the diagram should label at least 2 bounded contexts

  # Why: Core path — relationship patterns must be named, not generic arrows
  @key-example @smoke
  Scenario: Player labels context map relationships with DDD patterns
    Given product documentation with an identity context consuming tokens from an auth provider
    When the Player generates a DDD context map
    Then relationships between bounded contexts should be labelled with DDD patterns
    And acceptable patterns include "Published Language", "Customer-Supplier", "ACL", "Open Host Service", "Shared Kernel", "Conformist", and "Separate Ways"

  # Why: Core path — context map must be consistent with C4 Container diagram
  @key-example @smoke
  Scenario: DDD context map is consistent with the C4 Container diagram
    Given product documentation describing 3 services
    When the Player generates both a C4 Container diagram and a DDD context map
    Then every bounded context in the context map should correspond to at least one container in the C4 diagram
    And no bounded context should reference a container not present in the C4 diagram

  # Why: Formatter renders the optional section in the correct position
  @key-example @smoke
  Scenario: Formatter renders DDD Context Map section between C4 Container and Preferred Decisions
    Given a ConversationStarter with a context_map-level C4Diagram present
    When the formatter renders the output
    Then the "DDD Context Map" section should appear after "C4 Level 2: Container Diagram"
    And the "DDD Context Map" section should appear before "Preferred Decisions"
    And the total section count should be 12

  # Why: Handler must parse the optional section so it survives the parse-validate-format round-trip
  @key-example @smoke
  Scenario: Handler parses DDD Context Map section from raw Player markdown
    Given raw Player markdown containing a "DDD Context Map" heading with a Mermaid code fence
    When the handler parses the markdown
    Then the resulting ConversationStarter should include a C4Diagram with level "context_map"
    And the diagram mermaid_content should match the raw input

  # Why: Coach evaluates DDD quality as part of boundary_clarity — not a new criterion
  @key-example @smoke
  Scenario: Coach evaluates DDD context map quality within boundary_clarity criterion
    Given a Player output with a DDD context map containing 3 bounded contexts and labelled relationships
    When the Coach evaluates the output
    Then the boundary_clarity score should reflect the presence of named DDD patterns
    And the boundary_clarity reasoning should reference bounded context and relationship quality

  # --- GROUP B: Boundary Conditions ---

  # [ASSUMPTION: confidence=medium] Minimum bounded contexts for a context map is 2
  # Why: Just-inside boundary — minimum viable context map has 2 bounded contexts
  @boundary
  Scenario: Context map with exactly 2 bounded contexts is accepted
    Given product documentation describing exactly 2 distinct domain areas
    When the Player generates a DDD context map
    Then the context map should contain exactly 2 bounded contexts
    And the context map should be accepted by the Coach

  # [ASSUMPTION: confidence=medium] Minimum bounded contexts for a context map is 2
  # Why: Just-outside boundary — a single bounded context does not warrant a context map
  @boundary @negative
  Scenario: Player does not generate a context map when only 1 bounded context is identifiable
    Given product documentation describing a single-purpose microservice with no external domain boundaries
    When the Player generates a conversation starter
    Then the output should not include a "DDD Context Map" section
    And the formatter should render exactly 11 sections

  # Why: Boundary — section is optional, formatter must handle its absence gracefully
  @boundary
  Scenario: Formatter renders exactly 11 sections when no context map is present
    Given a ConversationStarter with no context_map-level C4Diagram
    When the formatter renders the output
    Then the total section count should be 11
    And no "DDD Context Map" heading should appear

  # [ASSUMPTION: confidence=high] All 7 DDD relationship patterns from Evans (2003) and Vernacular (2016) are valid labels
  # Why: Boundary — each of the 7 recognised DDD patterns should be accepted
  @boundary
  Scenario Outline: Each DDD relationship pattern is a valid label
    Given a DDD context map with a relationship labelled "<pattern>"
    When the Coach evaluates the boundary_clarity criterion
    Then the pattern should be recognised as valid

    Examples:
      | pattern            |
      | Published Language |
      | Customer-Supplier  |
      | ACL                |
      | Open Host Service  |
      | Shared Kernel      |
      | Conformist         |
      | Separate Ways      |

  # [ASSUMPTION: confidence=medium] boundary_clarity score ceiling is 0.5 when relationships are unlabelled
  # Why: Boundary — unlabelled relationships should be penalised
  @boundary @negative
  Scenario: Context map with unlabelled relationships reduces boundary_clarity score
    Given a DDD context map where all relationships are shown as plain arrows without pattern labels
    When the Coach evaluates the output
    Then the boundary_clarity score should be at most 0.5

  # --- GROUP C: Negative Cases ---

  # Why: Generic arrows without pattern names are the exact anti-pattern this feature addresses
  @negative
  Scenario: Coach penalises context map with generic relationship labels instead of DDD patterns
    Given a DDD context map where relationships are labelled "uses", "calls", or "depends on"
    When the Coach evaluates the output
    Then the boundary_clarity reasoning should note the absence of DDD relationship patterns
    And the boundary_clarity score should be reduced

  # Why: Bounded contexts must trace to product documentation — no phantom contexts
  @negative
  Scenario: Coach detects PHANTOM when bounded context is not traceable to product docs
    Given product documentation mentioning "Payment Service" and "User Service"
    And the Player's context map includes a "Recommendation Engine" bounded context not in the docs
    When the Coach evaluates the output
    Then the Coach should report a PHANTOM detection finding referencing the ungrounded context

  # Why: Context map must use Mermaid syntax for renderability
  @negative
  Scenario: Handler ignores context map section without a valid Mermaid code fence
    Given raw Player markdown with a "DDD Context Map" heading but only prose text and no Mermaid block
    When the handler parses the markdown
    Then no context_map-level C4Diagram should be extracted
    And the formatter should render 11 sections without a DDD Context Map section

  # Why: Scope creep — context map should not introduce services beyond product documentation scope
  @negative
  Scenario: Coach detects SCOPE_CREEP when context map adds domains beyond product scope
    Given product documentation scoped to 3 bounded contexts
    And the Player's context map includes 6 bounded contexts with 3 not evidenced in the docs
    When the Coach evaluates the output
    Then the Coach should report a SCOPE_CREEP detection finding

  # Why: Context map inconsistent with C4 Container should be flagged
  @negative
  Scenario: Coach flags inconsistency between context map and C4 Container diagram
    Given a C4 Container diagram showing 4 containers
    And a DDD context map referencing a bounded context with no corresponding container
    When the Coach evaluates the output
    Then the boundary_clarity reasoning should note the inconsistency between context map and C4 diagram

  # --- GROUP D: Edge Cases ---

  # Why: Player should handle revision — Coach rejects bad map, Player fixes it
  @edge-case
  Scenario: Player revises context map after Coach rejection for missing pattern labels
    Given the Coach has rejected Player output with boundary_clarity feedback citing unlabelled relationships
    When the Player revises the context map
    Then the revised map should label each relationship with a DDD pattern
    And the revised output should score higher on boundary_clarity

  # Why: Product docs may describe contexts without using DDD terminology — Player must infer
  @edge-case
  Scenario: Player identifies bounded contexts from product docs that do not use DDD terminology
    Given product documentation that describes "the billing module" and "the user management module" without using the term "bounded context"
    When the Player generates a DDD context map
    Then the context map should identify "Billing" and "User Management" as bounded contexts
    And the relationships should be labelled with appropriate DDD patterns

  # Why: Shared Kernel is a special relationship pattern — both contexts share code/schema
  @edge-case
  Scenario: Context map correctly represents Shared Kernel between two bounded contexts
    Given product documentation describing a shared authentication schema used by two services
    When the Player generates a DDD context map
    Then the relationship between those contexts should be labelled "Shared Kernel"

  # Why: Parse-validate-format round-trip must preserve the context map
  @edge-case @regression
  Scenario: Context map survives the parse-validate-format round-trip
    Given raw Player markdown containing a DDD Context Map section with a Mermaid diagram
    When the handler parses the markdown into a ConversationStarter
    And the formatter renders the ConversationStarter back to markdown
    Then the output markdown should contain the DDD Context Map section
    And the Mermaid diagram content should be preserved

  # --- EDGE CASE EXPANSION: Regression & Integration ---

  # Why: Regression — existing 11-section output must not break when no context map is present
  @edge-case @regression
  Scenario: Existing 11-section output is unchanged when DDD feature is active but no context map is generated
    Given product documentation for a single-service application with no identifiable bounded contexts
    When the Player generates a conversation starter with DDD instructions active
    Then the output should contain exactly 11 sections
    And the output should match the pre-DDD section structure exactly

  # Why: Regression — handler must still extract context/container/component diagrams correctly
  @edge-case @regression
  Scenario: Handler continues to extract context and container C4 diagrams after context_map support is added
    Given raw Player markdown containing C4 Level 1 (context), C4 Level 2 (container), and DDD Context Map sections
    When the handler parses the markdown
    Then the resulting ConversationStarter should include a C4Diagram with level "context"
    And a C4Diagram with level "container"
    And a C4Diagram with level "context_map"
    And the ConversationStarter model validation should pass

  # Why: Integration — domain fidelity rules apply to bounded context names too
  @edge-case
  Scenario: Coach detects DOMAIN_DILUTION when bounded context names are genericised
    Given product documentation naming "FinProxy Settlement" as a domain area
    And the Player's context map labels that bounded context as "Settlement Service"
    When the Coach evaluates the output
    Then the Coach should report a DOMAIN_DILUTION detection finding
    And the finding should reference the genericised bounded context name

  # Why: Integration — SOURCE_COLLAPSE detection applies to context map descriptions
  @edge-case
  Scenario: Context map descriptions use domain-specific language consistent with source documents
    Given product documentation with 3 named bounded contexts from 3 separate source documents
    When the Player generates a DDD context map
    Then each bounded context description should trace to a specific source document
    And the Coach should not flag SOURCE_COLLAPSE for the context map section

  # Why: Structural — context_map is an additional diagram, not a replacement for required context+container
  @edge-case @regression
  Scenario: ConversationStarter validation still requires context and container diagrams even when context_map is present
    Given a ConversationStarter with only a context_map-level C4Diagram and no context or container diagrams
    When the ConversationStarter model is validated
    Then validation should fail with an error requiring at least 2 C4 diagrams at context and container levels
