# Generated by /feature-spec
# Feature: FinProxy Fine-Tune vs Frontier Comparison
# Stack: python
# Assumptions: 9 (see finproxy-fine-tune-vs-frontier-comparison_assumptions.yaml)
# Generated: 2026-05-06T12:58:46Z

@finproxy-fine-tune-vs-frontier-comparison @phase-rag @feat-rag-07-03
Feature: FinProxy Fine-Tune vs Frontier Comparison Harness
  As a Phase RAG researcher
  I want to re-execute the four FinProxy align payloads against the local
    architect fine-tune and score the results against the GPT-5.5 baseline
  So that I can answer the Phase RAG thesis: does a specialist fine-tuned SLM
    plus retrieval match or exceed a frontier cloud model for FinProxy-class
    architectural reviews

  Background:
    Given the GPT-5.5 baseline review for FinProxy is on disk
    And the local architect fine-tune is reachable via llama-swap
    And the architecture knowledge index has been populated from the architecture-books dataset
    And the Player has the architecture knowledge query tool wired in
    And the four canonical FinProxy align payloads are the broad architecture review, the modular-monolith ADR, the Keycloak-FAPI-Organizations ADR, and the REST-vs-NATS ADR

  # ── GROUP A: Key Examples ───────────────────────────────────────────────

  # Why: Core path — running the harness produces a fine-tune review for every baseline session
  @task:TASK-FFC3-003
  @key-example @smoke
  Scenario: All four baseline payloads are re-executed against the local fine-tune
    Given the four baseline align payloads exist in the GPT-5.5 baseline run
    # [ASSUMPTION: confidence=medium] Harness reuses the existing specialist-agent align CLI with --player-model local
    When the comparison harness is run against the local fine-tune
    Then a fine-tune review should be produced for each of the four payloads
    And every fine-tune review should be paired with its baseline counterpart
    And no payload should be skipped or substituted

  # Why: Core deliverable — the side-by-side review report
  @task:TASK-FFC3-005
  @key-example @smoke
  Scenario: A side-by-side comparison report is produced
    Given the harness has completed all four fine-tune sessions
    When the comparison is written
    Then a side-by-side review report should be produced at the canonical reviews location
    And the report should pair each fine-tune session with its GPT-5.5 baseline counterpart
    And the report should score every session on the five evaluation axes

  # Why: The thesis verdict — SLM-vs-frontier
  @task:TASK-FFC3-005
  @key-example
  Scenario: The report states a clear verdict on the Phase RAG thesis
    Given the comparison report is being written
    # [ASSUMPTION: confidence=low] Verdict mapping: "≥ baseline" if parity on all 5 axes; "< baseline" if below parity on 3+ axes; "mixed" otherwise
    When the verdict section is composed
    Then the verdict should state whether the fine-tune meets or exceeds the GPT-5.5 baseline
    And the verdict should be either "fine-tune ≥ baseline", "fine-tune < baseline", or "mixed — see per-axis"
    And the verdict should reference the per-axis findings that justify it

  # Why: Replay fidelity — the comparison must be apples-to-apples
  @task:TASK-FFC3-003
  @key-example
  Scenario: Every fine-tune session uses the same context, proposal, and question as its baseline counterpart
    Given the GPT-5.5 baseline captured the four align payloads
    When the harness replays a payload against the local fine-tune
    Then the context, proposal, and question text should be identical to the baseline
    And only the player model should differ

  # Why: Trained-prompt and think-block handling are load-bearing for fairness (FEAT-RAG-05)
  @task:TASK-FFC3-003
  @key-example
  Scenario: The fine-tune session uses the trained prompt and strips think blocks before scoring
    Given the local provider is selected
    When the harness runs a fine-tune session
    Then the Player should be invoked with the GOAL.md-trained system prompt
    And any think blocks emitted by the fine-tune should be preserved in the session log
    And think blocks should be stripped before the Coach evaluates the output

  # ── GROUP B: Boundary Conditions ────────────────────────────────────────

  # Why: Just-inside boundary — fine-tune meets the target score
  @task:TASK-FFC3-004
  @boundary
  Scenario Outline: Fine-tune meeting or exceeding the Coach target score is reported as a pass
    Given the fine-tune session produced a Coach composite score of <score>
    And the architect role's target score is 0.75
    When the per-session verdict is written
    Then the session should be reported as <verdict>

    Examples:
      | score | verdict           |
      | 0.75  | meets target      |
      | 0.80  | exceeds target    |
      | 0.60  | passes threshold  |

  # Why: Just-outside boundary — fine-tune below the pass threshold
  @task:TASK-FFC3-004
  @boundary @negative
  Scenario: A fine-tune session below the pass threshold is reported as failed
    Given the fine-tune session produced a Coach composite score of 0.59
    And the architect role's pass threshold is 0.60
    When the per-session verdict is written
    Then the session should be reported as below the pass threshold

  # Why: Coverage axis floor — fine-tune surfaces the same bounded contexts and ADRs
  @task:TASK-FFC3-005
  @boundary
  Scenario: Coverage parity requires the fine-tune to surface the same bounded contexts and ADRs as the baseline
    Given the GPT-5.5 baseline cited a set of bounded contexts and ADRs
    When the coverage axis is scored
    Then the fine-tune should be marked as parity if it cites the same set or a superset
    And the fine-tune should be marked as below parity if any bounded context or ADR cited by the baseline is absent

  # Why: Citation-discipline floor — RAG should ground at least half of substantive claims
  @task:TASK-FFC3-005
  @boundary
  Scenario Outline: Citation discipline floor is fifty percent of substantive claims grounded to a source book
    Given the fine-tune session produced <claims> substantive claims
    # [ASSUMPTION: confidence=low] A "substantive claim" is a factual or evaluative statement about an architectural decision, pattern, force, or trade-off — excluding interrogatives, declared assumptions, and the verdict line
    And the citations grounded to a specific architecture book number <citations>
    When the citation-discipline axis is scored
    Then the session should be reported as <result>

    Examples:
      | claims | citations | result                    |
      | 10     | 5         | passes the citation floor |
      | 10     | 6         | passes the citation floor |
      | 10     | 4         | below the citation floor  |

  # Why: Phantom rate floor — fine-tune phantom count must not exceed baseline
  @task:TASK-FFC3-004
  @boundary
  Scenario Outline: Phantom rate is reported as parity when fine-tune findings do not exceed the baseline
    Given the GPT-5.5 baseline produced <baseline> phantom findings on a session
    And the fine-tune produced <finetune> phantom findings on the same session
    When the phantom-rate axis is scored
    Then the session should be reported as <result>

    Examples:
      | baseline | finetune | result                       |
      | 2        | 2        | parity                       |
      | 2        | 1        | better than baseline         |
      | 2        | 3        | regresses against baseline   |

  # Why: Five-axis coverage is mandatory in the report
  @task:TASK-FFC3-005
  @boundary
  Scenario: The report covers all five evaluation axes for every session
    Given the comparison report is being assembled
    When the per-session sections are written
    Then every session should be scored on coverage, trade-off depth, citation discipline, phantom rate, and Coach acceptance
    And no axis should be omitted or marked "not assessed" without an explicit reason

  # Why: Six-criteria fidelity — the Coach scoring uses the architect role's weighted criteria
  @task:TASK-FFC3-004
  @boundary
  Scenario: Coach acceptance is computed against the same six weighted criteria as the baseline
    Given the architect role defines six weighted criteria with composite scoring
    When the fine-tune session is evaluated by the Coach
    Then the Coach should score every criterion
    And the composite score should be computed using the same weights as the baseline run

  # Why: Detection patterns — the four pattern categories must be tracked
  @task:TASK-FFC3-004
  @boundary
  Scenario: The phantom-rate axis tracks PHANTOM, UNGROUNDED, SCOPE_CREEP, and MISSING_TRADEOFF findings
    # [ASSUMPTION: confidence=medium] The phantom-rate axis counts the four classic-hallucination patterns; SOURCE_COLLAPSE, DOMAIN_DILUTION, and UNSTATED_ASSUMPTION (also defined in criteria/definitions.yaml) are excluded from this rate metric
    Given the architect role defines the PHANTOM, UNGROUNDED, SCOPE_CREEP, and MISSING_TRADEOFF detection patterns
    When the phantom-rate axis is scored
    Then findings of all four pattern categories should be counted
    And each pattern's count should be reported per session

  # ── GROUP C: Negative Cases ─────────────────────────────────────────────

  # Why: Cannot compare without a baseline
  @task:TASK-FFC3-001
  @negative
  Scenario: The harness refuses to run if the GPT-5.5 baseline is not on disk
    Given the GPT-5.5 baseline review and per-session outputs are not on disk
    When the comparison harness is run
    Then the harness should refuse to start
    And the researcher should be told that the baseline is required

  # Why: Cannot run the local provider if llama-swap is unreachable
  @task:TASK-FFC3-003
  @negative
  Scenario: The harness reports unavailability when the local fine-tune cannot be reached
    Given the local fine-tune endpoint cannot be reached
    When the harness attempts to start a fine-tune session
    Then the harness should stop before invoking the Player
    And the researcher should be told that the local fine-tune is unreachable

  # Why: Cannot test the thesis without retrieval
  @task:TASK-FFC3-001
  @negative
  Scenario: The harness warns when the architecture knowledge index is empty
    Given the architecture knowledge collection contains no entries
    When the harness is started
    Then the researcher should be warned that retrieval will return nothing
    And the warning should explain that citation discipline cannot be assessed under these conditions

  # Why: Re-running must not silently overwrite a previous comparison
  @task:TASK-FFC3-001
  @negative
  Scenario: The harness refuses to overwrite a previous comparison report without explicit confirmation
    Given a previous comparison report already exists at the canonical reviews location
    # [ASSUMPTION: confidence=low] "Explicit overwrite intent" is expressed as an --overwrite CLI flag on the harness invocation
    When the harness is re-run without the overwrite intent declared
    Then the harness should refuse to overwrite the report
    And the researcher should be told to declare overwrite intent or choose a new path

  # Why: Question payloads must be the canonical four
  @task:TASK-FFC3-001
  @negative
  Scenario: The harness rejects a payload set that does not match the four baseline align payloads
    Given a payload set is supplied that omits one of the four baseline align payloads
    When the harness is started
    Then the harness should refuse to run
    And the researcher should be told that the payload set must match the baseline payloads exactly

  # ── GROUP D: Edge Cases ─────────────────────────────────────────────────

  # Why: Tool non-use is itself a finding (per scope §Citation discipline: "failure to use the tool at all is a thesis-level miss")
  @task:TASK-FFC3-004
  @edge-case
  Scenario: A fine-tune session that never invokes the architecture knowledge query tool is flagged
    Given the fine-tune session produces a review without invoking the architecture knowledge query tool
    When the citation-discipline axis is scored
    Then the session should be flagged as "tool not used"
    And the comparison report should call this out explicitly as a thesis-level finding

  # Why: Drift-finding probe is the canonical "did the model spot something real" test
  @task:TASK-FFC3-005
  @edge-case @regression
  Scenario: The drift finding from Session 1 of the baseline is checked against the fine-tune output
    # [ASSUMPTION: confidence=medium] The drift-finding probe is reported separately as a regression-class probe; not folded into the trade-off depth score itself
    Given the GPT-5.5 baseline Session 1 identified the conversation-starter drifting from the accepted ADR set
    When the fine-tune Session 1 review is scored
    Then the report should record whether the fine-tune surfaced the same drift
    And the trade-off depth axis should be adjusted based on whether the drift was caught

  # Why: Forces-in-tension surfaced by one model and missed by the other are load-bearing for trade-off depth
  @task:TASK-FFC3-005
  @edge-case
  Scenario: Forces in tension surfaced by exactly one of the two models are recorded per session
    Given the fine-tune surfaces a force in tension on a session
    And the GPT-5.5 baseline does not surface the same force on the same session
    When the trade-off depth axis is scored
    Then the asymmetric finding should be recorded against the fine-tune
    And the same record should be produced in reverse if the baseline surfaces a force the fine-tune misses

  # Why: Mixed verdicts must be representable
  @task:TASK-FFC3-005
  @edge-case
  Scenario: The verdict reflects that fine-tune wins on some axes and loses on others
    Given the fine-tune meets parity on three axes
    And the fine-tune is below parity on two axes
    When the verdict is composed
    Then the verdict should be reported as "mixed"
    And the report should name which axes the fine-tune wins on and which it loses on

  # Why: One session can fail at runtime without invalidating the rest
  @task:TASK-FFC3-005
  @edge-case
  Scenario: A single fine-tune session failing at runtime does not abort the whole comparison
    Given three of the four fine-tune sessions completed successfully
    And one fine-tune session failed at runtime
    When the comparison report is assembled
    Then the report should include the three completed sessions
    And the report should mark the fourth session as "did not complete"
    And the verdict should explicitly state that it is based on three of four sessions

  # Why: The baseline must not be regenerated mid-comparison or comparison fairness is compromised
  @task:TASK-FFC3-005
  @edge-case
  Scenario: The harness records the baseline run identifier so a stale comparison can be detected later
    Given the GPT-5.5 baseline was produced on a specific date with a specific OpenAI model identifier
    When the comparison report is written
    Then the report header should record the baseline run date and model identifier
    And the fine-tune model identifier and run date should be recorded alongside

  # ── Edge Case Expansion: Security / Data Integrity ──────────────────────

  # Why: Audit trail — raw fine-tune output must survive verbatim for diagnosis
  @task:TASK-FFC3-003
  @edge-case @audit
  Scenario: The fine-tune raw output is preserved verbatim for audit even when the report uses a stripped version
    Given the fine-tune emits a session output containing think blocks
    # [ASSUMPTION: confidence=medium] Raw per-session outputs are persisted under output/finproxy-fine-tune/ mirroring the output/finproxy-baseline-gpt-5.5/ naming convention
    When the comparison report is written
    Then the raw fine-tune output should be persisted unaltered for that session
    And the report's quoted excerpts should use the think-stripped version
    And the path to the raw output should be recorded next to the excerpt

  # Why: Comparison integrity — same trained prompt across runs or the comparison drifts
  @task:TASK-FFC3-005
  @edge-case @reproducibility
  Scenario: The trained-prompt artefact identity is recorded so the comparison cannot be silently re-run against a different prompt
    Given the local fine-tune was invoked using the trained Player prompt artefact
    When the comparison report is written
    Then the report should record the trained-prompt artefact path
    And the report should record the artefact's sha256 hex first-twelve characters
    And re-running the comparison against a different artefact identity should be flagged in the report header

  # Why: D5 invariant — the Coach must not gain tools during the comparison run
  @task:TASK-FFC3-004
  @edge-case @invariant
  Scenario: The Coach inventory is asserted to remain empty during the comparison run
    Given the harness invokes the Coach to score the fine-tune output
    When the Coach is constructed for each session
    Then the Coach tool inventory should be the empty set
    And any non-empty Coach inventory should abort the harness with the D5 invariant violation reported

  # ── Edge Case Expansion: Concurrency ────────────────────────────────────

  # Why: Embedding backend saturation can silently degrade retrievals
  @task:TASK-FFC3-003
  @edge-case @concurrency
  Scenario: Parallel fine-tune sessions do not silently drop retrievals when the embedding backend is saturated
    # [ASSUMPTION: confidence=medium] All four sessions run in parallel by default, mirroring the baseline runbook's backgrounded-jobs pattern; a sequential fallback is available for diagnosis
    Given the four fine-tune sessions are running in parallel
    And the embedding backend rate-limits or queues some requests
    When a session's retrieval call is delayed beyond its retrieval window
    Then the affected session should be annotated with a retrieval-degraded note
    And no retrieval should be silently dropped without leaving a trace in the session log

  # Why: Two harness runs racing the report file would corrupt the comparison
  @task:TASK-FFC3-003
  @edge-case @concurrency
  Scenario: A second comparison run started while the first is in flight is rejected
    Given a comparison harness run is already in progress and writing to the report file
    When a second comparison harness run is started against the same report path
    Then the second run should be rejected before invoking the Player
    And the researcher should be told that a comparison run is already in progress

  # ── Edge Case Expansion: Integration Boundaries ─────────────────────────

  # Why: Mid-session retrieval failure should degrade, not abort
  @task:TASK-FFC3-003
  @edge-case @degradation
  Scenario: The architecture knowledge collection becoming unreachable mid-session marks the session as degraded
    Given a fine-tune session has begun and made at least one successful retrieval
    When the architecture knowledge collection becomes unreachable for the remainder of the session
    Then the session should complete on whatever retrievals it already has
    And the session should be marked as "retrieval degraded" in the comparison report
    And the citation-discipline score for that session should note the degradation

  # Why: Coach JSON parse failure must not be invisible
  @task:TASK-FFC3-005
  @edge-case @evaluation
  Scenario: A fine-tune session whose output the Coach cannot parse is flagged as evaluation-failed
    Given the fine-tune produced output that the Coach cannot parse as a valid verdict
    When the comparison report is assembled
    Then the session should be marked as "evaluation failed"
    And the session should not be silently dropped from the report
    And the verdict should explicitly state that it is based on the parseable sessions only

  # Why: Embedding-endpoint timeout per session is a real-world failure mode
  @task:TASK-FFC3-003
  @edge-case @degradation
  Scenario: An embedding-endpoint timeout for a session's retrievals is reported as retrieval degraded
    Given the embedding endpoint times out on a session's retrieval calls
    When that session's review is scored
    Then the session should be annotated as "retrieval degraded"
    And the citation-discipline score for that session should reflect the limited retrieval evidence
