# Generated by /feature-spec
# Feature: ChromaDB Ingestion of the Architecture Knowledge Index
# Stack: python
# Assumptions: 6 (see chromadb-architecture-knowledge-ingestion_assumptions.yaml)
# Generated: 2026-05-04T00:00:00Z

@chromadb-architecture-knowledge-ingestion
Feature: ChromaDB Ingestion of the Architecture Knowledge Index
  As an architect-role operator wiring up Phase RAG
  I want a one-shot script that loads the knowledge.jsonl dataset into a named Chroma collection with full metadata fidelity
  So that the Player's architecture_knowledge_query tool has a populated retrieval substrate and the SLM-vs-frontier comparison thesis can be tested

  Background:
    Given the rag optional-dependency group is installed
    And the knowledge index file at "data/rag_index/knowledge.jsonl" contains ShareGPT-formatted records with a system, user, assistant message triple and the seven metadata keys (dimension, source_books, topic, layer, source, turns, type)
    And an Ollama embeddings endpoint serving the nomic-embed-text model is reachable

  # ------------------------------------------------------------------
  # GROUP A: Key Examples
  # ------------------------------------------------------------------

  # Why: Core happy-path — proves the script populates the collection from a fresh start
  @task:TASK-RAG02-003
  @key-example @smoke
  Scenario: First-time ingestion populates the architect knowledge collection
    Given the knowledge index file contains 1102 valid records
    And no Chroma collection named "architect-knowledge-v1" exists
    When I run the architecture knowledge ingestion script
    Then a Chroma collection named "architect-knowledge-v1" should exist
    And the collection should contain 1102 stored examples
    And the run summary should report 1102 ingested and 0 skipped

  # Why: Idempotency contract — deterministic IDs prevent duplication on re-run
  @task:TASK-RAG02-003
  @key-example @smoke
  Scenario: Re-running ingestion against an unchanged index does not duplicate records
    Given the knowledge collection has already been ingested once
    When I run the architecture knowledge ingestion script a second time
    Then the collection size should remain unchanged
    And the run summary should report 0 newly ingested and 1102 skipped as already present

  # Why: Metadata fidelity is what FEAT-RAG-03 filters on — must round-trip exactly
  @task:TASK-RAG02-003
  @key-example @smoke
  Scenario: Each ingested record carries the full seven-key metadata payload
    Given the knowledge index file contains a record with metadata
      | key          | value                       |
      | dimension    | strategic_ddd               |
      | source_books | ["evans_ddd","vernon_iddd"] |
      | topic        | bounded_context             |
      | layer        | knowledge                   |
      | source       | synthetic                   |
      | turns        | 1                           |
      | type         | reasoning                   |
    When I run the architecture knowledge ingestion script
    Then the corresponding stored example should expose all seven metadata keys with their original values
    And each metadata key should be queryable as a Chroma where-filter

  # Why: The <think> block is load-bearing for fine-tune retrieval — must not be stripped at ingestion time
  @task:TASK-RAG02-003
  @key-example
  Scenario: The assistant content including the think block is preserved verbatim
    Given a record whose assistant content begins with a "<think>" block followed by the visible architect response
    When I run the architecture knowledge ingestion script
    Then the stored example content should include the entire think block
    And the stored example content should include the visible response that follows

  # ------------------------------------------------------------------
  # GROUP B: Boundary Conditions
  # ------------------------------------------------------------------

  # Why: Just-inside boundary — the smoke-test fixture sizes named in the description
  @task:TASK-RAG02-003
  @boundary
  Scenario Outline: A small fixture index ingests cleanly and reports the expected count
    Given the knowledge index file contains <count> valid records
    When I run the architecture knowledge ingestion script
    Then the collection should contain <count> stored examples

    Examples:
      | count |
      | 3     |
      | 5     |

  # Why: Empty input is a defined no-op rather than an error — useful for first-day setup
  @task:TASK-RAG02-003
  @boundary
  Scenario: An empty knowledge index produces an empty collection without error
    Given the knowledge index file contains 0 records
    When I run the architecture knowledge ingestion script
    Then the collection should exist with 0 stored examples
    And the script should exit successfully

  # Why: Just-outside the assistant-content contract — record cannot be embedded
  @task:TASK-RAG02-004
  @boundary @negative
  Scenario: A record without the expected assistant message is skipped with a warning
    Given the knowledge index file contains a record whose messages array has only system and user roles
    When I run the architecture knowledge ingestion script
    Then that record should be skipped
    And the run summary should report it under "records skipped: missing assistant content"
    And the rest of the index should still ingest successfully

  # Why: Boundary on the deterministic ID — two records with identical user content share an ID
  # [ASSUMPTION: confidence=medium] Deterministic ID is SHA-256 of messages[1].content, hex-encoded, prefixed with "kn-"
  @task:TASK-RAG02-004
  @boundary
  Scenario: Two records with identical user content resolve to the same deterministic ID
    Given the knowledge index file contains two records whose user messages are identical
    When I run the architecture knowledge ingestion script
    Then only one example should be stored under the shared deterministic ID
    And the run summary should flag the collision under "records skipped: duplicate id"

  # ------------------------------------------------------------------
  # GROUP C: Negative Cases
  # ------------------------------------------------------------------

  # Why: Operator must not silently get a partial collection if the embedder is offline
  @task:TASK-RAG02-004
  @negative
  Scenario: An unreachable embedding endpoint causes the script to fail clearly
    Given the configured Ollama embeddings endpoint cannot be reached
    When I run the architecture knowledge ingestion script
    Then the script should exit with a non-zero status
    And the error should identify the embeddings endpoint as the cause
    And no partially-populated collection should be left behind

  # Why: Malformed input must surface line-number context, not a bare stack trace
  @task:TASK-RAG02-004
  @negative
  Scenario: A malformed JSONL line is reported with its line number
    Given the knowledge index file contains a record on line 42 that is not valid JSON
    When I run the architecture knowledge ingestion script
    Then the script should report that line 42 of the knowledge index could not be parsed
    And the script should exit without writing any records to the collection

  # Why: Missing required metadata is a contract violation, not a soft warning
  @task:TASK-RAG02-004
  @negative
  Scenario: A record missing a required metadata key is reported and excluded
    Given the knowledge index file contains a record whose metadata omits the "dimension" key
    When I run the architecture knowledge ingestion script
    Then that record should be excluded from the collection
    And the run summary should list the offending record under "records skipped: missing required metadata"

  # Why: Helpful error when the optional dependency was not installed
  @task:TASK-RAG02-004
  @negative
  Scenario: Running the script without the rag extra installed gives an actionable error
    Given the chromadb package is not importable
    When I run the architecture knowledge ingestion script
    Then the script should fail with a message naming the rag optional-dependency group
    And the message should suggest the installation command needed to proceed

  # Why: Collection name is the boundary between this dataset version and the next
  @task:TASK-RAG02-004
  @negative
  Scenario: An invalid Chroma collection name is rejected before any embedding work begins
    Given the configured collection name violates Chroma's naming rules
    When I run the architecture knowledge ingestion script
    Then the script should fail before any record is embedded
    And the error should explain which naming rule was violated

  # ------------------------------------------------------------------
  # GROUP D: Edge Cases
  # ------------------------------------------------------------------

  # Why: Resumability — the operator can interrupt and restart without re-embedding
  @task:TASK-RAG02-003
  @edge-case
  Scenario: An interrupted ingestion run resumes cleanly on the next invocation
    Given a previous ingestion run was interrupted after writing 600 of 1102 records
    When I run the architecture knowledge ingestion script again
    Then only the remaining 502 records should be embedded and written
    And the final collection size should equal 1102

  # Why: Drift detection — re-ingesting with a different embedding model is dangerous to mix
  @task:TASK-RAG02-004
  @edge-case
  Scenario: Re-ingesting against the same collection with a different embedding model is refused
    Given the existing collection was populated using "nomic-embed-text"
    When I run the architecture knowledge ingestion script with a different embedding model configured
    Then the script should refuse to proceed
    And the error should advise versioning the collection name (for example "architect-knowledge-v2") before switching embedding models

  # Why: Operator visibility — every key choice must be in the run summary for auditability
  @task:TASK-RAG02-003
  @edge-case
  Scenario: The run summary records the embedding model, collection name, and id strategy
    When I run the architecture knowledge ingestion script
    Then the run summary should report
      | item              |
      | rows ingested     |
      | rows skipped      |
      | embedding model   |
      | collection name   |
      | id hash strategy  |

  # Why: Re-running on a knowledge.jsonl that has grown since the previous ingestion
  @task:TASK-RAG02-003
  @edge-case
  Scenario: Adding new records to the index and re-running ingests only the new records
    Given the collection already contains 1102 examples from a previous run
    And 50 newly authored records have been appended to the knowledge index
    When I run the architecture knowledge ingestion script
    Then 50 new examples should be embedded and added
    And the 1102 existing examples should be reported as already present
    And the final collection size should equal 1152

  # Why: ADR-ARCH-013 needs to record refresh cadence — the script must declare the dataset version
  # [ASSUMPTION: confidence=medium] Source dataset version is SHA-256 of knowledge.jsonl contents, first 12 hex chars, prefixed "ds-"
  @task:TASK-RAG02-003
  @edge-case
  Scenario: The collection metadata records the source dataset version
    When I run the architecture knowledge ingestion script
    Then the collection's stored metadata should include the source dataset version identifier
    And subsequent runs should refuse to mix records from a different dataset version into the same collection

  # ------------------------------------------------------------------
  # EDGE CASE EXPANSION: Security
  # ------------------------------------------------------------------

  # Why: No-verbatim is a dataset-generation contract (GOAL.md §"No verbatim reproduction");
  # the ingestion script's responsibility is to surface potential leaks for upstream remediation
  # [ASSUMPTION: confidence=low] Verbatim detection is off by default; opt-in via "--detect-verbatim" flag — REVIEW REQUIRED
  @task:TASK-RAG02-005
  @edge-case @security
  Scenario: Records suspected of containing verbatim source prose are flagged in the run summary
    Given the knowledge index file contains a record whose assistant content includes a span of 16 or more consecutive verbatim words from a known source phrase
    When I run the architecture knowledge ingestion script with verbatim detection enabled
    Then the record should still be ingested into the collection
    And the run summary should list the offending record under "records flagged: possible verbatim reproduction"
    And the warning should identify the suspected source span by record id

  # Why: Endpoint URL must be treated as opaque — no shell expansion, no path-traversal substitution
  @task:TASK-RAG02-004
  @edge-case @security
  Scenario: The configured embeddings endpoint URL is treated as a literal value
    Given the configured Ollama endpoint URL contains characters that resemble shell metacharacters or path-traversal segments
    When I run the architecture knowledge ingestion script
    Then the URL should be used as-is when calling the embedder
    And no shell process should be invoked
    And no filesystem path outside the configured Chroma persistence directory should be touched

  # ------------------------------------------------------------------
  # EDGE CASE EXPANSION: Concurrency
  # ------------------------------------------------------------------

  # Why: Operator hits Ctrl-C mid-run — the script must exit cleanly without leaving a half-written batch
  @task:TASK-RAG02-004
  @edge-case @concurrency
  Scenario: An interrupt mid-batch leaves the collection in a consistent state
    Given the script is mid-way through embedding a batch of records
    When the operator interrupts the process
    Then the script should exit before writing the in-flight batch
    And the records already written in earlier batches should remain intact
    And re-running the script should resume from the next un-ingested record

  # ------------------------------------------------------------------
  # EDGE CASE EXPANSION: Integration boundaries
  # ------------------------------------------------------------------

  # Why: Embedding dimensionality is fixed for the lifetime of a collection;
  # a mismatch means the wrong model is in use and is not a recoverable runtime error
  # [ASSUMPTION: confidence=high] Expected embedding dimensionality is 768 (nomic-embed-text)
  @task:TASK-RAG02-004
  @edge-case @integration
  Scenario: An unexpected embedding dimensionality halts the run before any record is persisted
    Given the existing collection was created with embeddings of dimension 768
    When the configured embeddings endpoint returns vectors of a different dimensionality
    Then the script should detect the mismatch on the first response
    And the script should exit without persisting any record from this run
    And the error should advise verifying the embedding model selection
